- receiver/varnishreceiver/config.go
- receiver/varnishreceiver/config_test.go
The previous varnish tests depended on an os specific string for path errors. Due to using multierror it makes error checking a bit difficult using `errors.Is` so I removed the compound test and update tests to check errors for string contains of base error.
> fix(test): Fixed config tests for varnish to work on any OS

- .github/workflows/tests.yml
- Makefile
Temporary fix to ensure tests are being run on all submodules as the previous script to find submodules would not work on windows.
> fix(ci): Run CI tests on all submodules

- scripts/install/install_unix.sh
* When installing on linux through the install script, print the version that was just installed
* Final line of installer is something like: `Successfully installed version 0.4.0 of the observIQ OpenTelemetry collector.` 
* Add some newlines to add some space after post-install script message.
> feat: Print the package version on install

- config/google_cloud_exporter/hostmetrics/README.md
- config/google_cloud_exporter/prometheus/README.md
The initial documentation for hostmetrics and prometheus had mismatched setup instructions.
> fix: Add correct setup instructions to host metrics and prometheus

- receiver/varnishreceiver/documentation.md
- receiver/varnishreceiver/internal/metadata/generated_metrics_v2.go
- receiver/varnishreceiver/metadata.yaml
- receiver/varnishreceiver/metrics.go
- receiver/varnishreceiver/scraper.go
- receiver/varnishreceiver/scraper_test.go
- receiver/varnishreceiver/testdata/scraper/mock_response6_0.json
- receiver/varnishreceiver/testdata/scraper/mock_response6_5.json
This pr updates the metadata to reflect the scope doc. Small plural changes have been made to the names and a `client.request.error.count` metric is now collected with 3 codes(400, 417, 500).
Note, attributes of ints cannot be generated in the metadata and in the past the enum has been left blank intentionally like in [couchdb](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/couchdbreceiver/metadata.yaml#L12-L13). I have posted an image to show that the attribute can still be labeled though.
> feat(varnish metrics): Add client request error code metrics

- config/example.yaml
Added the following scrapers to the host metric receiver in the sample config:
- filesystem
- memory
- network
- cpu
- disk
Added notes in config that `cpu` and `disk` are not compatible on MacOS. See table in [Getting Started](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/hostmetricsreceiver#getting-started) of hostmetric receiver.
> feat(config): Modified default scrapers for hostmetric receiver in the sample config

- .github/workflows/release.yml
- Dockerfile
- Makefile
I will be writing some documentation on how to run the collector within Docker and Kubernetes. Before I do, I wanted to make sure the collector image is up to date.
- Enabled arm64 image builds when running the release workflow
- Refactored Dockerfile
- Use Ubuntu 22.04 based stanza base image (previous 20.10 based image is no longer supported, apt repos do not work)
- Run as non root user by default: `otel`
- Removed /etc/otel, this is created when mounting a config.yaml.
The largest change is the switch from root to otel user. Generally, we should be running container processes with a non root user. The documentation will include examples on how to run as root (and more importantly, when it is necessary).
**Testing**
I have tested the following usecases
- Docker / Docker compose
- …
> Dockerfile refactor

- .goreleaser.yml
- Makefile
- buildscripts/download-dependencies.sh
- scripts/package/postinstall.sh
- windows/scripts/build-msi.sh
- windows/test/install.rb
- windows/wix.json
Stateful receivers will likely make use of the storage extension. For example, reading log files (saving state and buffering).
**Linux**
- Added directory `/opt/observiq-otel-collector/storage`
- Added environment `OIQ_OTEL_COLLECTOR_STORAGE` pointing to the directory, allowing configs to read `$OIQ_OTEL_COLLECTOR_STORAGE` instead of hard coding the value.
**Windows**
- Added storage directory to install directory. The `.include` file is required for WIX to copy the directory, afaik. 
Windows test output
```
File C:/Program Files/observIQ OpenTelemetry Collector/plugins
[PASS]  should exist
[PASS]  should be directory
File C:/Program Files/observIQ OpenTelemetry Collector/storage
[PASS]  should exist
[PASS]  should be directory
File C:/Program Files/observIQ OpenTelemetry …
```
> Add storage directory to release packages

- .github/workflows/release.yml
Release CI is failing due to timeouts, disabling arm64 builds will resolve this issue. ARM64 will be re-enabled after a container image build process refactor.
> Disable arm64 container image builds

- config/google_cloud_exporter/mysql/config.yaml
- config/google_cloud_exporter/redis/config.yaml
We will be using generic_node for all Google examples in the near future. Mysql and Redis will be part of a blog being written right now, so I have updated them earlier than expected.
To use [Google's generic_node](https://cloud.google.com/monitoring/api/resources#tag_generic_node), we need to use hostname as the node_id and set namespace / location. The `resourceattributetransposer` is no longer required as host.name is being preserved as `node_id`.
> Use generic node for Mysql and Redis Google examples

- docs/receivers.md
- factories/receivers.go
- go.mod
- go.sum
The `prometheusexec` receiver has been deprecated in OTel and we don't have customer usage of it in our collector so we're removing it.
> feat(removal): Removed deprecated prometheusexec receiver

- config/google_cloud_exporter/tomcat/config.yaml
This PR updates the tomcat configuration to use Google's `generic_node` monitored resource type. I am leveraging the `properties.otel.resource.attributes` parameter to define a unique field that can be used for `node_id`. This allows a single collector to scrape multiple Tomcat systems. The agent's hostname is preserved on the metric labels as `agent`.
You will notice that I did not remove the `batch`, `normalizesums` or anything else that [this pr](https://github.com/observIQ/observiq-otel-collector/pull/355) abstracts. I would like to be consistent, and update the configs together when we cut over to the "new way" of doing things with Google.
> Use generic node for Tomcat Google Cloud example

- config/google_cloud_exporter/hostmetrics/config.yaml
- exporter/googlecloudexporter/config.go
- `workloads.googleapis.com` needs to be `workload.googleapis.com`. 
- Update hostmetrics config to leverage wrapped Google exporter
> fix: Wrapped google exporter metric prefix

- config/google_cloud_exporter/elasticsearch/config.yaml
- config/google_cloud_exporter/rabbitmq/config.yaml
- Updated Rabbitmq to use Workload prefix and generic_node (a requirement of workload)
- Updated Elasticsearch to use Workload prefix and generic_node
> Use workload prefix for Rabbitmq and Elasticsearch Google examples

- plugins/mongodb_logs.yaml
Added the Mongodb log plugin MVP as a port from `stanza-plugins`. 
**Note1:** The stanza-plugin included the ability to read from k8s. There is no way I could find in otel to get logs from k8s and add the operator parsing. The [k8seventsreceiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver) does not support operators. This would be doable if the logs transforms processor is approved open-telemetry/opentelemetry-collector-contrib#9133.
**Note2:** The remove operator is currently not present in the filelog receiver. There is a PR to add it so I commented out that operator until the PR is approved. Tracked in open-telemetry/opentelemetry-collector-contrib#9524
> feat(plugin): Added Mongodb log plugin

- .github/CODEOWNERS
Changed codeowners to sub team [collector-team](https://github.com/orgs/observIQ/teams/collector-team)
> Changed codeowners to collector-team

- receiver/pluginreceiver/provider.go
- receiver/pluginreceiver/provider_test.go
* Set metrics level to none for plugin sub-service
Without this, plugins will set up the internal metrics server without respecting the config that was passed to the collector. This means that it would always attempt to start up the metrics server on port 8888, which can cause conflicts (the collector will not start if something is already bound to 8888).
This PR disables the plugin receiver from spinning up its own internal metrics server, so that only the top-level collector will spin up the internal metrics server.
> fix(pluginreceiver): Turn metrics telemetry off for plugin sub-service

- plugins/nginx_logs.yaml
* Add a logging plugin for NGINX access + error logs. (ported from stanza-plugins)
Tested against a running NGINX instance to make sure access + error logs were parsing correctly.
As noted for Mongodb, k8s support has been removed.
> feat(nginx): Add nginx logging plugin

- receiver/pluginreceiver/plugin.go
- receiver/pluginreceiver/plugin_test.go
While using the redis plugin, default values were working fine but when setting `file_path` @algchoo gets the following error.
```
2022/05/02 13:30:51 collector server run finished with error: cannot build receivers: cannot create receiver plugin: invalid plugin parameter: type failure: parameter file_path must be a []string
```
Config example
```
plugin:
path: ./plugins/redis_logs.yaml
parameters:
file_path: ["/var/log/redis/redis-server.log"]
```
After talking with @jmwilliams89 we assumed that the validation code was incorrectly considering []interface{} to be invalid. 
When using this change, the collector starts fine and reads the file we specified.
> fix: Plugin validation fails on valid []string parameter

- plugins/nginx_logs.yaml
- receiver/pluginreceiver/supplied_plugins_test.go
* Change error_log_paths to be of type string
* Add a test to verify that default arguments match the types of their parameters
* Fix the default plugin render test to actually test all plugins, instead of the last one in the directory listing
> fix(nginx): Fix incorrect type for error_log_paths

- plugins/elasticsearch_logs.yaml
- plugins/nginx_logs.yaml
The `preserve_to` field in log operators is no longer supported in otel. The new default behavior is the `parse_from` field automatically preserves the original field. I removed the few `preserve_to` statements that were just keeping the original field.
> fix(deprecation): Removed unsupported preserve_to in plugins

- .goreleaser.yml
* Move the "config|noreplace" type from LICENSE to config.yaml
This is needed to preserve config files between upgrades.
> fix: Config in linux package should be marked "config|noreplace"

- exporter/googlecloudexporter/README.md
- exporter/googlecloudexporter/config.go
- exporter/googlecloudexporter/config_test.go
- exporter/googlecloudexporter/factory.go
- exporter/googlecloudexporter/go.mod
- Adds a credentials field to the google exporter.
- Adds a credentials_file field to the google exporter.
- Updates the client options on the GCP config to use specified credentials if set.
- Updates Google Cloud exporter documentation.
> feat: Improve GCP credentials

- scripts/install/install_unix.sh
* Add flags for endpoint, labels, and secret-key
* endpoint must be specified if labels or secret-key is specified
* These parameters may also be passed in using environment variables
* If endpoint is specified, generate a "manager.yaml" file with a randomly generated UUID for agent_id, as well as labels and secret-key, if specified.
* Remove the manager.yaml on uninstall
This PR allows the install script to create a manager.yaml with supplied information, which will be used to configure the collector for connecting with an OpAMP compatible server.
Tested on debian-10 & centos8 (almalinux)
Note: The internal ticket for this specified `manager.yml`, however I opted to go with `manager.yaml` to keep consistency with the extension we've been using for yaml files in this repository.
> feat: Update Linux install script to allow generation of manager.yaml

- scripts/install/install_macos.sh
* Add flags for endpoint, labels, and secret-key
* endpoint must be specified if labels or secret-key is specified
* These parameters may also be passed in using environment variables
* If endpoint is specified, generate a "manager.yaml" file with a randomly generated UUID for agent_id, as well as labels and secret-key, if specified.
* Remove the manager.yaml on uninstall
This PR allows the install script to create a manager.yaml with supplied information, which will be used to configure the collector for connecting with an OpAMP compatible server.
Tested on macOS Big Sur v11.4
Note: The internal ticket for this specified `manager.yml`, however I opted to go with `manager.yaml` to keep consistency with the extension we've been using for yaml files in this repository.
> feat: Update macOS install script to allow generation of manager.yaml

- scripts/install/install_unix.sh
Our linux installation script currently does not restart the service after an upgrade.
Because of this, the previous version of the collector will still be running until a restart is triggered outside of the install script.
We should automatically restart the service if it's already enabled, so that the new collector binary runs automatically.
Tested on AlmaLinux 8.5 + debian 10
> feat(installscript): Restart the service so changes take effect on upgrade

- plugins/couchdb_logs.yaml
* Adds a plugin that receives & parses CouchDB logs
Sample Access record:
```
ObservedTimestamp: 2022-05-13 17:04:29.920619491 +0000 UTC
Timestamp: 2022-05-13 14:57:30.951381 +0000 UTC
Severity: Info
Body: [notice] 2022-05-13T14:57:30.951381Z couchdb@127.0.0.1 <0.1363.0> 4022011fc3 localhost:5984 127.0.0.1 admin PUT /_replicator 412 ok 1
Attributes:
-> log_type: STRING(couchdb)
-> log.file.name: STRING(couchdb.log)
-> node: STRING(couchdb)
-> http_request_requestMethod: STRING(PUT)
-> remote_user: STRING(admin)
-> pid: STRING(0.1363.0)
-> http_request_remoteIp: STRING(127.0.0.1)
-> host: STRING(127.0.0.1)
-> http_request_responseSize: STRING(1)
-> level: STRING(notice)
-> status_message: STRING(ok)
-> path: STRING(/_replicator)
-> message: STRING(admin PUT /_replicator 412 ok 1)
-> …
```
> feat: Add a plugin for CouchDB logs

- scripts/install/install_macos.sh
* Adds an explanation before password prompt about why the password is needed.
* use the `-f` flag when removing the jmx jar so that uninstall doesn't panic if the jar doesn't exist.
It ends up looking like this:
```
===================================================
| Installing observIQ OpenTelemetry Collector
===================================================
Tapping formula...
Succeeded!
Installing collector...
In order to install the jmx metrics jar to the correct location, root permissions are needed.
Please enter your password if prompted to complete installation.
Password:
Succeeded!
Enabling service...
Succeeded!
observIQ OpenTelemetry Collector installation complete!
```
> fix(installscript): Add wording about why password is needed in macOS install script

- .goreleaser.yml
Updated the image tags to include their arch, added image manifest using the original image tag. This should result in multi arch images.
I tested using the `bmedora` account, you can see the pushed image (with multi arch) [here](https://hub.docker.com/layers/observiq-otel-collector/bmedora/observiq-otel-collector/latest/images/sha256-280a9cb91b018932084f94800d910e0adbb2092061073e9bd4799e2e02e9d2bb?context=explore).
> fix: Multi arch (amd64 / arm64) container image

- plugins/pgbouncer_logs.yaml
Ported PGBouncer plugin
configuration used:
```
receivers:
plugin:
path: ./plugins/pgbouncer_logs.yaml
parameters:
file_path:
- /Users/austingeorgiades/projects/observiq-otel-collector/in
exporters:
logging:
logLevel: debug
service:
pipelines:
logs:
receivers:
- plugin
exporters:
- logging
```
input/test data:
```
2021-05-17 16:16:40.613 1354 LOG Stats: 0 xacts/s, 0 queries/s, in 0 B/s, out 0 B/s, xact 0 us, query 0 us wait time 0 us
2021-05-18 13:12:05.011 UTC [1] LOG stats: 927 xacts/s, 935 queries/s, in 420598 B/s, out 687149 B/s, xact 893 us, query 816 us, wait 1 us
2021-05-18 13:12:05.191 UTC [1] LOG C-0x55a12ff32ad0: collectors/bindplane@10.1.0.70:56614 closing because: client close request (age=82s)
2021-05-18 12:30:05.591 12788 WARNING C-0x564043c80e20: …
```
> feat: pgbouncer plugin

- processor/resourceattributetransposerprocessor/README.md
- processor/resourceattributetransposerprocessor/factory.go
- processor/resourceattributetransposerprocessor/factory_test.go
- processor/resourceattributetransposerprocessor/processor_logs.go
- processor/resourceattributetransposerprocessor/processor_logs_test.go
- processor/resourceattributetransposerprocessor/processor_metrics.go
- processor/resourceattributetransposerprocessor/processor_metrics_test.go
* Adds logs support to the resource attributes transposer
Also did a little refactoring to support this. 
We should consider deprecating this processor once https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/transformprocessor is considered ready for use in distributions.
Sample config:
```
receivers:
filelog:
include:
- /Users/brandon/example.log
resource:
log_type: app
processors:
resourceattributetransposer:
operations:
- from: log_type
to: log_type_2
exporters:
logging:
service:
pipelines:
logs:
receivers: [filelog]
processors: [resourceattributetransposer]
telemetry:
metrics:
level: none
```
Sample output:
```
2022-05-16T13:17:22.246-0400    DEBUG   loggingexporter/logging_exporter.go:81 …
```
> feat: Add logging support to resource attribute transposer

- Dockerfile
[Stanza Base Image](https://github.com/observIQ/stanza-base-image/releases/tag/v1.2.2) was updated today to fix an issue where the released image did not include the required packages (systemd, ca-certificates, tzdata). This PR updates the observiq-otel-collector's Dockerfile to use the latest base image.
The purpose of the base image is to ensure the required packages are pinned to recent / latest versions. In the past, we have observed the repo's giving us old versions of a package. It also cuts down on this repo's Dockerfile complexity.
> Update container base image to v1.2.2

- collector/settings.go
- collector/settings_test.go
- collector/test/valid_with_env_var.yaml
Fixes the environment variable replacement in configs not working that was broken when updating the otel collector to v0.50.0.
> fix: Fixes environment variable replacement in configs not working

- .goreleaser.yml
- Dockerfile
In order to leverage plugins within a container, we need to bundle them. I decided to place them at `/etc/otel/plugins`, as the config already lives in `/etc/otel/config.yaml`. 
After building the image:
```bash
docker run -it -u root --entrypoint ls observiq/observiq-otel-collector-amd64:latest /etc/otel/plugins
apache_common_logs.yaml  mongodb_logs.yaml     rabbitmq_logs.yaml
couchdb_logs.yaml	 mysql_logs.yaml       redis_logs.yaml
elasticsearch_logs.yaml  nginx_logs.yaml       syslog_logs.yaml
haproxy_logs.yaml	 pgbouncer_logs.yaml
ingress_nginx_logs.yaml  postgresql_logs.yaml
```
```
docker run -it -u root --entrypoint head observiq/observiq-otel-collector-amd64:latest /etc/otel/plugins/haproxy_logs.yaml
version: 0.0.1
title: HAProxy
description: Log parser for HAProxy
parameters:
- …
```
> feat: Include plugins with container image

- scripts/install/install_unix.sh
Changed the `url` flag on the `install_unix.sh` script to not apply version suffix if specified. This matches what the help message said before.
Tested with the following case:
- `url` set
- `url` not set `version` not set
- `url` not set `version` set
All cases produced the expected URL for download.
> feat:(install): Linux Install Script url flag works as intended

- windows/templates/product.wxs
* Run the custom actions with elevated privileges to create/delete manager.yaml
If the user who ran the installer was not an admin, but could elevate to admin privileges, manager.yaml would fail to create. This change will let the CustomAction be run as .\LocalSystem, which has the privileges needed to properly create the file.
See the Impersonate option here:
https://wixtoolset.org/documentation/manual/v3/xsd/wix/customaction.html
> fix: Fix manager.yaml not being generated if installing user was not admin

- .goreleaser.yml
Per the goreleaser [docs](https://goreleaser.com/customization/release/)
```yaml
prerelease: auto
```
I added the `prerelease` key set to `"true"`. This is to better facilitate the release process and post release testing before we fully publish a release.
> feat(release): Added prerelease tag to goreleaser config

- .github/workflows/release.yml
In go releaser 1.8.0 a version number was added to the amd64 build directories. This was not taken into account in our msi build.
> fix(release): Updated path for msi release to use new gorleaser path

- docs/exporters.md
- docs/extensions.md
- docs/processors.md
- docs/receivers.md
Resolves #419 
Updates documentation with two column tables for extensions, receivers, exporters, and processors. The first column has a human readable name and the second has the original otel name along with a link to the github README for that component.
> feat: Updates docs with human readable names for components

- plugins/udp_logs.yaml
```
package main
import (
"log"
"net"
)
func main() {
con, err := net.Dial("udp", "127.0.0.1:4444")
if err != nil {
log.Fatalf("Failed to dial udp: %v", err)
}
defer con.Close()
con.Write([]byte("Logging over UDP\n"))
}
```
```
2022-05-26T12:54:30.584-0400    INFO    loggingexporter/logging_exporter.go:71  LogsExporter  {"#logs": 1}
2022-05-26T12:54:30.584-0400    DEBUG   loggingexporter/logging_exporter.go:81  ResourceLog #0
ScopeLogs #0
ScopeLogs SchemaURL: 
LogRecord #0
ObservedTimestamp: 2022-05-26 16:54:30.55076 +0000 UTC
Severity: 
Body: Logging over UDP
Attributes:
-> net.peer.ip: STRING(127.0.0.1)
-> net.peer.port: STRING(63813)
-> net.peer.name: STRING(localhost)
-> log_type: STRING(udp)
-> …
```
> feat: Add UDP plugin

- go.mod
- go.sum
- opamp/observiq/observiq_client.go
- opamp/observiq/observiq_client_test.go
Most of the changes are handled directly in the library implementation. There was also a change to remove the AuthorizationHeader and replace it with a general Header field to allow additional headers to be passed. This adds the User-Agent header setting it to `observiq-otel-collector/version`
> deps: Update opamp library with new protobuf message format

- docs/exporters.md
- docs/extensions.md
- docs/installation-mac.md
- docs/processors.md
- docs/receivers.md
- exporter/googlecloudexporter/README.md
- factories/receivers.go
- go.mod
- go.sum
Now that OTEL Collector dependencies have been updated to 0.52.0, we can bring in the new F5 BIG-IP Receiver into this collector.
Also edited docs with 0.52.0 dependencies
> feat: Adds BIG-IP Receiver

- .goreleaser.yml
- docs/installation-linux.md
- scripts/package/postinstall.sh
In order to support reading log files out of the box, we need the collector to run as the root user on Linux. The `observiq-otel-collector` does not have permission to read arbitrary log files. For example: Elasticsearch, Mongodb, Mysql, Nginx, Postgres, Rabbitmq, and redis are all owned by different users.
Changes
- Updated systemd unit file to use `root` user
- Updated post install script to configure the log file permissions
- The logger will not modify permissions. If the file does not exist, the log file will be owned by root. We want to pre configure the permissions in order to allow users to switch to the `observiq-otel-collector` user.
- Updated linux doc to reflect these changes, and documented the process to switching to the unprivileged user.
I have tested the following
- Fresh …
> Run as root by default on Linux

- exporter/googlecloudexporter/go.mod
- Fixed the module path for the google exporter. This will allow the collector to be imported by other libraries without creating a module path issue.
> fix: Fixed the module path for the google exporter

- internal/service/service_windows.go
On startup set the working directory to the directory of the executable. This fixes the Windows Service issue where the working directory is not where the executable lives.
```  
plugin:
path: ./plugins/csv_logs.yaml
parameters:
log_paths:
- ./input.csv
header: "1,2,3"
```
The above config produces errors related to not being able to find plugins/csv_logs.yaml after a windows install.  It works fine now after the proposed changes.
> fix: Changes working directory to directory of executable on startup (for Windows)

- .goreleaser.yml
- docs/installation-mac.md
- scripts/install/install_macos.sh
goreleaser now creates a brew formula which puts the config file in the /etc directory of brew. It is given a observiq prefix (as this is a shared directory) and symlinked back to the standard brew install directory.
Also updated the macos install script to remove these configs on uninstall.
> fix: Modify goreleaser to have a safe config.yaml that will not be overwritten

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
* When force exiting, return exit code 0 when successful
For some actions, we were using force_exit to exit the script after the action was done (e.g. uninstall). This returns exit code 1, indicating a failure, even if the script ran successfully. Noticed this while trying to automate testing for uninstallation.
Tested on mac and AlmaLinux 8.
> fix(installscripts): Return exit code 0 on successful actions

- scripts/install/install_macos.sh
Updates and reinstalls preserve manager.yaml if it exists. It is ultimately installed to the homebrew/etc directory with a special observiq_ prefix (/etc is shared) and then symlinked as manger.yaml. On install, we always check if the yaml file exists in the /etc directory and then create the symlink. This ensures it exists even on a reinstall (where the directory is wiped). 
Uninstall will clear out this file even from /etc.
> fix: macOS reinstalls/updates now preserve manager.yaml

- .github/workflows/homebrew-update-current.yml
Adds a GitHub action that will trigger on an edit to a release. This will occur when we change a pre-release to a release. The action sends a `repository_dispatch` event to the https://github.com/observIQ/homebrew-observiq-otel-collector repo to trigger the action to update the homebrew formulas.
Triggers action detailed in observIQ/homebrew-observiq-otel-collector#1.
> Added GitHub action to trigger homebrew action

- config/new_relic_otlp/elasticsearch/README.md
- config/new_relic_otlp/elasticsearch/config.yaml
- config/new_relic_otlp/redis/README.md
- config/new_relic_otlp/redis/config.yaml
- Added Elasticsearch metrics for New Relic
- Added Redis metrics for New Relic
- Fixed Cassandra for New Relic (properties.otel.resource.attributes was replaced by resource_attributes)
- Updated the attribute name to `cassandra.endpoint` to follow the pattern used in other jmx based configs
Redis includes the resource detection processor as it does not include identifiable attributes out of the box. Elasticsearch has node name and cluster name attributes that can be used for identification.
> feat(example config): New Relic Elasticsearch and Redis

- plugins/couchbase_metrics.yaml
* Add a metric plugin for Couchbase
Tested against a dockerized Couchbase instance with the following config.
<details> 
<summary>Sample config</summary>
```yaml
receivers:
plugin:
path: './plugins/couchbase_metrics.yaml'
parameters:
username: 'otelu'
password: 'otelpassword'
scrape_interval: '5s'
exporters:
logging:
service:
pipelines:
metrics:
telemetry:
metrics:
level: none
```
</details> 
<details> 
<summary>Sample metric datapoint</summary>
```
2022-06-13T14:19:46.541-0400    DEBUG   loggingexporter/logging_exporter.go:67  ResourceMetrics #0
Resource labels:
-> service.name: STRING(couchbase)
-> service.instance.id: STRING(localhost:8091)
-> net.host.port: STRING(8091)
-> http.scheme: STRING(http) …
```
> feat: Add Couchbase metrics plugin

- plugins/hadoop_logs.yaml
Ported Hadoop plugin from Stanza
- Merged all three file inputs into a single file log receiver
- Multiline pattern and regex parser are the same, no need to define them three times
- Use router to set log type from the file name. The file name seems to be stable enough for this.
Works well against a live system.
> feat: Hadoop log plugin

- scripts/install/install_macos.sh
Removes the double forward slash for the manager.yaml symlink in homebrew
> fix: Removes double forward slash in manager.yaml symlink

- plugins/zookeeper_logs.yaml
- Added a logging plugin for apache zookeeper
- Tested using the file located here: [https://github.com/observIQ/log-library/blob/master/library/hbase/zookeeper.log](url)
- Example Log:
```
LogRecord #32
ObservedTimestamp: 2022-06-16 19:53:47.538867 +0000 UTC
Severity: 
Body: 2020-12-09 20:38:42,979 INFO  [main] server.ZooKeeperServer: Server environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
Attributes:
-> log.file.name: STRING(zookeeper.txt)
Trace ID: 
Span ID: 
Flags: 0
```
> feat: Add Zookeeper Plugin

- plugins/active_directory_logs.yaml
* Port the stanza active directory log plugin to an OTEL plugin
Sample plugin on a system with active directory installed:
```
ObservedTimestamp: 2022-06-20 19:32:24.6656296 +0000 UTC
Timestamp: 2022-06-20 18:42:19.7294182 +0000 UTC
Severity: Info
Body: {
-> channel: STRING(Directory Service)
-> computer: STRING(brandon-win-build.test.example.com)
-> event_data: SLICE(["NTDS","696,D,0","NTDSA: ","C:\\Windows\\NTDS\\ntds.dit","0","6/20/2022","0","1","1","43"])
-> event_id: MAP({"id":701,"qualifiers":0})
-> keywords: SLICE(["Classic"])
-> level: STRING(Information)
-> message: STRING(NTDS (696,D,0) NTDSA: Online defragmentation has completed a full pass on database 'C:\Windows\NTDS\ntds.dit', freeing 0 pages. This pass started on 6/20/2022 and ran for a total of 0 seconds, requiring 1 …
```
> feat: Add Active Directory log plugin

- plugins/w3c_logs.yaml
Add a logging plugin for w3c logs .
Tested running collector locally and testing logs from [iis](https://github.com/observIQ/log-library/blob/master/library/msiis/iis.log)
In the original stanza plugin, a timestamp was not parsed out and in order to maintain the original functionality while porting we did likewise, which is why it appears the timestamp does not parse out
Example Log:
> feat(w3c): Add w3c logging plugin

- plugins/aerospike_logs.yaml
- Ported Aerospike plugin from stanza
- Replaced file input with journald input
- Preserve hostname (as resource host.name), cursor, pid, priority, facility, and service name from journald entry
- Replace body with Aerospike's log body
- Parse Aerospike's log body and promote timestamp and severity fields (from stanza plugin)
- Filter out 'config' logs (from stanza plugin)
- Add log type (from stanza plugin)
Previously, the Stanza plugin expected to read from a log file. Journald is the default log driver for Aerospike, so we decided to replace the log input in favor of Journald.
Example Input:
```json
{
"__CURSOR": "s=e2a0ce35f993490e9b57bfc00a93204f;i=6275;b=4c9e0328beb14759afeff1fdd487bde9;m=a815e8a1;t=5e20ac4ece40b;x=d4d03fcd934119c2",
"__REALTIME_TIMESTAMP": "1655910764962827", …
```
> feat: Aerospike log plugin

- plugins/file_logs.yaml
The following multinline pattern fails with a marshal error if not wrapped in single quotes:
Error
>```{"level":"fatal","ts":"2022-06-23T09:56:57.578-0400","caller":"collector/main.go:81","msg":"RunService returned error","error":"failed to start service: failed while starting collector: failed to get config: cannot resolve the configuration: yaml: line 3: did not find expected key","stacktrace":"main.main\n\t/home/runner/work/observiq-otel-collector/observiq-otel-collector/cmd/collector/main.go:81\nruntime.main\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/proc.go:250"}```
Pattern
```
[0-9]{4}-[0-9]{2}-[0-9]{2}\s+[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,3})?\s+(TRACE|DEBUG|INFO|NOTICE|WARN|WARNING|ERROR|SEVERE|FATAL)
```
This fix works with and without multiline pattern being specified.
> fix(file plugin): Wrap multiline pattern in single quotes

- .goreleaser.yml
- Makefile
- README.md
- docs/installation-mac.md
- scripts/install/install_macos.sh
- service/com.observiq.collector.plist
* Add a plist file to the archive for the macOS service.
* Like with the windows one, there doesn't seem to be a way to restrict this to specific tarballs, so it's packaged with all archives.
* Rework the macOS script to install from tarball instead of brew
* Remove brew references from docs
* Remove brew from goreleaser
Since the new service file is required in the tarball, I've been testing using the `-l` flag to specify a local tarball built with `make release-test`.
- Configs (config.yaml, logging.yaml, manager.yaml) are not overwritten on re-install.
- On uninstall, config.yaml is preserved as config.bak.yaml, which is similar to behavior when uninstalling through RPM.
- Installing on top of an existing install will overwrite files of the existing install, similar to the linux …
> feat: Rework macOS script to install from tarball

- plugins/apache_http_logs.yaml
* Ported Apache Http Server plugin from stanza
Example Config (ObservIQ log format):
```yaml
receivers:
plugin:
path: './plugins/apache_http_logs.yaml'
parameters:
log_format: observiq
access_log_path:
- "./apache_access_logs.log"
error_log_path: 
- "./apache_error_logs.json"
enable_error_log: true
enable_access_log: false
exporters:
logging:
service:
pipelines:
logs:
telemetry:
metrics:
level: none
```
Example Output:
Example Config (Default):
```yaml
receivers:
plugin:
path: './plugins/apache_http_logs.yaml'
parameters:
log_format: default
access_log_path:
- "./apache_access_logs.log"
error_log_path: 
- "./apache_error_logs.log"
enable_error_log: true
enable_access_log: false
exporters: …
```
> feat: Apache http plugin

- opamp/observiq/observiq_client.go
- opamp/observiq/observiq_client_test.go
- opamp/version.go
- opamp/version_test.go
Added the following headers to the observIQ client:
- `OpAMP-Version`: internally determined version of OpAMP
- `AgentID`: UUID of Agent
- `Agent-Hostname`: Hostname of agent
- `Agent-Version`: Version of agent
These headers are meant as a fail safe for OpAMP communication with server. Since OpAMP is not stable yet it's possible proto definitions will change and that a user may have a sever and agent that are incompatible. These headers will be a way to allow the server to recognize if the version of OpAMP the client is using has compatible protos. If not the server can take action accordingly. We also include some identifying information in the headers so the server can have some identity on the server even if there are OpAMP compatibility issues.
> feat: Added additional headers to OpAMP client

- cmd/collector/main.go
- cmd/collector/main_test.go
Implement dynamic manager.yaml loading/creation based upon pre-existing manager.yaml file or preconfigured environment variables.
Logic for loading/creating a yaml file:
1. Check if manager.yaml exists in flag specified location
2. If not check if endpoint env exists.
- If so check all other envs
- If agent id is not specified via env then create a UUID
- Create opamp.Config with env values
- Marshal created config to yaml and write out to disk at `./manager.yaml`
3. If file does not exist and no envs are set go into standalone mode
> feat: Manager Env Config

- .github/workflows/release.yml
Sometimes releasing fails on goreleaser step when it takes longer than 30m. Increased timeout to 60m.
> Increased timeout of goreleaser to 60 minutes

- docs/installation-mac.md
- scripts/install/install_macos.sh
Updated the service start and stop commands printed in the macOS install script. `launchctl stop` will stop the collector but the plist file will restart it because of the `<key>KeepAlive</key>` key we have set. Using `unload` and `load` will start and stop the service and give desired behavior.
> fix: Updated macOS script commands for service start and stop

- opamp/observiq/observiq_client.go
- opamp/observiq/observiq_client_test.go
> feat: Add mutex for updatingClient flag in client

- factories/exporters.go
- go.mod
- go.sum
When we switched over to the otel version of the `googlemanagedprometheusexporter` looks like we missed the factor import. I double checked this will not be a breaking change as it wraps the exporter we had imported before.
> fix: Fixed import for googlemanagedprometheusexporter

- plugins/windows_dhcp.yaml
This is currently blocked by https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/10128. Because all log files have lines 2 & 3 as empty lines, this bug affects every file. Even `start_at` end will have an issue once the log rolls over to the next day's file.
Adds the Windows DHCP plugin.
```
receivers:
plugin:
path: ./plugins/windows_dhcp.yaml
parameters:
exporters:
logging:
service:
pipelines:
logs:
```
```
ScopeLogs #0
ScopeLogs SchemaURL: 
LogRecord #0
ObservedTimestamp: 2022-06-21 17:14:03.939705 +0000 UTC
Timestamp: 2022-06-18 03:38:47 +0000 UTC
Severity: 
Body: 25,06/17/22,23:38:47,0 leases expired and 0 leases deleted,,,,,0,6,,,,,,,,,0 …
```
> feat: Adds the Windows DHCP plugin

- opamp/observiq/observiq_client.go
- opamp/observiq/updater_manager.go
- opamp/observiq/updater_manager_others.go
- opamp/observiq/updater_manager_others_test.go
- opamp/observiq/updater_manager_windows.go
- opamp/observiq/updater_manager_windows_test.go
* Copy the updater to CWD, and execute it there.
* Tweak tests for updaterManager to run in parallel (this knocks like 4-5 seconds, from 11-12 seconds to ~6-7 seconds)
> feat: Copy updater executable to CWD of collector before executing

- updater/internal/action/file_action.go
- updater/internal/action/file_action_test.go
- updater/internal/file/file.go
- updater/internal/file/file_test.go
- updater/internal/install/install.go
- updater/internal/install/install_test.go
- updater/internal/path/path.go
- updater/internal/path/path_test.go
- updater/internal/rollback/rollback.go
- updater/internal/rollback/rollback_test.go
- updater/internal/service/service_darwin.go
- updater/internal/service/service_linux.go
Ensures JMX jar is both installed and rolled back properly
Also making sure that we use the backed up file permissions when
rolling back a file that no longer exists in the install directory
Updated some tests that were extremely hard to debug.
> fix: Makes sure JMX jar is installed and rolled back properly

- plugins/cisco_asa_logs.yaml
Cisco ASA was failing to start for me. This is because `receiver` should be `receivers` in the template.
> fix: Cisco ASA plugin typo

- opamp/observiq/updater_manager.go
- opamp/observiq/updater_manager_others.go
- opamp/observiq/updater_manager_others_test.go
- opamp/observiq/updater_manager_windows.go
- opamp/observiq/updater_manager_windows_test.go
- service/com.observiq.collector.plist
- service/observiq-otel-collector.service
- updater/cmd/updater/main.go
- updater/internal/install/install.go
- updater/internal/install/install_test.go
* Change service timeouts to be 20 seconds
* This is the default for macOS, but I added it in just to be sure
* Windows default is 20s and isn't easy to set, so I left it where it was
* Change collector wait timeout for updater to 30 seconds
* Change updater to stop the collector before performing the backup, in order to reduce time to service shutdown
> feat: Harden collector shutdown while updating

- .github/workflows/multi_build.yml
- Makefile
- license.yaml
Updated Makefile & GitHub Action workflow so Updater binary has license scans
> Updated Makefile & GitHub Action workflow so Updater binary has license scans

- opamp/observiq/observiq_downloadable_file_manager.go
Fixes tmp dir for update to have 0700 permissions
> fix: Fixes tmp dir for update to have 0700 permissions

- updater/internal/service/service_windows.go
- updater/internal/service/service_windows_test.go
* Instead of uninstalling and re-installing, do the Update in-place for windows.
* This means we remove both the `install` and `uninstall` functions
Previously, we relied on a wait loop to wait for the service to actually uninstall after being marked for removal.
In this PR, we change how we update the service to not need an uninstall, so we don't need to wait for the service manager to remove the service. Instead, we just apply an update to the existing configuration.
> fix(updater): Do Update in place for windows service

- updater/internal/logging/logging_others.go
* Enable debug logs for updater logger
I noticed while testing that the logs were very sparse; We don't have the debug logs enabled right now, it must have got lost during the file logging PR.
Tested an update locally on my mac and the updater now emits debug logs.
> fix(updater): Enable debug logs

- updater/internal/action/file_action.go
- updater/internal/file/file.go
- updater/internal/file/file_test.go
- updater/internal/install/install.go
- updater/internal/rollback/rollback.go
- updater/internal/service/service_darwin.go
- updater/internal/service/service_linux.go
* Refactor CopyFile into 3 separate exported functions and 1 unexported function.
> feat: Refactor Updater's file package

- docs/processors.md
- docs/receivers.md
- go.mod
- go.sum
* Points back to the official [operations collector](https://github.com/GoogleCloudPlatform/opentelemetry-operations-collector) instead of using our fork, now that v0.57.2 otel dependencies have been merged in.
> deps: Update to point at official operations-collector again

- cmd/collector/main.go
- cmd/collector/main_test.go
For users that specify a `manager.yaml` and do not supply an agent ID, we should generate a valid UUIDv4 and rewrite the config before establishing any opamp connections. This should not impede standalone collector usage as the manager
> fix: Generate Agent ID if `manager.yaml` exists and does not supply the field

- plugins/iis_logs.yaml
* Add support for IIS format
* Add support for NCSA format
* Extend W3C support to allow for specifying a custom header.
* This allows us to support extra fields to be configured in IIS.
* Because of this change, the attribute names are different than they were previously.
Note on field naming; I tried to keep them consistent with the W3C logs, the main difference is that instead of hyphens I have underscores, since go's regexes do not allow hyphens in capture group names.
<details>
<summary>Sample W3C default log</summary>
```
LogRecord #1
ObservedTimestamp: 2022-08-09 20:21:04.443152 +0000 UTC
Timestamp: 2022-08-09 19:42:33 +0000 UTC
Severity: Warn
Body: 2022-08-09 19:42:33 127.0.0.1 GET /query param1=1&parma2=2 80 - 127.0.0.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:103.0)+Gecko/201 …
```
> feat(plugin): Add support for more log formats in IIS log plugin

- .github/workflows/gosec.yml
- .github/workflows/manual_msi_build.yml
- .github/workflows/release.yml
- Makefile
- receiver/pluginreceiver/rendered_config_test.go
- Updated revive to 1.2.3
- Updated cosign to 1.10.1
- Updated goreleaser to 1.10.3
- Updated gosec to 2.12.0
- Removed unused mdatagen tool
- Fixed fmt error in license comment
> deps: Updated Tool versions

- plugins/common_event_format_logs.yaml
* Make start_at description consistent with other plugin's start_at descriptions for common_event_format_logs plugin
> fix(plugin): Make start_at description consistent for common_event_format_logs plugin

- cmd/collector/main.go
- cmd/collector/main_test.go
- Added function for getting default collector config paths
- Will use an ENV variable if it is set
- If not will use default (./config.yaml)
> feat: Set ENV to path of collector config.yaml

- cmd/collector/main.go
- cmd/collector/main_test.go
- Added function for getting default collector logging path
- Will use an ENV variable if it is set
- If not will use default (./logging.yaml)
> feat: Set ENV to path of collector logging.yaml

- cmd/collector/main.go
- cmd/collector/main_test.go
- Added function for getting default collector manager path
- Will use an ENV variable if it is set
- If not will use default (./manager.yaml)
> feat: Set ENV to path of collector manager.yaml

- cmd/collector/main.go
- internal/logging/config.go
- internal/logging/config_test.go
- internal/logging/testdata/not-yaml.txt
* When the `--logging` flag is not specified, write out a default stdout config
* This fixes an issue where the logging.yaml would not exist on the system, so managed mode would fail when attempting to report the config to BindPlane OP
* Make specifying a logging.yaml fail if the specified yaml does not exist
Tested with a local build to ensure the logging.yaml was created locally on startup without specifying its location.
The default logging.yaml looks like this:
```yaml
output: stdout
level: info
```
> fix(logging): Write default logging yaml if not specified

- plugins/iis_logs.yaml
- plugins/w3c_logs.yaml
* Enable lazy_quotes in the csv parsers for W3C and iis
* Remove the unneeded quote manipulation in the W3C plugin (this existed as an alternative to the lazy quotes option)
This fix allows records to have quotes in the middle of its fields.
Resolves #655
<details>
<summary>Parsing an IIS record with a quote in it (before this change)</summary>
```
LogRecord #0
ObservedTimestamp: 2022-08-18 22:03:02.205955 +0000 UTC
Severity: 
Body: 2022-08-09 20:25:26 W3SVC1 <Server> 127.0.0.1 GET /query param1=1&parma2=2\\\">\\\"<script> 80 - 127.0.0.1 HTTP/1.1 Mozilla/5.0+(Windows+NT+10.0;+Win64;+x64;+rv:103.0)+Gecko/20100101+Firefox/103.0 - - localhost 404 0 2 5029 464 83
Attributes:
-> log.file.name: STRING(w3c_format_logs_quote.log)
-> log.file.path: …
```
> fix(plugin): Enable lazy quotes when parsing W3C

- processor/resourceattributetransposerprocessor/processor_logs_test.go
- processor/resourceattributetransposerprocessor/processor_metrics_test.go
- receiver/pluginreceiver/factory.go
- receiver/pluginreceiver/factory_test.go
- receiver/pluginreceiver/plugin.go
- receiver/pluginreceiver/plugin_test.go
- receiver/pluginreceiver/receiver_test.go
- receiver/pluginreceiver/rendered_config.go
- receiver/pluginreceiver/rendered_config_test.go
- receiver/pluginreceiver/supplied_plugins_test.go
Per new alias in go 1.18 updated all instances of `interface{}` to `any`
> Replaced interface{} with any

- scripts/install/install_macos.sh
M1 Macs apparently need (at least) the collector binary to be removed first before the new one is copied over on an upgrade type install. Without doing this, the new collector fails to run in the destination directory (even though there is nothing obviously wrong with it. It can still run in other directories if copied over). So to ensure this isn't a problem, I'm now removing any files/directories from the artifacts directory before copying them over.
> fix: Fixed mac install script to remove files before copying them over

- Dockerfile
The logging configuration is created on collector startup, if it does not exist. This presents an issue with the container image, as the collector process does not have permission to write to `./logging.yaml` in its working directory.
There are several ways to resolve this, but I think the best solution is to just bake a logging.yaml into /etc/otel and point to it with the new environment variable.
This changes resolves issues that I am observing with 1.7.0 in Kubernetes and OpenShift.
> fix: Container image default logging configuration

- plugins/iis_logs.yaml
- plugins/w3c_logs.yaml
* Use `ignore_quotes` instead of `lazy_quotes` for W3C based logs.
<details>
<summary>IIS Sample log</summary>
```
2022-06-04 00:15:42 "10.88.32.238 'GET "/ "><script>alert(document.domain)</script> "6080 "- "10.104.11.16 "- "- 403 "14 "0 "3
```
</details>
<details>
<summary>IIS Sample output</summary>
Note: The quotes are escaped here when being printed to console, but they (`\"`) are actually just a raw quote(`"`).
```
LogRecord #0
ObservedTimestamp: 2022-09-01 14:39:45.446754 +0000 UTC
Timestamp: 2022-06-04 00:15:42 +0000 UTC
Severity: 403
Body: 2022-06-04 00:15:42 \"10.88.32.238 'GET \"/ \"><script>alert(document.domain)</script> \"6080 \"- \"10.104.11.16 \"- \"- 403 \"14 \"0 \"3
Attributes:
-> time-taken: STRING(\"3)
-> sc-status: STRING(403)
-> cs-username: STRING(\"-)
-> s-ip: …
```
> fix(plugin): Use ignore_quotes option for w3c type logs

- docs/processors.md
- go.mod
- go.sum
Noticed gauges were causing the collector to panic in v0.59.0, for more information please refer to https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/13905
<details>
<summary>Config</summary>
```yaml
exporters:
logging:
processors:
filter/couchbase_couchbase_1:
metrics:
exclude:
match_type: strict
metric_names:
- scrape_samples_post_metric_relabeling
- scrape_series_added
- scrape_duration_seconds
- scrape_samples_scraped
- up
transform/couchbase_couchbase_3:
metrics:
queries:
- convert_gauge_to_sum("cumulative", true) where metric.name == "couchbase.bucket.error.oom.count"
- set(metric.description, "Number of out of memory errors.") where metric.name == "couchbase.bucket.error.oom.count"
- set(metric.unit, "{errors}") where metric.name == …
```
> fix(transformprocessor): Update `transformprocessor` to not panic on gauges

- go.mod
- updater/go.mod
Updated module references to internal submodules to `1.8.0` ahead of `1.8.0` release.
> Updated sub module references in go.mod to 1.8.0 before release

- plugins/tomcat_logs.yaml
Tomcat Logging plugin now parses to body rather than attributes. Also, adds a new parameter to preserve raw log line (off by default)
Access Logs with `access_retain_raw_logs` enabled:
```
LogRecord #1
ObservedTimestamp: 2022-09-08 14:29:10.418364 +0000 UTC
Timestamp: 2021-01-21 04:27:02 +0000 UTC
Severity: 404
Body: {
-> bytes_sent: STRING(755)
-> method: STRING(GET)
-> path: STRING(/help?bob=test&api=v2)
-> raw_log: STRING(10.33.104.26 - - [20/Jan/2021:23:27:02 -0500] \"GET /help?bob=test&api=v2 HTTP/1.1\" 404 755)
-> remote_host: STRING(10.33.104.26)
-> remote_user: STRING(-)
-> status: STRING(404)
-> timestamp: STRING(20/Jan/2021:23:27:02 -0500)
}
Attributes:
-> log.file.name: STRING(localhost_access_log.txt)
-> log_type: STRING(tomcat.access)
Trace ID: 
Span ID: 
Flags: 0
``` …
> feat(plugin): Refactored Tomcat log plugin to parse to body

- plugins/mongodb_logs.yaml
- plugins/tomcat_logs.yaml
- Removed unused parameter `retain_raw_logs` from tomcat plugin
- Added parsing to body to MongoDB logs plugin. 
MongoDB older style logs with `retain_raw_logs` enabled:
```
LogRecord #1
ObservedTimestamp: 2022-09-08 17:37:23.165769 +0000 UTC
Timestamp: 2019-02-06 14:22:27.347 +0000 UTC
Severity: I
Body: {
-> component: STRING(CONTROL)
-> context: STRING(initandlisten)
-> message: STRING(db version v3.6.2)
-> raw_log: STRING(2019-02-06T09:22:27.347-0500 I CONTROL  [initandlisten] db version v3.6.2)
-> severity: STRING(I)
-> timestamp: STRING(2019-02-06T09:22:27.347-0500)
}
Attributes:
-> log_type: STRING(mongodb)
-> log.file.name: STRING(old.log)
Trace ID: 
Span ID: 
Flags: 0
```
MongoDB newer json style logs with `retain_raw_logs` enabled:
```
LogRecord #1
ObservedTimestamp: 2022-09-08 …
```
> feat(plugin): Changed MongoDB Logs plugin to parse to body

- plugins/container_logs.yaml
Some docker based Kubernetes clusters will use Journald as the log driver (default is `json-file`).  This change adds a parameter, `log_source`, for selecting `Journald` instead of the default `file`. 
This is not a breaking change, as users will need to explicitly enable Journald. Existing users will use the default value `file`.
The Journald directory is defaulted to `/var/log/journal` as that was the Journald directory in use when testing this change against an OpenShift cluster using Journald for the log driver. 
The Journald source maps correctly to Open Telemetry semantic conventions, and shows up in Google mapped to the `k8s_container` monitored resource type.
> feat(plugin): Add Journald log driver support to container log plugin

- plugins/apache_combined_logs.yaml
- Updated the Apache Combined Plugin to parse attributes to body.
- Added `retain_raw_logs` parameter that, when enabled, adds the original log as an attribute to the `body`
Example with `retain_raw_logs` enabled:
```
LogRecord #0
ObservedTimestamp: 2022-09-12 12:27:17.915038 +0000 UTC
Timestamp: 2021-06-17 16:06:46 +0000 UTC
Severity: 304
Body: {
-> body_bytes_sent: STRING(64162)
-> http_referer: STRING(https://www.seniordisintermediate.biz/models)
-> http_user_agent: STRING(Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_3) AppleWebKit/5310 (KHTML, like Gecko) Chrome/39.0.854.0 Mobile Safari/5310)
-> method: STRING(POST)
-> path: STRING(/v1/login)
-> protocol: STRING(HTTP)
-> protocol_version: STRING(2.0)
-> raw_log: STRING(129.53.82.110 - - [17/Jun/2021:12:06:46 -0400] \"POST /v1/login …
```
> feat(plugin): Updated Apache Combined Plugin to parse attributes to body

- Makefile
The free version of GoReleaser does not handle multiple module tags in a single repo. Setting the `GORELEASER_CURRENT_TAG` fixes this. Added setting this in the `release-test` target to the last semantic versioned tag.
> fix(makefile): Fix the release-test make target to work with module tags

- plugins/container_logs.yaml
Some Kubernetes container application logs are json, and look like this in their unparsed form:
```json
{
"log":"{\"http.req.id\":\"d2ff7faf-db0b-4a5b-86c6-344eda2c5b8c\",\"http.req.method\":\"GET\",\"http.req.path\":\"/cart\",\"http.resp.bytes\":6650,\"http.resp.status\":200,\"http.resp.took_ms\":5,\"message\":\"request complete\",\"session\":\"bad3edc3-0974-41e0-9e5e-1427b11219d2\",\"severity\":\"debug\",\"timestamp\":\"2022-09-12T20:06:38.079934409Z\"}\n",
"stream":"stdout",
"time":"2022-09-12T20:06:38.080008097Z"
}
```
The output entry has `body` as a string, like this:
This change will parse body as json, and look like this:
Applications logs that are no json are skipped. This change applies to both input options (file and journald).
This change is enabled by default, but I would …
> feat(plugin): Support parsing container application logs as json

- plugins/aerospike_logs.yaml
* Parse to `body` instead of `attributes` for the `aerospike_logs` plugin.
In this instance, I didn't add the `retain_raw_log` parameter; The original journald line is not present in the output of the journald receiver, so there isn't an original line to retain.
Sample log input:
```
Sep 14 17:55:42 buster asd[2153]: Sep 14 2022 17:55:42 GMT: INFO (info): (ticker.c:499) {bar} memory-usage: total-bytes 0 index-bytes 0 set-index-bytes 0 sindex-bytes 0 data-bytes 0 used-pct 0.00
```
<details>
<summary>As JSON</summary>
```
{
"PRIORITY" : "6",
"_SYSTEMD_UNIT" : "aerospike.service",
"__REALTIME_TIMESTAMP" : "1663178142661261",
"__CURSOR" : "s=406a98fe116e4556b8a6598e7d6874ff;i=381d;b=9babb220c16742f68ba570481e7466a6;m=2fdd3c8b2;t=5e8a6d6643a8d;x=f216c603b20963d5",
"_PID" : "2153", …
```
> feat(plugin): Parse to body for aerospike_logs

- plugins/vcenter_logs.yaml
- Updated the vCenter Plugin to parse attributes to body.
- Added `retain_raw_logs` parameter that, when enabled, adds the original log as an attribute to the `body`
Example with `retain_raw_logs` enabled:
```
ResourceLog #0
ScopeLogs #0
ScopeLogs SchemaURL: 
LogRecord #0
ObservedTimestamp: 2022-09-16 14:30:43.095888 +0000 UTC
Timestamp: 2022-09-15 18:01:57.756788 +0000 UTC
Severity: info
Body: {
-> appname: STRING(content-library)
-> facility: INT(16)
-> hostname: STRING(vcsa)
-> message: STRING(2022-09-15T18:01:57.756Z | DEBUG    | opId-bdfbb34a-1a9c-4d01-9ea3-2a415f97c245 | cls-background-executor-2 | StsTrustChainImpl              | Refreshing cert chain from sso server...)
-> priority: INT(134)
-> raw_log: STRING(<134>1 …
```
> feat(plugin): Updated vCenter log plugin to parse attributes to body

- plugins/syslog_logs.yaml
- Updated the Syslog Plugin to parse attributes to body.
- Added `retain_raw_logs` parameter that, when enabled, adds the original log as an attribute to the `body`.
Example with `retain_raw_logs` enabled:
```
ResourceLog #0
ScopeLogs #0
ScopeLogs SchemaURL: 
LogRecord #0
ObservedTimestamp: 2022-09-16 15:51:34.000164 +0000 UTC
Timestamp: 2022-09-15 18:01:57.756788 +0000 UTC
Severity: info
Body: {
-> appname: STRING(content-library)
-> facility: INT(16)
-> hostname: STRING(vcsa)
-> message: STRING(2022-09-15T18:01:57.756Z | DEBUG    | opId-bdfbb34a-1a9c-4d01-9ea3-2a415f97c245 | cls-background-executor-2 | StsTrustChainImpl              | Refreshing cert chain from sso server...)
-> priority: INT(134)
-> raw_log: STRING(<134>1 …
```
> feat(plugin): Updated syslog log plugin to parse attributes to body

- plugins/file_logs.yaml
- Update the file_logs plugin to parse attributes to body.
- Added `retain_raw_logs` parameter that, when enabled, adds the original logs as an attribute to body.
```yaml
receivers:
plugin:
path: ./plugins/file_logs.yaml
parameters:
file_path: [./tmp/log-plugins/file-logs/mongodb.log]
parse_format: regex
regex_pattern: ^(?P<date>[^ ]*) (?P<something>[^ ]*) (?P<something2>[^ ]*)  (?P<rest>.*)$
include_file_name: false
retain_raw_logs: true
exporters:
logging:
service:
pipelines:
logs:
```
```log
2019-02-06T09:22:27.347-0500 I CONTROL  [initandlisten] db version v3.6.2
```
```log
LogRecord #0
ObservedTimestamp: 2022-09-16 18:17:21.449598 +0000 UTC
Severity: 
Body: {
-> date: …
```
> feat(plugin): Update file_logs plugin to parse attributes to body

- plugins/iis_logs.yaml
- Updated IIS Log Plugin to parse attributes to body
- Added `retain_raw_logs` parameter that, when enabled, adds the original log as an attribute to the `body`
Example of w3c format with `retain_raw_logs` enabled:
```
LogRecord #0
ObservedTimestamp: 2022-09-19 17:18:18.133832 +0000 UTC
Timestamp: 2020-11-03 16:13:15 +0000 UTC
Severity: 404
Body: {
-> c-ip: STRING(10.33.121.100)
-> cs(Referer): STRING(-)
-> cs(User-Agent): STRING(Go-http-client/1.1)
-> cs-method: STRING(GET)
-> cs-uri-query: STRING(-)
-> cs-uri-stem: STRING(/index.html)
-> cs-username: STRING(-)
-> raw_log: STRING(2020-11-03 16:13:15 10.33.104.51 GET /index.html - 80 - 10.33.121.100 Go-http-client/1.1 - 404 0 2 0)
-> s-ip: STRING(10.33.104.51)
-> s-port: STRING(80)
-> sc-status: STRING(404)
-> sc-substatus: STRING(0)
-> …
```
> feat(plugin): Updated IIS logging plugin to parse to body rather than attributes

- docs/receivers.md
- go.mod
- go.sum
* Update mongodbatlasreceiver to https://github.com/open-telemetry/opentelemetry-collector-contrib/commit/5da63139851a3cbcc329f8c517a2fe02c5b2b30b
This update includes the following fixes:
* Include some missing fields on audit logs to make them complete
* Retain the actual log record as the Body on both audit and process logs
* Fix potential infinite loop when parsing audit logs
Manually tested scraping mongodbatlas logs.
> deps: Update mongodbatlasreceiver to latest

- go.mod
* Bumps versions of submodules required in prep for v1.9.0 release
> deps: Bump internal module versions to 1.9.0

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
- windows/install/generate-manager-yaml.ps1
In preparation for moving Agent IDs to [ULID](https://github.com/ulid/spec), as required in the latest version of OPAMP, I've removed `agent_id` generation in the installation scripts. The collector currently will generate it's own `agent_id` if one isn't found int he `manager.yaml` so this does not break any installation flow.
> feat: Removed agent_id generation from installation scripts

- cmd/collector/main.go
- cmd/collector/main_test.go
- go.mod
- go.sum
If a collector does not have an existing `agent_id` and the ENV has not been set the collector will generate itself a a ULID as a new ID rather than a UUID.
I have tested this with the head of BPOP. Since both the collector and BPOP treat this as a string currently collectors can still talk to BPOP.
> feat: Changed new agent_id generation to use ULID

- cmd/collector/main.go
- cmd/collector/main_test.go
- go.mod
Added logic so that if an agent currently has an `agent_id` in the `manager.yaml` that is not a ULID the collector will generate a ULID and save that as its new `agent_id`.
This ID change does make BPOP think the collector is a new agent. All labels and config files are preserved so the agent will behave the same in BPOP it will just be a new entity. I plan to discuss with the BPOP team to see if they have any plan to auto clean up this legacy porting.
> feat: Added forward porting of legacy agent IDs to ULIDs

- internal/report/agent_client.go
- internal/report/agent_client_test.go
- opamp/observiq/observiq_client.go
- opamp/observiq/observiq_client_test.go
Fixed TLS issues when using Snapshot feature as TLS config wasn't being passed down to the Client.
> fix: Pass through TLS settings to Snapshot Client

- docs/processors.md
- docs/receivers.md
- go.mod
- go.sum
Updated to use latest version of GoogleCloudPlatform Operations Collector instead of a fork.
> deps: Updated to use latest version of operations-collector

- exporter/googlecloudexporter/README.md
- exporter/googlecloudexporter/config.go
- exporter/googlecloudexporter/config_test.go
- Updates the Google exporter to use a new default resource filter.
- Prior to this change, the exporter used an empty array as the default. If the user did not configure this field, the exporter would ignore all resource attributes.
- After this change, the exporter will use an array of one item as the default. This item has an empty string as the prefix. If the user does not configure this field, the exporter will now include all resource attributes by default.
- Users can still restrict all resource attributes by setting the field manually to an empty array. Or they can still configure the field as before.
> feat: Add a new default resource filter to the Google exporter

- processor/throughputmeasurementprocessor/README.md
- processor/throughputmeasurementprocessor/metrics.go
- processor/throughputmeasurementprocessor/metrics_test.go
- processor/throughputmeasurementprocessor/processor.go
Added the following count metrics to `throughputmeasurement` processor:
- `log_count`
- `metric_count`
- `trace_count`
While most receivers inherently count their object throughput via the OTel framework some don't. Also, most processors do not count their throughput either. Adding counts to the `throughputmeasurement` processor adds a way to get counts of throughput for components that don't count on their own.
Example of metric count prometheus metric:
```
otelcol_processor_throughputmeasurement_metric_count{processor="throughputmeasurement/batch",service_instance_id="4addcd83-9156-4f03-9c4a-0bd93c133359",service_version="v1.9.1"} 6
otelcol_processor_throughputmeasurement_metric_count{processor="throughputmeasurement/receiver",service_instance_id="4addcd83-9156-4f03-9c4a-0bd93c133359",se …
```
> feat: Added Object Counts to throughputmeasurement Processor

- .goreleaser.yml
- Dockerfile
The Dockerfile requires a configuration file to be injected (docker volume / kubernetes configmap) at runtime, otherwise it will fail to start. In order to allow users to use OpAMP, the container needs to function without a configuration.
- Moved user creation toward top
- Created `/etc/otel` and set ownership to the previously created `otel` user
- Added "default" config to container image
- Set `OIQ_OTEL_COLLECTOR_HOME` to `/etc/otel`. We use this variable in the systemd and windows service configurations.
- Added a "default" config to `/etc/otel/config.yaml`, owned by `otel` user
- Set working dir to `/etc/otel`, this allows the `otel` user to write `manager.yaml` to `/etc/otel`
I tested to ensure the collector continues to work without opamp (config injected via configmap).
You can …
> feat: Support OpAMP when running within a container

- plugins/oracledb_metrics.yaml
Added a plugin for OracleDB Metrics.
Here is a small sample of a metric resulting from the plugin:
```
ResourceMetrics #0
ScopeMetrics #0
ScopeMetrics SchemaURL: 
Metric #0
Descriptor:
-> Name: oracle.tablespace.size
-> Description: The size of tablespaces in the database.
-> Unit: by
-> DataType: Sum
-> IsMonotonic: false
-> AggregationTemporality: AGGREGATION_TEMPORALITY_CUMULATIVE
NumberDataPoints #0
Data point attributes:
-> db.system: STRING(oracle)
-> state: STRING(free)
-> database_id: STRING(1643340059)
-> global_name: STRING(ORCL.C.OTEL-AGENT-DEV.INTERNAL)
-> tablespace_name: STRING(SYSTEM)
-> contents: STRING(PERMANENT)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2022-10-06 17:50:47.960831095 +0000 UTC
Value: 6225920 …
```
> feat: OracleDB Metrics Plugin

- plugins/container_logs.yaml
- Added `log_driver` parameter with `auto`, `docker-json-file`, and `containerd-cri` options
- `auto` is the default value and retains the same behavior (detects log format on every log)
- By selecting a log driver, the pipeline will skip a regex match on every single log that enters the pipeline
- Fixed the regex used when checking if containerd cri format
- Previous regex was working for the most part, but I had some application logs match despite coming from docker.
- This [example](https://regex101.com/r/glMYc3/1) shows the previous containerd incorrectly regex matching a docker log.
- Renamed the parsers to better reflect what format they are processing
- docker_parser --> docker_json_file_parser
- containerd_parser --> containerd_cri_parser
These changes are backwards compatible, …
> feat(plugin):  Add log_driver option to container log plugin

- plugins/hadoop_logs.yaml
I stumbled upon this in the wild. At some point between v1.9.0 and v1.9.2, the `expr` language changed. We now need to quote `true` when doing `expr: true`. I did verify that this is backwards compatible and is working as expected with v1.9.0 and v1.9.2.
The hadoop plugin is the only place we do this.
> fix(plugin): Hadoop filter expression

- docs/receivers.md
- go.mod
- go.sum
Changes found here https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14953/
This adds a custom unmarshal step to avoid the default config auto populating the `autodiscover` config when only using the `named` config portions of the `GroupConfig`. 
<details>
<summary>Error received before</summary>
Config: 
```yaml
receivers:
awscloudwatch:
profile: 'kschmitt'
region: us-east-2
logs:
poll_interval: 10s
groups:
named:
/aws/eks/dev-eks-0/cluster:
names: [kube-apiserver-audit-ea9c831555adca1815ae04b884b30566]
exporters:
logging:
file:
path: cloudwatch.json
service:
pipelines:
logs:
receivers:
- awscloudwatch
exporters:
- logging
- file
```
Error before:
```sh
{"level":"fatal","ts":"2022-10-18T11:21:12.744-0400","caller":"collector/main.go:98","msg":"RunService returned …
```
> fix: Update `awscloudwatchreceiver` to fix partial issue with config validation

- plugins/bindplane_logs.yaml
Added plugin for [BindPlane OP](https://github.com/observIQ/bindplane-op/).
- Default path is `/var/log/bindplane/bindplane.log` on a linux system, which is the only supported install path at the moment.
- BindPlane rotates the log into gzip compressed files, which should always be excluded.
- Logs are always json encoded.
- Timestamps are ISO 8601.
- Severity parsing uses the default mapping.
> feat(plugin): BindPlane OP Logs

- plugins/container_logs.yaml
The cri-o regex works, but includes a leading space for the `log` capture groups value. You can see this happening [here](https://regex101.com/r/oMmHS1/1). This causes the json detection (line 134) to fail, meaning containerd logs work great but json message fields are not parsed.
The [updated regex](https://regex101.com/r/sObCdA/1) properly handles the space between the `partial` and `log` capture groups.
> fix(plugin): Container logs cri-o regex

- .github/workflows/check_plugin_docs.yml
Adds github action to verify that plugin document generation is up to date. This currently is with a manual trigger, but will change to on pull request once verified.
> feat: Added temporary manual plugin doc github action check

- docs/plugins/iis_logs.md
- plugins/iis_logs.yaml
Added a `parse_to` parameter to IIS log plugin to allow choosing where to parse logs to `body` or `attributes`. 
**Examples:**
<details>
<summary>W3C Format</summary>
Parse To Body:
```
LogRecord #0
ObservedTimestamp: 2022-11-09 16:51:35.957338 +0000 UTC
Timestamp: 2020-11-03 16:13:15 +0000 UTC
SeverityText: 200
Body: Map({\"c-ip\":\"10.33.121.100\",\"cs(Referer)\":\"-\",\"cs(User-Agent)\":\"Go-http-client/1.1\",\"cs-method\":\"GET\",\"cs-uri-query\":\"-\",\"cs-uri-stem\":\"/\",\"cs-username\":\"-\",\"s-ip\":\"10.33.104.51\",\"s-port\":\"80\",\"sc-status\":\"200\",\"sc-substatus\":\"0\",\"sc-win32-status\":\"0\",\"time-taken\":\"67\",\"timestamp\":\"2020-11-03 16:13:15\"})
Attributes:
-> log.file.name: Str(iis_w3c_format.log)
-> log.file.path: …
```
> feat: Added a parse_to field to iis plugin to allow choose how to parse logs

- docs/plugins/apache_combined_logs.md
- plugins/apache_combined_logs.yaml
Added a parse_to parameter to apache combined log plugin to allow choosing where to parse logs to body or attributes.
**Examples:**
Parse to body:
```
LogRecord #0
ObservedTimestamp: 2022-11-14 18:50:33.744205 +0000 UTC
Timestamp: 2021-06-17 16:06:46 +0000 UTC
SeverityText: 304
SeverityNumber: SEVERITY_NUMBER_INFO2(10)
Body: Map({\"body_bytes_sent\":\"64162\",\"http_referer\":\"https://www.seniordisintermediate.biz/models\",\"http_user_agent\":\"Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_6_3) AppleWebKit/5310 (KHTML, like Gecko) Chrome/39.0.854.0 Mobile Safari/5310\",\"method\":\"POST\",\"path\":\"/v1/login\",\"protocol\":\"HTTP\",\"protocol_version\":\"2.0\",\"remote_addr\":\"129.53.82.110\",\"remote_host\":\"-\",\"remote_user\":\"-\",\"status\":\"304\",\"time\":\"17/Jun/2021:12:06:46 …
```
> update to parse_to field to allow to parse to body or attributes

- docs/plugins/file_logs.md
- plugins/file_logs.yaml
Added a parse_to parameter to file_logs plugin to allow choosing where to parse logs to body or attributes.
**Examples**
Using regex
```bash
regex_pattern: ^(?P<date>[^ ]*) (?P<something>[^ ]*) (?P<something2>[^ ]*)  (?P<rest>.*)$
```
for log
```log
2019-02-06T09:22:27.347-0500 I CONTROL  [initandlisten] db version v3.6.2
```
parse to Body:
```LogRecord #0
ObservedTimestamp: 2022-11-14 20:31:48.093544 +0000 UTC
SeverityText: 
SeverityNumber: SEVERITY_NUMBER_UNSPECIFIED(0)
Body: Map({\"date\":\"2019-02-06T09:22:27.347-0500\",\"rest\":\"[initandlisten] db version v3.6.2\",\"something\":\"I\",\"something2\":\"CONTROL\"})
Attributes:
-> log.file.name: Str(mongodb.log)
-> log_type: Str(file)
Trace ID: 
Span ID: 
Flags: 0
```
Parse to Attributes:
``` …
```
> feat: Add parse_to parameter field to file_logs plugin

- docs/plugins/kubelet_logs.md
- plugins/kubelet_logs.yaml
Added a `parse_to` parameter to IIS log plugin to allow choosing where to parse logs to `body` or `attributes`. 
@jsirianni Validated this in GCP:
With body parsing:
With attribute parsing
> feat: Added a parse_to field to Kubelet plugin to allow choose how to parse logs

- collector/collector.go
- collector/collector_test.go
- internal/service/standalone.go
- opamp/observiq/observiq_client.go
- opamp/observiq/observiq_client_test.go
- opamp/observiq/reload_funcs.go
- opamp/observiq/reload_funcs_test.go
- Added `recover` to handle panics from the main collector goroutine
- Added logic to monitor collector status in managed mode
> feat: Monitor Collector Status in Managed Mode

- docs/plugins/syslog_logs.md
- plugins/syslog_logs.yaml
Added a parse_to parameter to syslog plugin to allow choosing where to parse logs to body or attributes.
** Example
Parse to body
```
LogRecord #0
ObservedTimestamp: 2022-11-15 15:32:17.81204 +0000 UTC
Timestamp: 2022-09-15 18:01:57.756788 +0000 UTC
SeverityText: info
Body: Map({\"appname\":\"content-library\",\"facility\":16,\"hostname\":\"vcsa\",\"message\":\"2022-09-15T18:01:57.756Z | DEBUG    | opId-bdfbb34a-1a9c-4d01-9ea3-2a415f97c245 | cls-background-executor-2 | StsTrustChainImpl              | Refreshing cert chain from sso server...\",\"priority\":134,\"version\":1})
Trace ID: 
Span ID: 
Flags: 0
```
Parse to attributes
```
LogRecord #0
ObservedTimestamp: 2022-11-15 15:33:13.109556 +0000 UTC
Timestamp: 2022-09-15 18:01:57.756788 +0000 UTC …
```
> feat: Add parse to parameter for syslog

- docs/plugins/tomcat_logs.md
- plugins/tomcat_logs.yaml
Added a parse_to parameter to tomcat log plugin to allow choosing where to parse logs to body or attributes.
**Examples
Parse to body with access log
```
LogRecord #0
ObservedTimestamp: 2022-11-15 16:21:47.113723 +0000 UTC
Timestamp: 2021-01-21 04:26:02 +0000 UTC
SeverityText: 200
Body: Map({\"bytes_sent\":\"11216\",\"method\":\"GET\",\"path\":\"/\",\"remote_host\":\"10.33.104.26\",\"remote_user\":\"-\",\"status\":\"200\",\"timestamp\":\"20/Jan/2021:23:26:02 -0500\"})
Attributes:
-> log.file.name: Str(tomcat_access_log.log)
-> log_type: Str(tomcat.access)
Trace ID: 
Span ID: 
Flags: 0
```
Parse to body catalina log
```
LogRecord #0
ObservedTimestamp: 2022-11-15 16:22:36.314092 +0000 UTC
Timestamp: 2021-01-20 12:51:42.078 +0000 UTC
SeverityText: INFO …
```
> feat: Add parse_to parameter to tomcat

- docs/plugins/vcenter_logs.md
- plugins/vcenter_logs.yaml
Added a parse_to parameter to Vcenter log plugin to allow choosing where to parse logs to body or attributes.
**Example**
Parse to body
```
LogRecord #0
ObservedTimestamp: 2022-11-15 18:47:57.198006 +0000 UTC
Timestamp: 2022-09-15 18:01:57.734952 +0000 UTC
SeverityText: info
Body: Map({\"appname\":\"ssoadminserver\",\"facility\":16,\"hostname\":\"vcsa\",\"message\":\"2022-09-15T18:00:42.903Z INFO ssoAdminServer[101:pool-2-thread-5] [OpId=d09ba743-1106-412d-8d83-03512f67560e] [com.vmware.identity.admin.vlsi.ConfigurationManagementServiceImpl] Vmodl method ConfigurationManagementService.getIssuersCertificates return value is []\",\"priority\":134,\"version\":1})
Attributes:
-> log_type: Str(vmware_vcenter)
-> net.host.ip: Str(127.0.0.1)
-> …
```
> feat: Add parse_to parameter to Vcenter

- .goreleaser.yml
- Makefile
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
For OpenShift deployments that require a RHEL certificate image, we will need a container image built on top of Red Hat's Universal base image.
- Moved Dockerfile --> docker/Dockerfile.ubuntu
- Added docker/Dockerfile.ubi8
- Added docker build config to goreleaser, with single `Minor }}.{{ .Patch }}-ubi8` tag
- Replaced `gcr.io/observiq-container-images/stanza-base:v1.2.2` with `ubuntu:22.04`
- Added `shell` and `home` options to `adduser` command
I opted to stop using the `stanza-base` image because I wanted to keep both Dockerfiles as identical as possible. This means the ubuntu image needs the `apt` commands for installing the systemd, tzdata, and ca-certificates packages. Stanza base image is nice because it pins our package versions in a nice way, but it is additional maintenance …
> feat(container): Red Hat Universal base image

- collector/settings.go
- factories/factories.go
- internal/throughputwrapper/receiver_factory_wrapper.go
- processor/throughputmeasurementprocessor/factory.go
In managed mode during a reconfiguration the throughput internal telemetry counters would not reset their values but rather just change labels. Added logic so when factories are recreated it resets the telemetry counters.
Screen shot showing the reset on a reconfigure:
> fix: Added package level functions to reset internal telemetry views

- config/example.yaml
In otel v0.64.0 the `verbosity` parameter was added and the `loglevel` parameter slated for deprecation in the logging exporter. Updated the example base config with the `verbosity` parameter.
> Changed logging exporter loglevel to verbosity in example config

- .goreleaser.yml
- config/logging.stdout.yaml
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
Seeing some inconsistent behavior between the ubuntu based image and the rhel ubi image. The logging.yaml file is written incorrectly. This PR creates a `config/logging.stdout.yaml` logging config file and uses `COPY` to add it to each container image.
When running the container, I can see that the logging.yaml file is correct:
```
bash-4.4$ ls -la
total 24
drwxr-xr-x 1 otel otel 4096 Nov 18 15:12 .
drwxr-xr-x 1 root root 4096 Nov 18 15:12 ..
-rw-r--r-- 1 otel otel 3184 Nov 18 15:11 config.yaml
-rw-r--r-- 1 otel otel   28 Nov 18 15:11 logging.yaml
drwxr-xr-x 2 root root 4096 Nov 18 15:12 plugins
bash-4.4$ cat logging.yaml
output: stdout
level: info
```
> fix(container): RHEL UBI logging.yaml

- docs/installation-windows.md
- internal/service/service_windows.go
* Redirect stderr when running as a service on Windows, so that panics will be logged
I tested this on a windows machine using a fake "panic" extension that panics on component startup.
> feat: Redirect stderr to file on Windows

- .goreleaser.yml
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
For RHEL certificatation, we need to include the collector's license at `/licenses` within the container image. When running the RHEL [preflight tool](https://github.com/redhat-openshift-ecosystem/openshift-preflight), I see
```json
"failed": [
{
"name": "HasLicense",
"elapsed_time": 0,
"description": "Checking if terms and conditions applicable to the software including open source licensing information are present. The license must be at /licenses",
"help": "Check HasLicense encountered an error. Please review the preflight.log file for more information.",
"suggestion": "Create a directory named /licenses and include all relevant licensing and/or terms and conditions as text file(s) in that directory.",
"knowledgebase_url": "https://access.redhat.com/documentation/en-us/red_hat_software_ …
```
> Copy collector license into container image (RHEL certification)

- .github/workflows/manual_msi_build.yml
- .github/workflows/multi_build.yml
- .github/workflows/release.yml
Updated GH Action Windows Runners to 2022 as that is the current `latest`. Checked macOS and Ubuntu and verified the current versions are latest.
> Updated all Windows GH Action Runners to 2022

- .github/workflows/release.yml
Removed deprecated `set-output` from GitHub Actions. These were only used for setting the tag. I replaced this with `GITHUB_REF_NAME` and `github.ref_name`. These are newer ENVs that contain the short ref name that triggered the workflow.
More info [here](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)
> Removed deprecated set output and used new reference variable for tag

- scripts/install/install_unix.sh
* Force the install script to use the old config instead of prompting for a user choice on Debian systems.
* This change makes the script non-interactive if the default config is changed, which it previously was not.
Tested on a Debian 10 VM, upgrading from v1.10.0 to v1.12.0.
> fix: Force the install script to take old config on debian systems

- .github/workflows/release.yml
Wrapped `GITHUB_REF_NAME` in curly brackets as it wasn't being evaluated in the release task.
> fix: Fixes release task with new GITHUB_REF_NAME

- .github/workflows/release.yml
Changed `GITHUB_REF_NAME` to `github.ref_name` in release MSI build
> fix: Changed to using context notation for GITHUB_REF_NAME in msi release

- plugins/oracledb_metrics.yaml
When building `$datasource`, use plain `=` instead of `%3D`
> fix(oracledb): Don't encode '=' in Oracle DB datasource

- config/google_cloud_exporter/prometheus/README.md
- config/google_cloud_exporter/prometheus/config.yaml
The Prometheus example results in two issues:
- Metrics show up in GCP as [generic_task](https://cloud.google.com/monitoring/api/resources#tag_generic_task) when we would prefer [generic_node](https://cloud.google.com/monitoring/api/resources#tag_generic_node).
- Metric labels do not align with Prometheus server. Prometheus server would have `job` and `instance` labels.
Solution: "Rename" `service.name` and `service.instance.id` to `job` and `instance`. This will prevent the `generic_task` mapping while also emitting metrics that look closer to what you would expect when coming from a Prometheus environment.
I also re-wrote the readme to support things like multiple scrape configs and custom metric prefix.
> Update Google Cloud Prometheus example config to use `generic_node`

- go.mod
- go.sum
Fixed an issue in v1.14.0 where if the `credentials` or `credentials_file` parameter was specified it would cause the google cloud exporter to fail to start. Using a fork of `github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector` to remove new logic that autodiscovers credentials. 
Commit with change [here](https://github.com/observIQ/opentelemetry-operations-go/commit/d92100d9c7286ebe5ca09ad1af15b0c2b813a736)
> fix: Fix issue where specifying crednetials or credential_file won't work in googlecloud Exporter

- config/google_managed_prometheus/hostmetrics/config.yaml
- config/prometheus/kafka/config.yaml
- config/prometheus/mongodb/config.yaml
- config/prometheus/mysql/config.yaml
- config/prometheus/redis/config.yaml
- docs/processors.md
- docs/receivers.md
- factories/processors.go
- factories/receivers.go
- go.mod
- go.sum
Removing the `github.com/GoogleCloudPlatform/opentelemetry-operations-collector` as a dependency to reduce external dependencies on the collector.
This removes the following components:
- normalizesums processor
- varnish receiver
> deps: Removed dependency on opentelemetry-operations-collector

- go.mod
- go.sum
One of our test files imported github.com/shirou/gopsutil/v3 3.22.11 which had the crash in it. Downgraded to 3.22.10.
> deps: Downgraded github.com/shirou/gopsutil/v3 to 3.22.10 in main go.mod

- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
Users expect that [$OIQ_OTEL_COLLECTOR_HOME/storage](https://github.com/observIQ/bindplane-op/blob/main/resources/source-types/file_log.yaml#L137) exists and is read / writable by the collector process.
Also added OIQ_OTEL_COLLECTOR_STORAGE to be consistent w/ [existing services](https://github.com/observIQ/observiq-otel-collector/blob/main/service/observiq-otel-collector.service#L12).
Tested with:
```bash
docker run -it --entrypoint ls observiq/observiq-otel-collector-amd64:latest -la /etc/otel
```
```
-rw-r--r-- 1 otel otel 3184 Jan  9 21:00 config.yaml
-rw-r--r-- 1 otel otel   27 Jan  9 21:00 logging.yaml
drwxr-xr-x 2 root root 4096 Jan  9 21:00 plugins
drwxr-x--- 2 otel otel 4096 Jan  9 21:00 storage
```
For production environments, the /etc/otel/storage directory would be bound to a …
> fix(container): Add storage directory to Dockerfiles

- scripts/install/install_macos.sh
- service/com.observiq.collector.plist
* Create storage dir for macOS install script
* This directory is required for filelog based plugins, otherwise the collector will fail to start. 
* Add `OIQ_OTEL_COLLECTOR_STORAGE` env var to MacOS service file
* This env is present in other installs, so we should have this here to be consistent.
> fix: Create storage dir for macOS

- receiver/sapnetweaverreceiver/client_test.go
- receiver/sapnetweaverreceiver/config.go
- receiver/sapnetweaverreceiver/config_test.go
- receiver/sapnetweaverreceiver/factory.go
- receiver/sapnetweaverreceiver/go.mod
- receiver/sapnetweaverreceiver/metrics.go
I think this was missed in the original SAP PR but the receiver was using the `github.com/pkg/errors` package in place of the stdlib `errors` package. I switched it to using the stdlib package to reduce the dependencies of the receiver.
> deps: Removed github.com/pkg/errors in sap receiver in favor of stdlib errors

- go.mod
- go.sum
Updates our forked version of opentelemetry-operations-go to https://github.com/observIQ/opentelemetry-operations-go/commit/01510a5dd153cb6d89d777e2491a383bc9c195a7 - this fixes a bug where labels of previous logs would be placed on subsequent logs under scenerios with moderate throughput.
Tested against a postgres log that was known to cause the issue.
> fix: hotfix issue where GCL logs would get copies of previous log attributes

- cmd/collector/main.go
- collector/featuregates.go
- collector/featuregates_test.go
- go.mod
Hard coded `filelog.allowFileDeletion` to `true` to enable `delete_after_read` functionality in filelog receiver.
> feat: Added feature flag for delete after read

- windows/templates/WixUI_HK.wxs
- windows/templates/product.wxs
Added logic to MSI to not give the user the option to add the `manager.yaml` on install for Windows 7 or older.
We utilize the [VersionNT](https://learn.microsoft.com/en-us/windows/win32/msi/versionnt) and [VersionNT64](https://learn.microsoft.com/en-us/windows/win32/msi/versionnt64) properties to determine the Windows version and make OpAMP installation logic conditional.
Tested this on Windows 7 32bit and Windows Server 2012 R2 64bit.
> fix: Remove OpAMP setup from MSI on older version of Windows

- .github/workflows/manual_msi_build.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Makefile
- windows/templates/WixUI_HK.wxs
- windows/templates/product.wxs
- Added support for building Windows 32bit executable and MSI as release artifacts
- In release task broke the 32bit and 64bit MSI builds into separate jobs
- Updated goreleaser action to v4
- Removed CINC testing as part of MSI builds as that's handle on release our internal testing suit
> feat: Windows 32bit Deliverables

- docs/plugins/container_logs.md
- plugins/container_logs.yaml
Added the storage extension to the container logs plugin, following the pattern established [here](https://github.com/observIQ/observiq-otel-collector/commit/25abf408990357b4ae7fdf4e92d18c8fdf7b90f5).
The environment variable `OIQ_OTEL_COLLECTOR_STORAGE` is [set by default](https://github.com/observIQ/observiq-otel-collector/blob/main/docker/Dockerfile.ubuntu#L60) to `/etc/otel/storage`. Users will likely modify this to fit their deployment.
The plugin has two possible receivers (filelog and journald), both of which support the storage extension.
I tested by:
1. Deploying 1.17.0 and verifying that logs were flowing correctly
2. Build an image from my branch and updated my container
3. Verified that logs were flowing correctly
4. Deleted my agent
5. Waited two minutes and re-deployed the …
> feat(plugin): Add checkpoint storage to container plugin

- go.mod
- go.sum
Updated a github.com/GoogleCloudPlatform/opentelemetry-operations-go with [this](https://github.com/observIQ/opentelemetry-operations-go/commit/44351a011294dae4a6cbcd2214fe61cb5a5f6aa9) to prevent issue where credentials or credentials file are specified.
> fix: Updated github.com/GoogleCloudPlatform/opentelemetry-operations-go with fork with credentials fix

- .github/workflows/check-formatting.yml
- .github/workflows/check-license.yml
- .github/workflows/check_plugin_docs.yml
- .github/workflows/gosec.yml
- .github/workflows/manual_msi_build.yml
- .github/workflows/misspell.yml
- .github/workflows/multi_build.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
- Makefile
- cmd/plugindocgen/go.mod
- exporter/googlecloudexporter/go.mod
- expr/go.mod
- go.mod
- opamp/observiq/observiq_downloadable_file_manager.go
- packagestate/go.mod
- processor/logcountprocessor/go.mod
- processor/logdeduplicationprocessor/go.mod
- processor/maskprocessor/go.mod
- processor/metricextractprocessor/go.mod
- processor/metricstatsprocessor/go.mod
- processor/resourceattributetransposerprocessor/go.mod
- processor/samplingprocessor/go.mod
- processor/throughputmeasurementprocessor/go.mod
- receiver/pluginreceiver/go.mod
- receiver/routereceiver/go.mod
- receiver/sapnetweaverreceiver/go.mod
- updater/go.mod
Updated all modules to Go 1.19 as OTel has updated in the [v0.72.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.72.0) release. 
Gosec needed to be updated to v2.15.0 as there was a failure while running on 1.19. The new version of gosec also identified an ignored error on defer so a logging statement was added.
> Updated all modules to Go 1.19

- docs/installation-linux.md
- scripts/install/install_unix.sh
Resolves #934 
Added the `-f`/`--file` flag to the Linux installation script to allow for specifying a file path to a local package to install.
**Screen shot using the `--file` flag:**
> feat: Add flag to Linux Install to specify local package

- docs/plugins/iis_logs.md
- plugins/iis_logs.yaml
* Change default for `start_at` to beginning on w3c (this is required if headers are being auto-detected!)
* Mark `w3c_header` parameter as not required (if not specified, automatic field detection is enabled)
* Add storage to the IIS plugin
* This is needed, otherwise the plugin will always start from the beginning in auto-header mode and re-emit log files that have already been read.
<details>
<summary>Config</summary>
```yaml
receivers:
plugin:
path: './plugins/iis_logs.yaml'
parameters:
log_format: "w3c"
file_path:
- ./tmp/w3c_format_logs.log
exporters:
logging:
service:
pipelines:
logs:
telemetry:
metrics:
level: none
```
</details>
<details>
<summary>Log</summary>
```
#Software: Microsoft Internet Information Services 10.0 …
```
> feat: Enhance IIS plugin with automatic field detection and storage

- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
The `--config` flag is redundant with `WORKDIR /etc/otel`. The config, `/etc/otel/config.yaml` will get used by default if no flag or environment variable are specified.
This resolves an issue where a user might set `CONFIG_YAML_PATH` only to have it overwritten by the `--config` flag which is set in the Dockerfile.
I verified that the container image runs without issue, and uses `/etc/otel/config.yaml` by default, of nothing is specified.
> fix(container): Remove --config flag from entrypoint command

- receiver/sapnetweaverreceiver/metrics.go
- receiver/sapnetweaverreceiver/scraper_test.go
- receiver/sapnetweaverreceiver/testdata/api-responses/ABAPSystemWPTableEmptyResponse.xml
- receiver/sapnetweaverreceiver/testdata/api-responses/AlertTreeEmptyResponse.xml
- receiver/sapnetweaverreceiver/testdata/api-responses/EnqStatisticEmptyResponse.xml
- receiver/sapnetweaverreceiver/testdata/api-responses/InstancePropertiesEmptyResponse.xml
- receiver/sapnetweaverreceiver/testdata/api-responses/ProcessListEmptyResponse.xml
- receiver/sapnetweaverreceiver/testdata/api-responses/QueueStatisticEmptyResponse.xml
- receiver/sapnetweaverreceiver/testdata/api-responses/SystemInstanceListEmptyResponse.xml
An error is occurring when parsing systemWPTableResponse on an empty response.
``` log
Mar 10 15:25:24 netweaver-7 observiq-otel-collector[11720]: panic: runtime error: index out of range [-2]
Mar 10 15:25:24 netweaver-7 observiq-otel-collector[11720]: goroutine 115 [running]:
Mar 10 15:25:24 netweaver-7 observiq-otel-collector[11720]: github.com/observiq/observiq-otel-collector/receiver/sapnetweaverreceiver.(*sapNetweaverScraper).recordSapnetweaverWorkProcessActiveCountDataPoint(0xc00096a3f0, 0x0?, 0xc001286330, 0x0?)
Mar 10 15:25:24 netweaver-7 observiq-otel-collector[11720]:         /home/runner/work/observiq-otel-collector/observiq-otel-collector/receiver/sapnetweaverreceiver/metrics.go:272 +0x5b4
Mar 10 15:25:24 netweaver-7 observiq-otel-collector[11720]: …
```
> fix(sapnetweaverreceiver):  Record empty response values correctly

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
Added a `--base_url` flag to the macOS and Linux installation scripts. This allows the script to look at a host other than GitHub for release while still being able to reason about the OS, architecture, and package type needed for the target system.
> feat: Added base_url flag to macOS and Linux installation scripts

- docs/plugins/w3c_logs.md
- plugins/w3c_logs.yaml
This PR exposes most of the filelog receiver and csv_parser parameters as plugin parameters to give full functionality to the users
[cdn_httpaccess-testfile.log](https://github.com/observIQ/observiq-otel-collector/files/10972800/cdn_httpaccess-testfile.log)
[collector.log](https://github.com/observIQ/observiq-otel-collector/files/10972802/collector.log)
> feat(plugin): W3C Plugin: Added most of the possible fields for filelog receiver and csv_parser operator as plugin parameters

- .github/workflows/release.yml
At the end of the release action bundle all artifacts in an archive.
Bundles all artifacts into a `.tar.gz` archive and uploads it to the release via the [AButler/upload-release-assets](https://github.com/marketplace/actions/upload-assets-to-a-release) action.
Tested the archive create changes in a [test action](https://github.com/observIQ/observiq-otel-collector/actions/workflows/test_release.yml)
> feat: Archive artifacts on release

- cmd/collector/main.go
- cmd/collector/main_test.go
- docs/opamp.md
This change adds support for the following OpAMP options using environment variables
- TLS skip verify (skip verifying the server's certificate)
- CA certificate (can be used as an alternative to the underlying operating systems trust store)
- Mutual TLS
- Private Key
- Certificate
This solves a container use-case, where the collector's configuration is derived only from environment variables.
> feat(opamp): Add environment variable options for TLS

- docs/plugins/iis_logs.md
- plugins/iis_logs.yaml
A request from a POC customer getting ready to move to production is to be able to specify max_concurrent_files for IIS logs. Since this makes sense, I've added it to the plugin.
[cdn_httpaccess-testfile.log](https://github.com/observIQ/observiq-otel-collector/files/11028621/cdn_httpaccess-testfile.log)
[iis-collector.log](https://github.com/observIQ/observiq-otel-collector/files/11028632/iis-collector.log)
[config-iis.yaml.txt](https://github.com/observIQ/observiq-otel-collector/files/11028633/config-iis.yaml.txt)
> feat(plugin): Add max_concurrent_files parameter to the IIS plugin

- processor/maskprocessor/config.go
- processor/maskprocessor/config_test.go
- processor/maskprocessor/factory.go
- processor/maskprocessor/factory_test.go
- processor/maskprocessor/processor.go
- processor/maskprocessor/processor_test.go
- Changed the behavior of default rules in the mask processor.
- Default rules are now set at "runtime" rather than "config time"
- The previous design was flawed, because otel uses mapstructure to unmarshal configs. When mapstructure unmarshals into a map that already has values, it doesn't wipe that map clean with the incoming map. Instead, it will merge the source and destination. In this scenario, only duplicate keys would be overwritten. This means that if a user configured their own rules in the previous design, the processor would load the union of the two rulesets. This should be considered a bug, since defaults should only apply if a user leaves this field blank. This can be accomplished by moving where the default is set and avoiding mapstructure altogether.
> fix: Fixed bug with default rules in the mask processor

- .github/workflows/release.yml
- .goreleaser.yml
Added additional container image tags for pushing to Github's container registry. This will give us flexibility on where we store and pull our images. Dockerhub will continue to be used but we should consider Github to be our primary repository. Pushed images will show up as packages. You can see an example [here](https://github.com/orgs/observIQ/packages?repo_name=bindplane-op).
Changes
- Login to Github container registry in addition to Dockerhub
- Add tags to Goreleaser config.
You can see how we do this in BindPlane's repo
- https://github.com/observIQ/bindplane-op/blob/main/.github/workflows/release.yml#L23
- https://github.com/observIQ/bindplane-op/blob/main/.goreleaser.yml#L204
After running Goreleaser locally, I have the following tags:
```
REPOSITORY …
```
> feat(container): Push images to Github container registry

- receiver/sapnetweaverreceiver/README.md
- receiver/sapnetweaverreceiver/documentation.md
- receiver/sapnetweaverreceiver/internal/metadata/generated_metrics.go
- receiver/sapnetweaverreceiver/internal/metadata/generated_metrics_test.go
- receiver/sapnetweaverreceiver/internal/metadata/testdata/config.yaml
- receiver/sapnetweaverreceiver/metadata.yaml
- receiver/sapnetweaverreceiver/metrics.go
- receiver/sapnetweaverreceiver/scraper.go
- receiver/sapnetweaverreceiver/scraper_test.go
- receiver/sapnetweaverreceiver/testdata/api-responses/AlertTreeResponse.xml
- receiver/sapnetweaverreceiver/testdata/golden-response/expected.json
2 metrics were not collecting as expected:
1. `sapnetweaver.work_process.job.aborted.count` was assumed to have a value attached to the number of aborted jobs. A response for a RED control state may look like `AbortedJobs, 392, RED, ,` where the last column indicates a value, yet is empty.  Therefore aborted jobs was updated to `sapnetweaver.work_process.job.aborted.status`.  
2.  `sapnetweaver.connection.error.count` GetAlertTree path was implemented incorrectly as `StatNoOfConnectionErrors`  instead of `StatNoOfConnectErrors` and should now emit properly.
Updated scope SAP Netweaver doc.
> fix(sapnetweaverreceiver): Aborted Jobs and Connection error count

- counter/counter.go
- counter/counter_test.go
- counter/go.mod
- counter/go.sum
- go.mod
- processor/logcountprocessor/go.mod
- processor/logcountprocessor/processor.go
* Factor count logic out of the logcount processor, into a shared module so that it can be used in separate datapointcount and tracecount processor.
> chore: Factor count logic out of logcount processor

- expr/datapoint.go
- expr/datapoint_test.go
- expr/span.go
- expr/span_test.go
* Add ConvertToDatapointResourceGroup and ConvertToSpanResourceGroups functions that convert pdata datapoints and spans into a flattened representation
This change allows us to use these telemetry types in `expr` expressions, which will be necessary to implement a count processor for these two telemetry types.
> feat(expr): Update with the ability to convert spans and datapoints to a map representation

- plugins/couchbase_metrics.yaml
Fixed the Couchbase Metrics plugin to use the `datapoint` context rather than `metric` for the transformprocessor.
<details>
<summary>Metrics Collected:</summary>
```
ResourceMetrics #0
Resource attributes:
-> service.name: Str(couchbase)
-> service.instance.id: Str(localhost:8091)
-> net.host.port: Str(8091)
-> http.scheme: Str(http)
ScopeMetrics #0
ScopeMetrics SchemaURL: 
Metric #0
Descriptor:
-> Name: couchbase.bucket.memory.high_water_mark.limit
-> Description: The memory usage at which items will be ejected.
-> Unit: By
-> DataType: Gauge
NumberDataPoints #0
Data point attributes:
-> bucket: Str(beer-sample)
StartTimestamp: 1970-01-01 00:00:00 +0000 UTC
Timestamp: 2023-04-10 16:28:42.756 +0000 UTC
Value: 178257920.000000
Metric #1 …
```
> fix: Changed Couchbase metric plugin to use datapoint context

- .github/workflows/manual_msi_build.yml
- .github/workflows/release.yml
- windows/scripts/fetch-dependencies.sh
- windows/templates/product.wxs
- Updated msi builds to use [observIQ/go-msi v2.2.0](https://github.com/observIQ/go-msi/releases/tag/v2.2.0)
- Added Recovery conditions to Windows Service via the [WixUtilExtension ServiceConfig](https://wixtoolset.org/docs/v3/xsd/util/serviceconfig/)
- Always restarts
- Waits 5 seconds to restart
- Clears restart counter after 30 days
New set properties from Service UI:
1. Create an MSI using the [manual_msi_build action](https://github.com/observIQ/observiq-otel-collector/actions/workflows/manual_msi_build.yml) pointing to this branch.
2. Install the MSI on a box
3. Verify in the Collector Service Properties under `Recovery` that the recovery options are set.
4. Trigger recovery by ending the Collector process via task manager.
> feat(windows-service-reliability): Windows Service Auto Restarts on Failure

- updater/internal/service/service_windows.go
- updater/internal/service/service_windows_test.go
Added recovery actions to updater binary to match settings in #1023. This will ensure any existing agents will have the recovery actions applied to them on update.
> feat(windows-service-recovery): Apply Recovery actions to existing agents on update

- processor/maskprocessor/README.md
- processor/maskprocessor/processor.go
- processor/maskprocessor/processor_test.go
- Fixed and issue where default rules would not mask strings in the form of `[masked_{RULE_NAME}]`
- Also, fixed default regex for IPv4 mask to have word boundaries like other default rules
> fix(mask-processor): Fixed Default rules not having correct mask strings

- .github/workflows/release.yml
- .goreleaser.yml
In addition to Dockerhub and Github Container Registry, we would like to push images to Google Artifact Repository.
- Added docker login step for GAR using the secret `ORG_OBSERVIQ_PUBLIC_GCR_JSON_KEY`, which has already been configured on this repo.
- Added additional tags to debian and rhel amd64 / arm64 builds
- Added multi arch manifests for new `us-central1-docker.pkg.dev` tags.
Version 1.22 of the collector was pulled and re-tagged with `us-central1-docker.pkg.dev`. You can pull the image with:
```bash
docker pull us-central1-docker.pkg.dev/observiq-containers/collector/observiq-otel-collector:1.22.0
```
This PR was based on BindPlane's https://github.com/observIQ/bindplane-op/pull/900/files
Building results in the following image tags:
```bash
➜  observiq-otel-collector …
```
> Tag and push images to google artifact repository

- plugins/container_logs.yaml
Updated the `cri-o` regex parser to handle logs which do not have a message. This is a rare occurrence but I do see it every once and a while.
The regex parser will fail and cause dependent operators to fail (three errors per failure).
```
entry does not contain the combine_field
```
```
remove: field does not exist
```
```
regex pattern does not match
```
The regex has been updated to allow for a missing space after the partial field and missing message field.
See https://regex101.com/r/Mk8fY5/1
> fix(plugin): Container logs cri-o regex, allow empty message

- plugins/container_logs.yaml
The container logs plugin does not contain severity parsing. In an effort to fall in line with [Google's GKE log agent](https://cloud.google.com/blog/products/management-tools/using-logging-your-apps-running-kubernetes-engine), I have added the following:
- parse `attributes.stream` for basic severity
- parse `body.severity` if present, using default mappings
- parse `body.level` if `severity` is not present, using default mappings
This PR handles common severity cases. Support for more advanced options could come in the future, such as custom severity field / custom mapping, etc.
Before:
After:
- steam: stdout (info log)
- stream: stderr (error log)
- body.severity (debug log)
> feat(plugin): Add Severity parsing to Kubernetes container logs

- docs/exporters.md
- factories/exporters.go
- go.mod
- go.sum
Cherry picked s3 exporter commit from release/v1.25.0 branch as we want it in the v1.24.0 release.
> feat(exporters): Include awss3exporter from otel-contrib

- .github/workflows/release.yml
* Path to the build artifact has changed, maybe related to switching to go-releaser pro.
See the failure here: https://github.com/observIQ/observiq-otel-collector/actions/runs/5006631107/jobs/8972160306
> fix: Fix incorrect build path when copying the build windows binary in release

- .github/workflows/multi_build.yml
- .github/workflows/tests.yml
Updated build and test CI to use `windows-2022-8-cores` larger box to fix OOM errors
> chore(ci): Updated runner for windows test and build to 8 core box

- cmd/collector/main.go
- collector/collector.go
- collector/collector_test.go
- collector/mocks/mock_collector.go
- collector/settings.go
- collector/settings_test.go
- collector/test/slow_receiver.yaml
- internal/service/standalone.go
- opamp/observiq/observiq_client.go
- opamp/observiq/observiq_client_test.go
This change adds timeouts to the internal collector shutdown.
This means that the collector will not take large amounts of time to shutdown. This is important during opamp, where long shutdowns can make the collector seem like it's hung up, and also during shutdown on Windows, where the service manager does not kill the service when it refuses to shutdown nicely.
> fix: Add timeouts to collector shutdown

- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
The [openjdk](https://hub.docker.com/_/openjdk) container image is deprecated. It has been replaced with a suggested alternative [eclipse-temurin](https://hub.docker.com/_/eclipse-temurin).
This should resolve the container issues in #1113 as the new container supports `arm32v7`
> deps(container): Replaced deprecated openjdk container image with eclipse-temurin

- scripts/install/install_unix.sh
Fixes an issue where config files would be missing on Linux systems using the debian package on reinstall after the `/opt/observiq-otel-collector` directory was deleted.
**Steps to reproduce issue:**
1. Install the collector on a system with `dpkg` via the installation script
2. Uninstall the collector via the installation script using the `-r` flag
3. Remove the collector directory by running `sudo rm -rf /opt/observiq-otel-collector`
4. Install the collector again via the installation script and notice the config files are missing and the service failed to start.
**Fix:**
On install of a debian package check if the collector directory exists. If it does not check if the debian package is still registered with `dpkg`. If it is purge the package for a clean state then install.
> fix(install): Fixes Linux reinstallation after manual uninstall

- .github/workflows/release.yml
Removed amplify trigger from the release as it doesn't work and is triggering a private github action that counts against our private action balance.
> chore: Removed amplify trigger from release workflow

- docs/plugins/apache_common_logs.md
- plugins/apache_common_logs.yaml
We need the option to parse to body for Apache Common. This change follows the pattern established in previous plugin updates.
> feat(plugin): Support parse_to option for Apache Common

- docs/plugins/container_logs.md
- plugins/container_logs.yaml
BindPlane deploys the agent with the pod name `bindplane-node-agent-*` and `bindplane-cluster-agent-*`. These pods should be excluded by default, to prevent circular logging.
Using BindPlane, I can see the agent's logs by filtering on `k8s.namespace.name: bindplane-agent`:
To simulate this change, I had to update the source configuration with the same exclusion:
With the filter in place, and the exclusion, the agent is reporting zero logs (as expected).
> fix(plugin): Container logs: Exclude bindplane-agent logs by default

- internal/service/service_windows.go
- internal/service/service_windows_test.go
- updater/internal/logging/logging_others.go
- updater/internal/logging/logging_windows.go
- updater/internal/service/service_windows.go
- updater/internal/service/testdata/test-windows-service.go
* When shutting down, we cap the time for stopping to 20 seconds
* This fixes issues where shutting down the service can be unresponsive, and you get an error message in Service Manager
* This fixes an issue where the process living too long can cause the update process to fail on windows.
* Wait for the windows service to actually be stopped in the update logic
* This patches a race condition in the update path, where the collector may fail to properly update if the process is not actually stopped by the time it tries to overwrite to collector binary
* Update the updater logging for windows to match Linux, and use ISO8601 timestamps instead of unix timestamps.
> fix: When shutting down on windows, set a max timeout of 20 seconds

- internal/service/managed.go
- opamp/observiq/identity.go
- opamp/observiq/identity_test.go
- opamp/observiq/observiq_client.go
- opamp/observiq/reload_funcs_test.go
Modified to pass the version into the OpAMP client rather than pulling it from the version package. This way we can easily set collector version in Amplify scaling tool.
> Pass Version into OpAMP Client

- .github/workflows/codeql.yml
* Add codeql yaml for advanced configuration
This will let us run CodeQL only on push to main/release branches. This way it doesn't interrupt our PR flow with overly long checks.
> chore: add CodeQL action

- receiver/azureblobrehydrationreceiver/receiver.go
* Have a storage per-telemetry type
* This could cause a deadlock on startup, since the client will not be able to acquire the same storage client as another telemetry type (due to the acquired file lock).
* Close the storage on shutdown
* If we don't close, the storage client will not release the file lock it holds, and will cause a deadlock on reconfigure through opamp.
> fix(azureblobreceiver): Storage shutdown and partitioning between telemetry types

- processor/datapointcountprocessor/go.mod
- processor/datapointcountprocessor/go.sum
- processor/logcountprocessor/go.mod
- processor/logcountprocessor/go.sum
- processor/spancountprocessor/go.mod
- processor/spancountprocessor/go.sum
- receiver/httpreceiver/go.mod
Updated to OTel [v0.88.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.88.0)
> deps: Updated OTel to v0.88.0

- service/observiq-otel-collector
This startup script will be needed to support any Linux distros that aren't using systemd. This is mostly older distros, but some modern tiny distros still use init.d scripts as well.
Known issues/concerns to be addressed in a future PR:
- error.log doesn't get rotated (still researching best way to do this)
- Has only been tested on EL6. Needs to be tested on SLES11, and a modern tiny distro as well.
> feat(service): SysV init.d style startup script

- collector/featuregates.go
* Adds the `filelog.mtimeSortType` feature flag, which enables using the `mtime` sort type in the filelog's `ordering_criteria` section.
> feat: Add filelog.mtimeSortType feature flag

- exporter/chronicleexporter/README.md
- exporter/chronicleexporter/config.go
- exporter/chronicleexporter/marshal.go
- Add support for attaching the namespace to the payload for chronicle
- Add mapping for SQL server because noticed the export to chronicle just works with this mapping
> feat: Add Chronicle namespace config option

- receiver/httpreceiver/logs.go
* Always use http.Server.Serve instead of http.Server.ServeTLS
The listener returned from `serverSettings.ToListener` will already have TLS built in, so it strips any TLS handshake stuff before it reaches the server. Since it's double wrapped due to ServerTLS, the inner TLS handler doesn't see the handshake, and always assumes it's just getting a normal http request, even when sending an https request.
> fix(httpreceiver): Fix double wrapped TLS listener

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
Add functionality to the install scripts to have it check the provided endpoint for connectivity prior to installation, and offer the user the ability to opt out.
This is feature gated by a command line flag (-c|--check-bp-url) to preserve backwards compatibility.
After this gets released, the BindPlane "Install Agent" should have the `-c` flag added
> feat(install_scripts): Check BindPlane URL before installing

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
This brings both the OSX and UNIX install scripts into parity on behavior, as previously discussed with @BinaryFissionGames in another PR.
Edit:
Things not addressed by this PR:
Lack of support for all flags in the OSX script. Notably, proxy and local file install.
> fix: Make install scripts uniform in behavior

- exporter/chronicleforwarderexporter/README.md
- switch to `transport` instead of `network` parameter name in the documentation.
> fix: Chronicle Transport Parameter in documentation

- .goreleaser.yml
- Makefile
- scripts/install/install_unix.sh
This PR will introduce PowerPC (ppc64 and ppc64le) Linux build and release artifacts. These have been tested on an Enterprise Linux ppc64le system.
Access for testing can be provided. The test system is running on SiteOx, and we rented it only for a month.
> feat(ppc-linux): Add PowerPC architectures for Linux OS Releases

- .goreleaser.yml
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
Instead of downloading the contrib jar using a multi-stage build, we should use the jar that was downloaded by the build script. This will prevent the container image jar version from becoming out of sync with JAVA_CONTRIB_VERSION (file in this repo).
After building with `make release-test`, Our security tool no longer identifies JAVA vulnerabilities. When I exec into the container and get the jar's checksum, it matches the checksum of the jar found in `release_deps/`.
> fix(container): Java contrib JAR version

- collector/featuregates.go
* Disable otel for internal metrics.
Right now, when we reconfigure with bindplane, it seems like old metric descriptors are not cleared when using the otel implementation for internal metrics. We need to go back to using the old OC implementation while we investigate how to get the new otel implementation working.
To test:
Create a config in bindplane with a destination using otlp (e.g. grafana)
Assign and rollout the config to the agent
Change a processor on the config and rollout the changes
run `curl localhost:8888/metrics`, observe that you don't get any errors (without this change, you will get errors about collecting multiple metrics with the same label set.)
> fix: Disable otel for internal metrics

- .github/workflows/multi_build.yml
- .github/workflows/tests.yml
* The linux build step fails due to running out of disk space, so we need a larger runner
* macos-11 is now being deprecated, bump to [macos-14](https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/)
> fix(ci): Use larger runner for linux build, use macos-14

- internal/report/snapshot/filter_logs.go
- internal/report/snapshot/filter_logs_test.go
- internal/report/snapshot/filter_metrics.go
- internal/report/snapshot/filter_metrics_test.go
- internal/report/snapshot/filter_traces.go
* The min timestamp check should be strictly greater than, not greater than or equal to
> fix(snapshotsearch): Fix mintimestamp check for filtering

- docs/opamp.md
Changed documentation to indicate `agent_id` is not required.
> Updated required fields for opamp documentation

- expr/ottl.go
* For OTTL, we should include the "StandardConverters" as our base for functions. 
I think this either originally didn't exist when we created the package, or I just missed it. Either way, we've slowly been drifting in terms of what functions are available in our processors vs what's available in docs and in the transform processor. 
This should help us keep up to date as functions are added to OTTL.
> feat(expr): use ottlfuncs.StandardConverters as base for ottl functions

- Makefile
- exporter/azureblobexporter/exporter_test.go
- internal/logging/config.go
- internal/processor/snapshotprocessor/processor_test.go
- internal/report/agent_client_test.go
- internal/service/standalone_test.go
- opamp/observiq/agent_config_manager_test.go
- opamp/observiq/observiq_client_test.go
- opamp/observiq/observiq_downloadable_file_manager_test.go
- receiver/pluginreceiver/emitter.go
- receiver/pluginreceiver/receiver_test.go
- updater/internal/rollback/rollback_test.go
Updated revive version to 1.3.7 so it' in compliance with the GitHub action.
> chore: Updated revive linter and fixed issues

- receiver/httpreceiver/logs.go
- receiver/httpreceiver/logs_test.go
We've observed a nil panic when the http receiver is shutting down, due to server being nil:
```
Failed to apply config changes: failed to reload config: collector.yaml: collector failed to restart: collector panicked with error: runtime error: invalid memory address or nil pointer dereference. Panic stacktrace: goroutine 126 [running]: runtime/debug.Stack() /opt/hostedtoolcache/go/1.20.13/x64/src/runtime/debug/stack.go:24 +0x65 github.com/observiq/bindplane-agent/collector.(*collector).Run.func1.1() /home/runner/work/bindplane-agent/bindplane-agent/collector/collector.go:146 +0x66 panic({0x69484e0, 0xd6cb140}) /opt/hostedtoolcache/go/1.20.13/x64/src/runtime/panic.go:884 +0x213 net/http.(*Server).Shutdown(0x0, {0x87d1120, 0xc000b84c30}) …
```
> fix(httpreceiver): Check if server is nil before shutting it down

- .github/workflows/codeql.yml
Codeql scanning is failing due to the go-version bump. 
Workaround from https://github.com/github/codeql-action/issues/1842 indicates we can install the go version we need before the init step to use the correct go version.
> chore: fix CodeQL scanning

- .github/workflows/manual_msi_build.yml
- .github/workflows/release.yml
Old link to the wix toolset binaries 404's now, new one does not.
> chore: Fix link to Wix toolset

- go.mod
- go.sum
Adds a replace to take in the ParseXML converter that has not been upstreamed yet.
You can see the changes here:
https://github.com/observIQ/opentelemetry-collector-contrib/compare/b16a03f946b7e26c94bf2aae11b429cd8931013f..e4593622db2abfcf19ec053157734c37d89f4744
Tested by loading a config and making sure output was parsed.
<details>
<summary>config</summary>
```yaml
receivers:
filelog:
include:
- "./tmp/test.xml"
processors:
transform:
log_statements:
- context: log
statements:
- set(attributes["parsed"], ParseXML(body))
exporters:
file:
path: "./tmp/test-ottl-xml.out.json"
logging:
verbosity: detailed
service:
telemetry:
metrics:
level: none
pipelines:
logs:
receivers: [filelog]
processors: [transform]
exporters: [logging, file]
```
</details>
<details> …
> deps: Add ParseXML OTTL converter

- processor/datapointcountprocessor/processor.go
- processor/datapointcountprocessor/processor_test.go
- processor/logcountprocessor/processor.go
- processor/logcountprocessor/processor_test.go
- processor/logdeduplicationprocessor/processor.go
- processor/logdeduplicationprocessor/processor_test.go
- processor/lookupprocessor/processor.go
- processor/lookupprocessor/processor_test.go
- processor/spancountprocessor/processor.go
- processor/spancountprocessor/processor_test.go
Fixes possible panics in the following processors if they are shutdown before starting:
- logcount processor
- datapointcount processor
- logdeduplication processor
- lookup processor
- spancount processor
> fix: Panic in shutdown of multiple processors before start

- receiver/azureblobrehydrationreceiver/README.md
- receiver/azureblobrehydrationreceiver/receiver.go
- receiver/azureblobrehydrationreceiver/receiver_test.go
After rehydration was completed the Azure Blob Rehydration receiver would continue to poll the Azure Blob API to ask for all blobs in order to see if they should be rehydrated. This would incur Blob egress charges for API calls. As this receiver is given a time window in the past it makes sense that rehydration is not a long running operation.
To stop extra calls if the receiver detects three consecutive polling cycles of no blobs rehydrated then stop attempting to rehydrate.
> fix: Additional Polling of Azure Blob Rehydration Receiver

- scripts/package/postinstall.sh
Change the postinstall script to remove the sysv file on systems that don't need it.
> fix(SLES15 systemd) Have the postinstall script remove the sysv init file if it exists on a systemd enabled system

- README.md
Updates the first paragraph to nudge users towards BindPlane OP, the primary usage of the agent.
Also removed the gosec status badge, since the workflow no longer exists, and just leaves a dead link on the README.
> chore: Update readme starting paragraph

- receiver/pluginreceiver/factory.go
- receiver/pluginreceiver/receiver.go
- receiver/pluginreceiver/receiver_test.go
* Fix potential lockup on shutdown of the plugin receiver, where it may attempt to emit an error on an unbuffered channel with no listener.
* Make a NewReceiver method that sets internal fields to the correct values (simplifies setup in tests a bit, especially with this channel that must be set up the same everywhere)
> fix(pluginreceiver): Add buffer to error channel in case shutdown causes error

- exporter/chronicleexporter/README.md
- exporter/chronicleexporter/config.go
- exporter/chronicleexporter/marshal.go
- exporter/chronicleexporter/marshal_test.go
- Add support for setting a log_type through an attribute rather than the config or automatic detection.
- Add additional validation to the config now that we're using the grpc protos.
> feat(chronicle): Add support for setting log_type through an attribute

- Makefile
* Don't skip internal modules when tagging for a release, we require these to be tagged to properly use the bindplane-agent module.
> chore: Don't skip internal modules when releasing

- internal/report/snapshot/filter_logs.go
- internal/report/snapshot/filter_traces.go
The filtered log/trace objects are guaranteed to be copies of the original and are not used after they are aggregated, so we should be able to move them for a slight performance bump over copying them.
We already do this for metrics.
> chore(snapshotsearch): Move filtered logs/traces instead of copying

- exporter/googlecloudexporter/exporter.go
The exporter sets host.name in an effort to ensure telemetry is identifiable. The presence of host.name allows the telemetry to map to `generic_node` [Monitored Resource Type](https://cloud.google.com/monitoring/api/resources#tag_generic_node).
Because k8s.pod.name is an identifiable attribute similar to host.name, we can skip setting host.name when it is present. This might help prevent metrics from mapping to generic_node when they should really be k8s_container or k8s_pod monitored resource types.
> fix(googlecloudexporter): Skip setting host.name when k8s.pod.name is present

- config/example.yaml
The default config is noisy, switched to `nop` receiver and exporter.
Disabled the agent's own metrics, this will allow the agent to install on systems with port `8888` already bound by another process. It will be BindPlane's responsibility to configure a port, 8888 or some alternative.
When deploying the agent to a new system, port 8888 is not bound when the default config is in use.
> chore: Update default config to use nop components, disable agent prometheus metrics

- Makefile
* Use `VERSION` make file var for GORELEASER_CURRENT_TAG in release-test
* This lets you set the version of the build by doing `VERSION=v1.xx.x make release-test`
* Create a dummy windows MSI if one isn't present
* This is required for checksums, but usually it's not worth going through the effort of actually getting one of these built. So a dummy one will be created if one doesn't exist
> chore: release test ease of use

- .goreleaser.yml
- docker/Dockerfile.scratch
Added a new container build based on [scratch](https://hub.docker.com/_/scratch). Scratch images are empty, containing nothing. The final image will only contain files explicitly copied into the image during the build.
This change is security motivated. Users who do not require systemd (journald receiver) and Java (jmx receiver) can decide to use this image, which has a reduced attack surface. The final image contains a single binary (agent binary), does not contain a shell or any other utilizes that an attacker would look for.
The images are tagged with `major.minor.patch-minimal`. I opted to omit `latest` and did not bother with `major` and `major.minor`. The final images are somewhat small, ~ 240MB vs ~500 for the full image.
```
observiq/bindplane-agent-arm64 …
```
> feat(container): Minimal scratch based container image

- .goreleaser.yml
- docker/Dockerfile.scratch
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
- Copy plugins from release_deps
- Copy base config from release_deps
- New: Copy VERSION.txt from release_deps
The logging config and LICENSE will continue to be copied as is. The logging config was built specifically for the container build process.
This is a follow up PR for https://github.com/observIQ/bindplane-agent/pull/1769
Tested by deploying BindPlane managed agents and updating them to use the Ubuntu based image produced by this branch.
> chore(docker): Use release_deps when copying files to container images

- docker/Dockerfile.scratch
BindPlane makes several assumptions when deploying Kubernetes agents that need to be implemented in the minimal image.
- Add uid and uid 10005 to minimal container image
- Add `/etc/otel/storage` to minimal container image (Required for some BindPlane resource types)
- Add collector home and collector storage environment variables (Required for some BindPlane resource types)
Tested against latest BindPlane SaaS with all K8s source types
- OTLP
- BindPlane Gateway
- Container Logs
- Kubelet Metrics
- Cluster Events
- Cluster Metrics
I tested:
- Current image
- Switch to ubuntu based image produced by this branch
- Switch to minimal image with produced by this branch
- Switch back to current image
No errors going between them. This includes the required changes on the BindPlane k8s …
> feat(docker): Add BindPlane support to minimal image

- .goreleaser.yml
The release process signs artifacts using [Cosign](https://github.com/sigstore/cosign). This PR extends this capability to container images and manifests. This is part of a larger effort to sign all BindPlane related artifacts.
The existing release workflow handles the placement of the private key and private key password. The public key already exists in the repo at `signature/bp_agent_key.pub` per out documentation [here](https://github.com/observIQ/bindplane-agent/blob/release/v1.57.0/docs/verify-signature.md).
Testing is only possible when building a full release. I forked the repo and built a tag against my fork. The release passed and the resulting image can be verified with Cosign.
```bash
cosign verify \
--key signature/bp_agent_key.pub \ …
```
> feat(release): Sign container images with Cosign

- go.mod
- go.sum
Removes the length limit from the component name.
You can see the diff to v0.106.x here: https://github.com/open-telemetry/opentelemetry-collector/compare/release/v0.106.x..observIQ:opentelemetry-collector:component-length-restriction-remove-v0.106.1?expand=1
Tested this against bindplane with a long-named source from saved-sources. It fails on (unreleased) v1.57.0, but works with this change.
> fix: Remove length limit from component name

- processor/throughputmeasurementprocessor/processor.go
- processor/throughputmeasurementprocessor/processor_test.go
Due to https://github.com/open-telemetry/opentelemetry-collector/pull/9759, the names for our metrics changed. Because of this, we need to add the "otelcol" prefix manually to the name.
I've ended up hardcoding the prefix we want here instead of relying on the processorhelper logic, it's important that this name stays the same between versions of the agent.
> fix: Fix throughput measurement name changes

- collector/settings.go
- receiver/pluginreceiver/rendered_config.go
* Switch default provider scheme to `env`. This means `${ENV_VAR}` is treated as an environment variable. This actually has no effect until we remove the env converter, but I wanted to make sure we don't forget to add this. This does not change any existing behavior of the collector.
> chore: use env as default provider (as is heavily recommended)

- .goreleaser.yml
- Makefile
- buildscripts/download-dependencies.sh
- docker/Dockerfile.scratch
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
- exporter/googlecloudexporter/go.mod
- exporter/googlecloudexporter/go.sum
- exporter/googlemanagedprometheusexporter/go.mod
- exporter/googlemanagedprometheusexporter/go.sum
- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
- scripts/package/postinstall.sh
- scripts/package/postremove.sh
- scripts/package/preinstall.sh
- scripts/package/preremove.sh
- service/com.observiq.collector.plist
- service/observiq-otel-collector
- service/observiq-otel-collector.service
- service/sysconfig/observiq-otel-collector
Updates linux install process to work with ocb and supervisor. Tested with debian, rhel, and ubuntu VMs. 
Linux packages now use pre and post remove scripts to manage uninstallation instead of passing `-r` to the install script. 
Also updates docker images to work as well. For docker images, a config file needs to be volume mounted. This is the command I used:
```
docker run -v ./local/docker-supervisor-config.yaml:/etc/otel/supervisor-config.yaml observiq/bindplane-agent-arm64:1.57.1-minimal
```
Notably, the config file needs to have the agent executable path set as `/collector/observiq-otel-collector`
> feat: Update Unix install script

- go.mod
- go.sum
Replaced github.com/mholt/archiver/v3 with github.com/anchore/archiver/v3 v3.5.2 to address this [CVE](https://github.com/advisories/GHSA-rhh4-rh7c-7r5v).
Replace can be removed if/when this [PR](https://github.com/mholt/archiver/pull/396) is merged. Alternatively we can remove the dependency by handling the unpack logic ourselves.
> fix: Address mholt/archiver CVE

- .goreleaser.yml
Comment out `docker_signs` section of goreleaser cfg since goreleaser v2 isn't working with cosign for some reason.
> fix: Revert goreleaser image signing

- .github/workflows/release.yml
When the release has issues, waiting 1 hour for feedback can be tedious. We have the green light to use larger runners where necessary. If the 8 core runner does not appear to be faster, we can revert this PR.
> chore(release): Use 8 core runner

- .goreleaser.yml
- Makefile
- config/logging.stdout.yaml
- config/logging.yaml
- docker/Dockerfile.scratch
- docker/Dockerfile.ubi8
- docker/Dockerfile.ubuntu
- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
Cleanup references to `logging.yaml`
> chore: Remove logging.yaml

- .github/workflows/multi_build.yml
- .github/workflows/tests.yml
Trying to speed up CI after running into issues with the release and needing to wait on CI. Unfortunately the only real bottle neck is downloading dependencies, so for a single CI run there's not much that can be done. By default, the setup-go action will cache the root go.sum but with this change we're going to also cache nested go.sum files. With some rough testing I found this does speed up CI.
These are the results of some rough testing. In general I think caching the nested go.sum files does improve CI speed but it can definitely vary and this probably isn't definitive (such as windows tests taking longer with nested caching vs just the root).
> chore: Test caching to speed up test action

- collector/featuregates.go
Disable the `confmap.strictlyTypedInput` featuregate (needs to be done before v0.110.0 of OTel).
Ran into issues while updating OTel a few releases ago but no issues disabling now. I think there was some overlap with the environment var expansion feature gate stuff that was causing this one to fail too (issue [here](https://github.com/open-telemetry/opentelemetry-collector/issues/10552) goes into more detail). Now that the env var stuff is taken care disabling this featuregate seems fine.
> chore: Disable confmap featuregate

- plugins/tomcat_logs.yaml
The Tomcat source in BindPlane has been failing to parse catalina logs for a few users. After some investigation I found that we had a bad regex for parsing. It was missing an optional subfield, and was also less efficient than it could be. This PR changes it to take account of the optional subfield while also being more efficient.
Regex 101 test here. Change the [\s\S]+ to .+ to validate the subfield parsing (that \s\S pattern captures too much in regex101, but works correctly in BP Agent)
https://regex101.com/r/s4Cuth/3
> fix(plugin): Tomcat plugin has been failing to parse catalina logs due to a bad regex

- go.mod
- go.sum
- opamp/observiq/observiq_downloadable_file_manager.go
Adds custom functions for unpacking .tar.gz and .zip packages to the updater. Doing so to remove the `mholt/archiver/v3` dependency due to this [issue](https://github.com/mholt/archiver/pull/396).
> chore: Custom .tar.gz and .zip unarchive functions

- docs/receivers.md
- factories/receivers.go
- go.mod
- go.sum
* Adds the [webhook event receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/webhookeventreceiver)
> feat: add webhook event receiver to build

- collector/featuregates.go
* Reverts feature gate for moving the `convert_sum_to_gauge` transform processor function to metric context.
> fix: Set featuregate for convert sum/gauge to false temporarily

- windows/templates/product.wxs
When installing on windows with the MSI, the collector's folder should only be accessible by administrators. Added new permission settings to the WIX file.
Addresses an issue Travis put in the triage: https://linear.app/observiq/issue/BPOP-709/agent-windows-agent-folder-restrict-permissions-to-administrator
> feat: Make Windows dir admin only

- receiver/m365receiver/logs.go
Shutdown should be calling shutdown on the storage extension. When it doesn't, the next start up fails because it cannot connect to the file extension.
> fix: Call shutdown on storage extension

- go.mod
- go.sum
Adding in a replace for `pkg/stanza` that includes Dan's fix until the [pr](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/35175) gets merged using this commit: https://github.com/observIQ/opentelemetry-collector-contrib/commit/2741093f40aa892cdcd77294a0de039f31cb95c6
> deps: Replace `pkg/stanza` with msrpc fix

- expr/ottl.go
- expr/ottl_condition.go
- expr/ottl_expression.go
- go.mod
- processor/samplingprocessor/config.go
- processor/samplingprocessor/factory.go
- processor/samplingprocessor/go.mod
- processor/samplingprocessor/go.sum
- processor/samplingprocessor/processor.go
- processor/samplingprocessor/processor_test.go
- receiver/awss3rehydrationreceiver/go.mod
- receiver/azureblobrehydrationreceiver/go.mod
Adds OTTL Metric Condition, Statement, and Expression to the expr package. Changes the sampling processor to use a metric based condition instead of datapoint based condition.
Followup to: #1877
> fix: add ottl metric condition to expr package for use in sampling processor

- collector/featuregates.go
- go.mod
- go.sum
* Allow datapoint and metric context to convert between sum and gauge
You can see the diff here: https://github.com/open-telemetry/opentelemetry-collector-contrib/compare/v0.110.0...observIQ:opentelemetry-collector-contrib:fix/v0.110.0-transform-processor-interop?expand=1
Tested with this sample config:
```yaml
receivers:
hostmetrics:
collection_interval: 60s
scrapers:
load:
metrics: null
processors:
transform:
metric_statements:
- context: metric
statements:
- convert_gauge_to_sum("cumulative", false)
- convert_sum_to_gauge()
- context: datapoint
statements:
- convert_gauge_to_sum("cumulative", false)
- convert_sum_to_gauge()
exporters:
debug:
verbosity: detailed
service:
pipelines:
logs:
receivers: [hostmetrics]
processors: [transform]
exporters: [debug]
```
Here, both contexts have the …
> feat: Allow metric conversion functions on datapoint and metric context

- buildscripts/download-dependencies.sh
Supervisor build should build the supervisor package, not the main.go. Due to a recent change where multiple go files were introduced, the supervisor build broke. This fixes that by building the package (`.`) instead of `main.go`.
> fix: Fix build for supervisor in 2.0

- windows/install/generate-manager-yaml.bat
- windows/templates/product.wxs
For GPO rollouts of MSIs, the MSI is uninstalled, then the new MSI is installed. Because the manager.yaml should be persistent between this uninstall/install flow, we need to not remove it on uninstall.
Instead, like the linux scripts, we'll keep the manager.yaml between upgrades done this way. In addition, I've added a "CLEAN" property that can be specified via the command line that will allow you to cleanly install over the manager.yaml, even if it already exists.
Testing:
I've run these steps with the prebuilt MSI here: https://github.com/observIQ/bindplane-agent/actions/runs/11331967731
1. Install using above MSI, pointing it to a BPOP instance
2. Uninstall. Note the agent is disconnected in BPOP
3. Re-install using above MSI. Note that the agent reconnects, with the same ID.
4. …
> fix: Keep manager.yaml on uninstall

- go.mod
- go.sum
There's a panic caused by us updating to v1.24.2 of the `github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/trace` package. A method was added to the interface, which this module uses, but the other module, which implements this interface, _embeds_ the interface. This means that the implementor always trivially implements the interface, even when it doesn't actually implement a method. When this unimplemented method is called, a nil panic happens because the embedded interface is always set to nil.
TL;DR v1.24.2 is incompatible with v0.111.0 of the GCP exporter, we need to use v1.24.1.
Here's a sample config I used to reproduce/test (this would panic immediately on startup):
```yaml
receivers:
telemetrygeneratorreceiver:
payloads_per_second: 1
generators:
- type: otlp …
```
> fix: Fix panic when exporting tracing to GCP

- processor/marshalprocessor/README.md
We are not aware of anyone using this processor. 
In Bindplane, we use the OTTLfuncs listed instead of this processor.
> chore(ui): Add deprecation notice to Marshal Processor

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
Add a new quiet flag that allows running this script in a non-interactive shell, including performing a prerequisite check that prevents running when interactive features are required.
> feat(install): Add quiet flag to allow use in non-interactive shells

- go.mod
- go.sum
Both of these replace statements are no longer needed so removing them here.
- `transformprocessor`: The datapoint context is now deprecated for metric conversion funcs in the transform processor, and with [this](https://github.com/observIQ/bindplane-agent/pull/1934) PR merged we no longer need this replace.
- `kafkareceiver`: The bug fix this includes is now released in OTel v0.112.0 so this replace is no longer needed.
> chore: Remove `transformprocessor` & `kafkareceiver` replaces

- .goreleaser.yml
- config/supervisor-default.yaml
- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
- windows/install/generate-supervisor-yaml.bat
- windows/templates/product.wxs
Want to be able to install and start supervisor without needing to provide an opamp endpoint or secret key. Neither are no longer required but since the supervisor needs an endpoint to actually start, use a default of `ws://localhost:3001/v1/opamp` when one isn't provided
> chore: Don't require OpAMP endpoint when installing & starting

- opamp/observiq/identity.go
- opamp/observiq/identity_test.go
Reports the encryption key stored in OTEL_AES_CREDENTIAL_PROVIDER env var to Bindplane.
> chore: Add OTEL_AES_CREDENTIAL_PROVIDER key to agent description

- opamp/config.go
- opamp/config_test.go
- opamp/observiq/observiq_client.go
In one test case of opamp/config_test.go/TestToTLS():
Since the existing comparison only compared the expected and actual Certificates on the config, `expectedConfig.RootCAs` and `expectedConfig.MinVersion` were specified but not used. The reason for this was that comparing the entirety of the expectedConfig to the actual config failed the comparison of `RootCAs`, due to the `expectedConfig.RootCAs` having been created from a different `*x509.CertPool` than the `actual.RootCAs`.
To allow for the comparison of the full expected and actual configs, the scope of the previously-local `caCertPool` variable has been broadened - it will still be re-initialized on every call to `ToTLS()`, but its value from the previous call of `ToTLS()` can be retrieved by the test. This will make …
> fix: TestToTLS to use unreferenced config attributes

- exporter/chronicleexporter/marshal_test.go
I plan to open follow up PRs for optimizing getRawField. I think we should have a couple simple tests and benchmarks in place first.
> [exporter/chronicleexporter]: Add tests and benchmarks for getRawField

- scripts/install/install_unix.sh
Flag got accidentally removed during rebase so adding it back in. Verified -r is present in macos script. Probably trigger another release afterwards.
> fix: Add `-r` flag back to unix install script

- scripts/install/install_unix.sh
Follow up pr to #1970. Noticed this install script lacks a usage blurb for the uninstall cmd. Copied same blurb over from macos script.
> chore: Add uninstall usage blurb to install_unix.sh

- receiver/splunksearchapireceiver/client.go
- receiver/splunksearchapireceiver/config.go
- receiver/splunksearchapireceiver/config_test.go
- receiver/splunksearchapireceiver/factory.go
- receiver/splunksearchapireceiver/receiver.go
Instead of passing the query from the config as-is, use the earliest and latest time config fields to specify a `starttime` and `endtime` on the created query. This will eliminate unnecessary API calls and remove a lot of the post-processing done by the receiver.
Example output:
```
{"level":"info","ts":"2024-11-14T14:34:26.854-0500","caller":"splunksearchapireceiver/receiver.go:155","msg":"creating search","kind":"receiver","name":"splunksearchapi","data_type":"logs","query":"search index=otel starttime=\"2024-11-14T00:00:00.000Z\" endtime=\"2024-11-14T20:00:00.000Z\" timeformat=\"%Y-%m-%dT%H:%M:%S\""}
{"level":"info","ts":"2024-11-14T14:34:32.094-0500","caller":"splunksearchapireceiver/receiver.go:142","msg":"search completed","kind":"receiver","name":"splunksearchapi","data_type":"logs" …
```
> feat: SSAPI pass timestamps in Splunk query (BPS-283)

- Makefile
- buildscripts/download-dependencies.sh
- Disable CGO for supervisor and agent builds
- This allows the agent to start on Ubuntu 18.04.6 LTS (Bionic Beaver)
> fix: Disable CGO for supervisor and agent builds

- exporter/chronicleexporter/marshal.go
getRawField is called three times for every log record. One of those times is for reading the "field to send" value. Generally, "field to send" will be `body`. Body can be either a string or a map. 
If `field` is body, we can read the underlying string or map and return it. No need to use an expensive OTTL expression.
Before
```
Benchmark_getRawField/String_body-32         	  522542	     21758 ns/op
Benchmark_getRawField/Empty_body-32          	  566030	     23555 ns/op
Benchmark_getRawField/Map_body-32            	  529818	     26545 ns/op
Benchmark_getRawField/Map_body_field-32      	  427791	     29865 ns/op
Benchmark_getRawField/Map_body_field_missing-32         	  477262	     26456 ns/op
Benchmark_getRawField/String_attribute-32               	  480273	     25780 ns/op …
```
> [exporter/chronicleexporter]: Optimize getRawField when field is "body"

- Makefile
Update name of default collector binary for `make kill`
```bash
$ make kill
pkill -9 opampsupervisor || true
pkill -9 collector_darwin_arm64 || true
```
> fix(dev): Name of binary for `make kill`

- internal/report/agent_client.go
- internal/report/agent_client_test.go
The AgentClient wrapper around http.Client (used to add headers to snapshot reports) didn't include a proxy setting in its Transport, so snapshots failed in environments configured with a proxy and without DNS access, specifically for Windows.
We have a proxy configured on the localnet at bp-qa-ub-proxy.bluemedora.localnet:9094
See https://observiq.com/docs/advanced-setup/configuration/proxy for setting up an agent with a proxy. The current agent will create an error when the snapshot console is opened in BP, with this PR snapshot should appear normally.
For Windows:
Using regedit, add to the `Environment` key for `observiq-otel-collector`
```
HTTP_PROXY=http://bp-qa-ub-proxy.bluemedora.localnet:9094
HTTPS_PROXYhttp://bp-qa-ub-proxy.bluemedora.localnet:9094
```
Restart the collector using …
> fix: snapshot reporting use HTTP_PROXY and HTTPS_PROXY env vars

- receiver/splunksearchapireceiver/client.go
- receiver/splunksearchapireceiver/client_test.go
- receiver/splunksearchapireceiver/config.go
- receiver/splunksearchapireceiver/config_test.go
- receiver/splunksearchapireceiver/receiver.go
Adds auth tokens as an authentication option in addition to basic auth.
> feat: SSAPI Auth Token (BPS-281)

- .github/workflows/manual_msi_build.yml
- .github/workflows/release.yml
- .goreleaser.yml
- Makefile
Set CURR_VERSION flag so that `make release-prep` provides the correct version in VERSION.txt.
> fix: Set CURR_VERSION for new v2 release-prep calls

- receiver/splunksearchapireceiver/client_test.go
- receiver/splunksearchapireceiver/integration_test.go
- receiver/splunksearchapireceiver/receiver.go
Add a new integration test to simulate a failure from the exporter that would travel back up the pipeline while blocking after calling `ConsumeLogs`.
> feat: SSAPI Exporter Integration Test (BPS-279)

- exporter/chronicleexporter/exporter.go
- exporter/chronicleexporter/exporter_test.go
- exporter/chronicleexporter/factory.go
- exporter/chronicleexporter/hostmetrics.go
This is a very small step towards #2044, includes a few renames and moves a few things around.
> chore: Minor cleanup of chronicle exporter names

- exporter/chronicleexporter/exporter.go
- exporter/chronicleexporter/exporter_test.go
- exporter/chronicleexporter/factory.go
- exporter/chronicleexporter/hostmetrics.go
Follows #2047, another step towards #2044
This PR moves everything specific to the `hostMetricsReporter` into the same place and allows the struct to be managed with start/shutdown methods that correspond roughly to a typical exporter. (This will also help if we ever want to turn this into a proper `exporter.Metrics`.) Additionally, the `hostMetricsReporter` is only instantiated and used if `CollectAgentMetrics`, whereas before it was always instantiated and used to track metrics, even if they were not sent anywhere.
> chore: Localize chronicle exporter's metrics concerns

- exporter/chronicleexporter/exporter.go
- exporter/chronicleexporter/grpc_exporter_test.go
- exporter/chronicleexporter/hostmetrics.go
- exporter/chronicleexporter/http_exporter_test.go
- exporter/chronicleexporter/util.go
Follows #2048, another step towards #2044
This PR mostly just adds tests, but a few minor changes are made to allow specific aspects of the code to be swapped out in those tests.
Regardless of protocol, a fake `tokenSource` function can be replaced, allowing us to bypass the loading of google credentials. Likewise, the endpoint is changed to point to the mock server. When using grpc, the dial opts are also changed to indicate no authentication. However, even with these changes the clients are real and actually exercised by the tests.
When using http, the exporter correctly returns a permanent error on at least some error codes. More should be done here, but it is a start and can be validated by tests.
Finally, in writing these tests, I found a few error messages which should be …
> chore: Add new tests for chronicle exporter with http and grpc servers

- README.md
This PR updates the readme to include more details about BindPlane and our mission to elevate OpenTelemetry and make it easier to adopt. This includes edits to match renaming to BDOT.
> chore: Update README (after BDOT change)

- processor/topologyprocessor/config.go
- processor/topologyprocessor/config_test.go
Validates topology processor interval parameter is at least 10 seconds
> fix: validate topology processor interval

- manifests/observIQ/README.md
- manifests/observIQ/manifest.yaml
With #2021 merged, it seemed like it missed its way into the v2 manifests. This PR adds it back so that new processor types can use it with v2 installations!
> chore: add unroll processor to v2 manifest

- receiver/splunksearchapireceiver/README.md
- receiver/splunksearchapireceiver/config.go
- receiver/splunksearchapireceiver/config_test.go
- receiver/splunksearchapireceiver/receiver.go
Removes the storage extension as a requirement. Mostly for debugging/testing purposes, should never be disabled by the user for actual use of the receiver.
> feat: Make SSAPI receiver storage optional

- windows/templates/product.wxs
- windows/wix.json
This PR replaces the hardcoded 'Users' group with a variable that gets the name of the group from the Windows system. This fixes an issue where Windows machines with other languages did not recognize the 'Users' group.
> fix: Localize `Users` group in Windows installer (BPOP-1396)

- receiver/azureblobrehydrationreceiver/receiver.go
I believe we want to block on the channel read as the doneChan gets closed when the stream is over. 
Thanks to @dpaasman00 for catching this.
> fix: dont buffer on azurerehydration receiver

- receiver/awss3rehydrationreceiver/reciever.go
- receiver/azureblobrehydrationreceiver/receiver.go
Closing the done channel in shutdown was causing the function to block and not shutdown properly. I believe this is because we are calling the ctx cancel func which is going to cause the go routine to return before it can read from the done chan.
Also acquire the lock before closing the checkpoint store.
> fix: Remove chan close in rehydration receiver shutdowns

- exporter/chronicleforwarderexporter/exporter.go
- exporter/chronicleforwarderexporter/factory.go
- exporter/chronicleforwarderexporter/factory_test.go
Call the `Dial` functions with a timeout to exit early in the case of a bad IP address. 
Uses the timeout already present in the configuration from the squashed `confignet.AddrConfig`. This way when BP starts adding this param to the exporter config it is backwards compatible
> feat: Use timeout for Dial in secops forwarder

- scripts/install/install_macos.sh
- scripts/install/install_unix.sh
- windows/install/generate-supervisor-yaml.bat
Add overrides for the default values of `config_apply_timeout` and `bootstrap_timeout` supervisor params. 30s for the config timeout incase any components have a long start up - Travis' original request for this ticket. 5s for bootstrap timeout based on my own experience testing the supervisor (default is 3s which can be a touch too fast sometimes).
> feat(v2): Add `config_apply_timeout` and `bootstrap_timeout`

- processor/topologyprocessor/go.mod
- processor/topologyprocessor/go.sum
- processor/topologyprocessor/processor.go
- processor/topologyprocessor/processor_test.go
The way headers were being read from the context previously was only compatible with gRPC requests, resulting in http gateway connections not being upserted and detected.
This change now reads the headers using the client.Info on the context, which works for both gRPC & http connections. Note: this change requires `include_metadata: true` on the exporter side for headers to be included in the client.Info, (updating default for `include_metadata` to true in [this PR](https://github.com/observIQ/bindplane-op-enterprise/pull/4265)).
> fix: fix topology processor header logic

- exporter/chronicleexporter/config.go
- exporter/chronicleexporter/hostmetrics.go
- exporter/chronicleexporter/marshal.go
- exporter/chronicleexporter/marshal_test.go
Adds a field `license_type` to the chronicle exporter and sets the CollectorID field sent to chronicle based on the license type.
> chore: set chronicle collector ID based on license type

- opamp/observiq/agent_config_manager.go
```json
{
"level":"info",
"ts":"2024-09-25T11:31:29.779-0500",
"logger":"config manager",
"caller":"observiq/agent_config_manager.go:161",
"msg":"Applying changes to config file",
"config":"collector.yaml"
}
```
This log says specifies config:"collector.yaml" - it caused confusion with a customer. In short, the ConfigMap given by OpAMP calls this config "collector.yaml", but the actual config on-disk is "config.yaml". Might want to modify this somehow to reduce confusion (e.g. change key to opamp-config or confmap-config or something to specify that it's not the on-disk config. Including the on-disk config here might also help).
In essence this PR clarifies this by updating the log message.
Here is the updated log
```json
{"level":"info","ts":"2025-02-10T11:12:57.615-0500","logger":"config …
```
> Fix: Added additional information in logging of collector rollouts

- service/bindplane-otel-collector.service
Need to use the value `control-group` for [KillMode](https://www.freedesktop.org/software/systemd/man/latest/systemd.kill.html) in the systemd service config. [Linear ticket](https://linear.app/bindplane/issue/BPOP-1678/v2-agent-runs-more-than-one-collector-sub-process).
Testing:
- Checkout this branch and run `make clean`, `make install-tools`, and `make release-test`
- Get the relevant linux package (.rpm or .deb) on to your linux machine, as well as the script at `scripts/install/install_unix.sh`
- Run the script on the linux machine with `sudo ./install_unix.sh -f <path-to-linux-pkg> ...` followed by the remaining argument flags to connect to a bindplane instance like `-e` and `-s`. Do not provide a version using `-v`
- Roll a config out to the agent
- Run `systemctl status …
> fix: Use `control-group` KillMode in systemd config

- opamp/config.go
Don't discard TLS Certificate Config if `InsecureSkipVerify` is set to `true`.
In the case where you would like to skip `server` certificate validation you don't necessarily want to skip `client` certificate validation on the `server-side`. Before this change, `client` certificates were disregarded completely and validations can't be done on the `server-side` hence it won't be possible to identify a collector connecting to your `OPAMP` server using TLS certs as a means of identification.
1. **Self Signed Certificates - Server Side** - some companies run self-signed CA's internally to allow other services within the company to verify the server side certificates, however the `clients` connecting to these `servers` don't always have the means to have TLS certificates signed by the same CA …
> feat: remove early return of TLSConfig when InsecureSkipVerify is true

- docs/receivers.md
- factories/receivers.go
- go.mod
- go.sum
Adds the upstream [s3 receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/awss3receiver). Adding this in now for a customer and after some testing we can move to deprecate our version at a later date.
> feat: Add upstream s3 rehydration receiver

- .github/workflows/release.yml
- cmd/plugindocgen/go.mod
- exporter/chronicleexporter/go.mod
- exporter/chronicleforwarderexporter/go.mod
- exporter/qradar/go.mod
- extension/bindplaneextension/go.mod
- go.mod
- internal/rehydration/go.mod
- processor/datapointcountprocessor/go.mod
- processor/logcountprocessor/go.mod
- processor/metricextractprocessor/go.mod
- processor/samplingprocessor/go.mod
- processor/snapshotprocessor/go.mod
- processor/spancountprocessor/go.mod
- processor/throughputmeasurementprocessor/go.mod
- processor/topologyprocessor/go.mod
- receiver/awss3rehydrationreceiver/go.mod
- receiver/azureblobrehydrationreceiver/go.mod
- receiver/splunksearchapireceiver/go.mod
- updater/go.mod
This PR bumps the modules to v1.71.1 and the runner for the release action to ubuntu-latest-16-cores
> chore: bump modules to v1.71.1 and bump runner

- .github/workflows/checks.yml
- .github/workflows/multi_build.yml
- .github/workflows/tests.yml
- Makefile
During release, we had to bump the size of the workflow runners to get through it after the deprecation of the old ubuntu runners we were using. This PR is changing them to a more appropriate size for regular use.
Also updates the version used by the `make agent` command to be a snapshot build if not on a tag. This also fixes a change that was accidentally committed (not a major issue, only affects the dev cycle).
> chore: Update runner sizes

- exporter/chronicleexporter/grpc_exporter.go
- exporter/chronicleexporter/hostmetrics.go
Ticker was cancelled immediately after creation in hostMetricsReporter.start()
This was a regression introduced in `v1.67.0`
> fix: Ticker bug in gRPC metrics collection

- service/observiq-otel-collector.service
We have users operating collectors w/ > 1,000 concurrent TCP connections. Increasing the limit to 65,000 to match what we do w/ Bindplane.
> chore: Set Systemd LimitNOFILE=65000

- cmd/plugindocgen/go.mod
- exporter/chronicleexporter/go.mod
- exporter/chronicleforwarderexporter/go.mod
- exporter/qradar/go.mod
- extension/bindplaneextension/go.mod
- go.mod
- go.sum
- internal/rehydration/go.mod
- processor/datapointcountprocessor/go.mod
- processor/logcountprocessor/go.mod
- processor/metricextractprocessor/go.mod
- processor/samplingprocessor/go.mod
- processor/snapshotprocessor/go.mod
- processor/spancountprocessor/go.mod
- processor/throughputmeasurementprocessor/go.mod
- receiver/awss3rehydrationreceiver/go.mod
- receiver/azureblobrehydrationreceiver/go.mod
- receiver/splunksearchapireceiver/go.mod
- updater/go.mod
Doing a patch release, so reverting the last module version bump and going to v1.73.1. 
Since only change for patch is replacing the stanza pkg, including that replace in this PR too to avoid running CI more than necessary.
> Revert "chore: Update modules to v1.74.0", bump modules to v1.73.1, replace `stanza`

- .github/workflows/checks.yml
- .github/workflows/codeql.yml
- .github/workflows/multi_build.yml
- .github/workflows/tests.yml
Dependabot PRs consume a lot of PR. We consolidate dependabot PRs into one PR during release time. Therefore, we can disable CI on dependabot PRs.
> chore(dependabot): Disable CI for dependabot

- exporter/chronicleexporter/log_grouper.go
- exporter/chronicleexporter/marshal.go
- exporter/chronicleexporter/marshal_test.go
Attempts to address the problem identified in this [slack thread](https://observiq.slack.com/archives/C03MU6RFLUD/p1742854417140459) by grouping log batches by log type, namespace and ingestion labels for gRPC API calls. Previously, we were aggregating all the ingestion lables for each batch and using the last namespace value we encounter for all the logs.
> fix: Group gRPC batches by namespace and ingestion labels

- exporter/chronicleexporter/hostmetrics.go
If the configured `service.instance.id` isn't a valid UUID, fall back to a random UUID
> fix: Fall back to random UUID if agent ID won't parse as UUID

- internal/measurements/throughput.go
- internal/measurements/throughput_test.go
- opamp/observiq/measurements.go
- opamp/observiq/measurements_test.go
- opamp/observiq/observiq_client.go
- opamp/observiq/testdata/metrics/expected-throughput-doubled.yaml
This change adds timestamps when throughput metrics are both collected and sent, and ensures that we are only sending metrics that have been collected after last transmission.  This prevents a scenario where an agent re-emits metrics after a disconnect/reconnect, causing out of order metrics to be received on the server.
> fix: prevent agent from emitting metrics that have already been emitted

- receiver/windowseventtracereceiver/internal/etw/consumer.go
- receiver/windowseventtracereceiver/receiver.go
Was missed in iniital implementation but we should be setting the observedTimestamp when we are receiving logs. 
Missed due to timestamp being emitted as unix epoch time which is fairly easy to gloss over
```json
{
"resource": {},
"scopeLogs": [
{
"scope": {},
"logRecords": [
{
"timeUnixNano": "1744746519110896200",
"observedTimeUnixNano": "1744746520271985400",
"body": {
"stringValue": "\u003cEvent\u003e\n  \u003cSystem\u003e\n    \u003cProvider Name=\"Microsoft-Windows-Kernel-File\" Guid=\"{{EDD08927-9CC4-4E65-B970-C2560FB5C289}}\"/\u003e\n    \u003cEventID\u003e15\u003c/EventID\u003e\n    \u003cVersion\u003e1\u003c/Version\u003e\n    \u003cLevel\u003e4\u003c/Level\u003e\n    \u003cTask\u003e15\u003c/Task\u003e\n    \u003cOpcode\u003e0\u003c/Opcode\u003e\n …
```
> fix: add observedTimestamp and timestamp to raw in Windows Event Trace Receiver 

- .github/workflows/manual_gcs_release_test.yml
- .github/workflows/release.yml
- .goreleaser.yml
Updates Goreleaser to publish artifacts to Google Cloud Storage in addition to Github. In the future, we will update install scripts to download from GCS instead of Github.
This PR includes a manual github workflow for ensuring the GCS auth is working. I had it run in the PR with success.
Locally, I disabled the Github release / changelog steps and ran a full release against a local tag. I can see artifacts in the bucket, in the correct directory. I have since cleaned up the folder.
> chore(release): Publish release artifacts to GCS

- receiver/awss3eventreceiver/receiver.go
The context that is passed to `Start` is not intended for long running operations such as a persistent polling mechanism.
[See documentation here.](https://github.com/open-telemetry/opentelemetry-collector/blob/b4d17f61a3871b1c69e1a14f721411c4a732a982/component/component.go#L32-L36)
> fix: Do not use Start context for long running goroutines

- opamp/config.go
- opamp/observiq/observiq_client.go
- opamp/observiq/reload_funcs.go
- opamp/observiq/reload_funcs_test.go
- opamp/observiq/topology.go
- processor/topologyprocessor/config.go
- processor/topologyprocessor/config_test.go
Re-adds the `interval` parameter to the topology processor, making it backwards compatible with bindplane < v1.90.0
Testing Notes
> fix: make topology processor backwards compatible with older bp versions

- extension/awss3eventextension/internal/worker/worker.go
- internal/aws/event/fdr.go
- internal/aws/event/fdr_test.go
- internal/aws/event/s3.go
- internal/aws/event/s3_test.go
- internal/aws/event/testdata/fdr/single-escaped.json
- internal/aws/event/testdata/s3/created_single.json
When S3 objects are in sub directories, the extension fails with this error:
> {"level":"error","ts":"2025-05-01T09:43:54.136-0400","caller":"worker/worker.go:103","msg":"download object","error":"create temp file: open /opt/observiq-otel-collector/storage/s3event/s-01JT60ZG6N8S5NCCXGRBG5GETX/jsirianni/year%3D2025/month%3D05/day%3D01/hour%3D09/minute%3D43/logs_718579873.json.gz.bptmp: no such file or directory","bucket":"jsirianni","key":"year%3D2025/month%3D05/day%3D01/hour%3D09/minute%3D43/logs_718579873.json.gz","stacktrace":"[github.com/observiq/bindplane-otel-collector/extension/awss3eventextension/internal/worker.(*Worker).ProcessMessage](http://github.com/observiq/bindplane-otel-collector/extension/awss3eventextension/internal/worker.(*Worker).ProcessMessage)\n\t/home/runner/work/bi …
> [extension/awss3eventextension]: Fix nested object handling

- exporter/chronicleexporter/grpc_exporter_test.go
- exporter/chronicleexporter/http_exporter.go
- exporter/chronicleexporter/http_exporter_test.go
The exporter will panic (HTTP only) if the json creds are malformed (like putting a 'z' in for creds)
We were missing a nil check in `Shutdown`. Added a test to validate that we error instead of panicking on shutdown in this situation.
Side note, we should really `Validate()` the JSON creds configuration field immediately in our Google destinations instead of letting it error later. 
Previous (with most recent agent):
https://github.com/user-attachments/assets/2ce8240e-a1c3-4abc-ba90-cd7c4b2494a9
This PR (replaced agent binary): 
https://github.com/user-attachments/assets/179f6740-670e-4f8d-ad42-9045d2ea73d9
> fix: Prevent panic in Chronicle HTTP exporter

- exporter/chronicleexporter/documentation.md
- exporter/chronicleexporter/grpc_exporter.go
- exporter/chronicleexporter/http_exporter.go
- exporter/chronicleexporter/internal/metadata/generated_telemetry.go
- exporter/chronicleexporter/internal/metadatatest/generated_telemetrytest.go
- exporter/chronicleexporter/internal/metadatatest/generated_telemetrytest_test.go
- exporter/chronicleexporter/metadata.yaml
- exporter/chronicleexporter/monitoring.go
Adds a request count metric to the secops exporter. This is the number of requests made to the secops API. The gRPC exporter will add the error code as an attribute.
Using Google Cloud, I can chart the error rate percentage and rate by error type (unknown, timeout, etc).
> feat(secops): Request count metric

- exporter/chronicleexporter/README.md
- exporter/chronicleexporter/config.go
- exporter/chronicleexporter/factory.go
The new secops API limit is 4 MB.
- Bindplane source PR https://github.com/observIQ/bindplane-op-enterprise/pull/5037
- Doc PR https://github.com/observIQ/observiq.com/pull/691
> fix(secops): Default Batch Request Size Limit should be 4MB

- internal/measurements/throughput_benchmark_test.go
- We need a benchmark test to check performance of [these changes to the throughput processor](https://github.com/observIQ/bindplane-otel-collector/pull/2437).
- Add new benchmark test: throughput_benchmark_test.go
- Does different volumes of logs. 
- Has some with `log.record.original`, some without. 
- Checks performance of when using AddLogs, and when not using AddLogs. (on main, should be similar. On [this branch](https://github.com/observIQ/bindplane-otel-collector/pull/2437), could be different)
> feat: add throughput measurement benchmark test

- exporter/chronicleexporter/http_exporter.go
Previously, we return no error only if we recieve a `200` from SecOps and read the response body with no error. Reading that body is only used for logging in the case of a non-200 response. We've been seeing timeouts reading that body, which cause the exporter to return a permanent error. This triggers a log that from the retry sender indicating dropped logs, which isn't the case. This change only attempts to read the response body in the case of a non-200 response.
```json
{
"level":"warn",
"ts":"2025-06-16T13:13:43.183-0500",
"caller":"chronicleexporter/http_exporter.go:171",
"msg":"Failed to read response body",
"resource":{"service.instance.id":"01952532-5de9-788d-947f-c429df213c18"},"otelcol.component.id":"chronicle/Google_SecOps_https",
"otelcol.component.kind":"exporter", …
```
> fix: Ignore error reading response body for a 200 in SecOps https exporter

- cmd/plugindocgen/go.mod
- exporter/azureloganalyticsexporter/go.mod
- exporter/chronicleexporter/go.mod
- exporter/chronicleforwarderexporter/go.mod
- exporter/qradar/go.mod
- extension/awss3eventextension/go.mod
- extension/bindplaneextension/go.mod
- go.mod
- go.sum
- internal/rehydration/go.mod
- processor/datapointcountprocessor/go.mod
- processor/logcountprocessor/go.mod
- processor/metricextractprocessor/go.mod
- processor/samplingprocessor/go.mod
- processor/snapshotprocessor/go.mod
- processor/spancountprocessor/go.mod
- processor/throughputmeasurementprocessor/go.mod
- receiver/awss3eventreceiver/go.mod
- receiver/awss3rehydrationreceiver/go.mod
- receiver/azureblobrehydrationreceiver/go.mod
- receiver/googlecloudstoragerehydrationreceiver/go.mod
- receiver/splunksearchapireceiver/go.mod
- updater/go.mod
Release prep for 1.79.1 patch.
- Bumps module versions to 1.79.1
- Replace the `go.opentelemetry.io/collector/service` to the v0.127.0 version. This is the last version before the `service.telemetry.metrics.address` field was deprecated. We want this field to be supported so we have a bit more time to implement a long term solution. To test, make the agent and start it with a config that includes that field, should see the agent start up and not fail with the error:
```
{"level":"fatal","ts":"2025-06-24T11:20:40.334-0400","caller":"collector/main.go:121","msg":"RunService returned error","error":"failed to start service: failed while starting collector: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):\n\nerror decoding …
```
> chore: v1.79.1 release prep

- receiver/awss3eventreceiver/internal/worker/worker.go
After additional testing a 50% safety margin has been performing better
> chore: Bump S3 event receiver safety margin to 50% from 80%

- exporter/chronicleexporter/config.go
- exporter/chronicleexporter/marshal.go
These fields were supposed to be removed in the v1.77.0 release, but better late than never.
> chore: Remove deprecated SecOps exporter config fields

- .goreleaser.yml
- scripts/install/install_unix.sh
- scripts/package/postinstall.sh
- scripts/package/preinstall.sh
- updater/internal/updater/testdata/observiq-otel-collector.golden
- updater/internal/updater/testdata/observiq-otel-collector.service.golden
- updater/internal/updater/updater.go
- updater/internal/updater/updater_test.go
This PR renames the Linux user `observiq-otel-collector` to `bdot`.
- Updated Goreleaser package manifest to use username `bdot`
- Updated install script to use username `bdot`
- Updated postinstall package script to use username `bdot`
- This includes updating the systemd heredoc to use group name `bdot`
- Added a migration function to the preinstall script for migrating from `observiq-otel-collector` to `bdot`, using the `usermod` command.
> chore(linuxpackage): Rename observiq-otel-collector user to bdot

- README.md
- cmd/collector/main.go
- collector/featuregates.go
- collector/featuregates_test.go
Enables run time configurable feature gates so that users can experiment with them without requiring us to provide a new release.
Can test pretty easily with the feature gate `receiver.kafkareceiver.UseFranzGo`. You can enable it no problem using the cli argument or env var, and if you try providing a bad feature gate you get an error from the collector.
> feat: Run time configurable FeatureGates

- scripts/package/postinstall.sh
When BDOT_UNPRIVILEGED is set in /etc/default/observiq-otel-collector or /etc/sysconfig/observiq-otel-collector, the package will deploy a systemd override to `10-package-customizations-username.conf`.
This PR establishes a pattern that can be used for additional overrides. The service can have many override files.
This PR will need a rebase when https://github.com/observIQ/bindplane-otel-collector/pull/2436 merges, switching to the new username.
Also, the updater does not require changes. Running without root means the updater cannot be used.
> feat(linuxpackage): Support non root install

- scripts/install/install_unix.sh
Updated the Linux install script to source the package override files and use them to determine the collector home, defaulting to `/opt/observiq-otel-collector`. This allows us to use the script to install the agent when a config override is in place. Before it would fail because the collector home was hardcoded to /opt/observiq-otel-collector.
See the Linux package's postinstall script for context. https://github.com/observIQ/bindplane-otel-collector/blob/main/scripts/package/postinstall.sh#L19-L25
Tested by building `/etc/default/observiq-otel-collector`:
```ini
BDOT_CONFIG_HOME=/opt/collector
```
And then running the script on a Linux system
```bash
sudo ./install_unix.sh \
--file observiq-otel-collector_v1.80.1-SNAPSHOT-6899ef8a-SNAPSHOT-6899ef8a_linux_amd64.rpm
```
The script …
> chore(installscript): Support BDOT_CONFIG_HOME in install script

- updater/cmd/updater/main.go
- updater/internal/path/path_darwin.go
- updater/internal/path/path_linux.go
- updater/internal/path/path_linux_test.go
- updater/internal/path/path_windows.go
- updater/internal/path/testdata/custom_install_dir.ini
- updater/internal/updater/templates.go
- updater/internal/updater/updater.go
- updater/internal/updater/updater_test.go
We support a user configured install dir. See `scripts/package/postinstall.sh`. This is a follow up change to support the user configured directory when using the updater.
Updated the updater's systemd service file template to include a `.InstallDir` variable. The value used is extracted from the installed systemd service file. This follows the pattern established when detecting the runtime `group`. 
Working great when the install dir is not configured.
I tested an install dir override by setting `BDOT_CONFIG_HOME=/opt/collector` and then building this branch with two tags:
```
observiq-otel-collector-v1.81.0-alpha.3
observiq-otel-collector-v1.81.0-alpha.4
```
The builds were identical, and allowed me to test upgrading with the new logic. We cannot upgrade from the latest release because …
> feat(updater): Support user configured systemd working directory / collector home

- scripts/install/install_unix.sh
- scripts/package/preinstall.sh
When testing `BDOT_SKIP_RUNTIME_USER_CREATION`, I found that the install would proceed even if the username was not created ahead of time. This causes failures later in the install process. Its better to fail fast with a clear error.
Now the failure is right away, and clear to the user.
```
BDOT_SKIP_RUNTIME_USER_CREATION is set to true, checking if bdot user exists
ERROR: BDOT_SKIP_RUNTIME_USER_CREATION is true but user bdot does not exist
dpkg: error processing archive /home/jsirianni/observiq-otel-collector_v1.81.0-alpha.1_linux_amd64.deb (--unpack):
```
The failure is similar on RHEL.
If I run the install script instead of installing the package directly (script with `--file` flag), the failure occurs in the script:
> fix(linuxpackage): Fail if BDOT_SKIP_RUNTIME_USER_CREATION is set and user missing

- .github/workflows/manual_multi_build.yml
- .github/workflows/release-test.yml
- .github/workflows/release.yml
- .github/workflows/tests.yml
Replaced Github large runners with namespace.so runners. I expect the release workflow to finish significantly faster. We can evaluate their macos and windows runners in the future.
The required test "unit-tests (ubuntu-latest-4-cores" will be replaced by "unit-tests (nscloud-ubuntu-24.04-systemd-amd64-4x8".
> chore: namespace.so github runners

- .github/workflows/release-test.yml
- .github/workflows/release.yml
Uploads Linux packages to our experimental Google Artifact Registry. The deb and rpm repositories are still being tested, and should be avoided by users. 
Once confirmed stable, the Linux repositories can be used by users to install and upgrade BDOT without needing to use an install script or download artifacts from Github or GCS.
> feat(release): Upload Linux packages to Google Artifact Registry

- exporter/chronicleexporter/marshal.go
- exporter/chronicleexporter/marshal_test.go
A user ran into a case where the Google Cloud Pub/Sub receiver was not correctly setting the timestamp or observed timestamp. The build-in encoding type from the receiver that has this bug is not going to be fixed because it is getting deprecated and we are recommended use the `textencoding` extension instead https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/41800. As a good temp solution that was recommended on the ticket we can add a fallback to `time.Now()` if the timestamps are not set.
There are a couple other exporters upstream that are already doing this
- Logic Monitor
- Azure Monitor
- Dataset
so this seems like a safe change to make
> feat: SecOps exporter should fall back to `time.Now()` if no timestamps are set (BPOP-3570)

- cmd/plugindocgen/go.mod
- exporter/azureloganalyticsexporter/go.mod
- exporter/chronicleexporter/go.mod
- exporter/chronicleforwarderexporter/go.mod
- exporter/qradar/go.mod
- exporter/snowflakeexporter/go.mod
- exporter/snowflakeexporter/go.sum
- extension/awss3eventextension/go.mod
- extension/bindplaneextension/go.mod
- go.mod
- go.sum
- internal/rehydration/go.mod
- processor/datapointcountprocessor/go.mod
- processor/logcountprocessor/go.mod
- processor/metricextractprocessor/go.mod
- processor/samplingprocessor/go.mod
- processor/snapshotprocessor/go.mod
- processor/spancountprocessor/go.mod
- processor/throughputmeasurementprocessor/go.mod
- receiver/awss3eventreceiver/go.mod
- receiver/awss3rehydrationreceiver/go.mod
- receiver/azureblobrehydrationreceiver/go.mod
- receiver/googlecloudstoragerehydrationreceiver/go.mod
- receiver/pluginreceiver/go.mod
- receiver/pluginreceiver/go.sum
- receiver/splunksearchapireceiver/go.mod
- updater/go.mod
Current release is panicing during QA testing due to the Snowflake update to v1.16.0 ([issue](https://github.com/snowflakedb/gosnowflake/issues/1533)). Revert back to v1.15.0 until this is fixed in a new release. Bump module versions to v1.83.1 for patch.
> fix: Snowflake v1.16.0 panic

- .goreleaser.yml
- scripts/install/install_unix.sh
- scripts/package/postinstall.sh
- scripts/package/preinstall.sh
Updated Linux package scripts and install script to support user defined username and group.
- BDOT_USER: Defaults to `bdot`
- BDOT_GROUP: Defaults to `bdot`
These options are intended to be used during first install. We do not support modifying these options after initial install.
The updater did not require changes as it already dynamically sets the Systemd group based on the group configured in the install unit file. It does not set the user, nor does it need to. We use a systemd override when running as non root, the updater does not touch this override file.
Local install and Test Kitchen are passing fine. All files that should be owned by `bdot:bdot` were verified successfully.
I configured `/etc/default/observiq-otel-collector`.
```ini
BDOT_USER=otelu
BDOT_GROUP=otelg …
```
> feat(linuxpackage): Support configurable username and group

- scripts/package/postinstall.sh
While working on this v2 PR https://github.com/observIQ/bindplane-otel-collector/pull/2652, I realized we can more safely move the new binary into place using an atomic operation.
This will prevent an edge case issue where the service could restart (due to a crash / some other issue) during a package upgrade. If the binary was deleted and `cp` has not finished, the binary could be missing.
I deployed the latest collector to my Linux test system. I then upgraded to the RPM from this branch. The binary was moved successfully without error.
> chore(package): Update Collector binary using atomic move

- scripts/install/install_unix.sh
- scripts/package/postinstall.sh
- scripts/package/preinstall.sh
- Updated unix install script to use `bdot` user and group
- Updated Linux package post install script to migrate Linux user `bindplane-otel-collector` to `bdot`
You can reference merged the V1 PR here https://github.com/observIQ/bindplane-otel-collector/pull/2436
1. Installed the latest v2 beta agent
2. Confirmed files and dirs in `/opt/bindplane-otel-collector` are owned by `bindplane-otel-collector`
```bash
ls -la /opt/bindplane-otel-collector 
total 361936
drwxr-xr-x   5 bindplane-otel-collector bindplane-otel-collector      4096 Sep 15 13:39 .
drwxr-xr-x. 13 root                     root                          4096 Sep 15 13:39 ..
-rwxr-xr-x   1 bindplane-otel-collector bindplane-otel-collector 339480760 Aug  4 11:51 bindplane-otel-collector
-rw-r--r--   1 bindplane-otel-collector …
```
> chore(v2): Rename observiq-otel-collector user to bdot

- scripts/support/create-support-bundle.ps1
In order to bring the Windows support bundle in line with the Linux one, I've added the ability to collect the golang profiles (when enabled for the agent)
> feat: Add profiles capabilities to the PowerShell support bundle script
