observIQ/bindplane-otel-collector

README.md
docs/installation-windows.md
windows/test/install.rb

* Change docs to reflect Windows install folder change that was made in #315

fix: Update Windows default install location in docs

---

Makefile
processor/resourceattributetransposerprocessor/processor_test.go

Updated linter to v1.2.0 and fixed issues in test

fix(linter): Updated linter version and fixed linter issues

---

config/google_cloud_exporter/rabbitmq/README.md
config/google_cloud_exporter/rabbitmq/config.yaml

Added RabbitMQ + Google Cloud example configuration.

Add rabbitmq example config

---

config/google_cloud_exporter/mysql/README.md
config/google_cloud_exporter/mysql/config.yaml

Add mysql example config

---

config/google_cloud_exporter/elasticsearch/README.md
config/google_cloud_exporter/elasticsearch/config.yaml

Added Elasticsearch example config for Google Cloud.

Add elasticsearch example config

---

config/google_cloud_exporter/redis/README.md
config/google_cloud_exporter/redis/config.yaml

Added redis example configuration for Google Cloud.

Add redis example config

---

config/google_cloud_exporter/elasticsearch/README.md
config/google_cloud_exporter/hostmetrics/README.md
config/google_cloud_exporter/mongodb/README.md
config/google_cloud_exporter/mysql/README.md
config/google_cloud_exporter/prometheus/README.md
config/google_cloud_exporter/rabbitmq/README.md
config/google_cloud_exporter/redis/README.md
config/google_managed_prometheus/README.md
config/google_managed_prometheus/hostmetrics/README.md
config/google_managed_prometheus/hostmetrics/config.yaml

Example config for Google's Prometheus engine.

Google Managed Prometheus + Hostmetrics example config

---

config/google_cloud_exporter/docker/README.md
config/google_cloud_exporter/docker/config.yaml

Add docker example config

---

config/google_cloud_exporter/kubernetes/README.md

Added a Kubernetes example, which links to our Kubernetes repository. This repository will contain current and future examples on how to deploy cluster, node, and side car collectors in a scalable fashion. 
The repository works well but is still a work in progress. We have some users asking about k8s right now, so I believe a link to the current implementation will be useful.

Kubernetes with Google Cloud example config

---

README.md

Added hostmetrics example to example section of README

---

config/google_cloud_exporter/cadvisor/README.md
config/google_cloud_exporter/cadvisor/config.yaml

Cadvisor is a useful when collecting host + container metrics while the collector is running as a container.

Add cadvisor example config

---

plugins/redis_logs.yaml

- Added redis log plugin. MVP Port from `stanza-plugins`

feat(plugin): Redis Log Plugin

---

plugins/elasticsearch_logs.yaml
plugins/rabbitmq_logs.yaml

- Added elasticsearch log plugin. MVP Port from `stanza-plugins`
- Updated rabbitmq_log.yaml to do expansion of `.daemon_log_paths` based on findings testing elasticsearch

feat(plugin): Elasticsearch log plugin

---

plugins/elasticsearch_logs.yaml
plugins/postgresql_logs.yaml
plugins/rabbitmq_logs.yaml
plugins/redis_logs.yaml

Added MVP PostgreSQL plugin ported from `stanza-plugins`

feat(plugin): PostgreSQL Plugin

---

config/prometheus/README.md
config/prometheus/mongodb/README.md
config/prometheus/mongodb/config.yaml
config/prometheus/mysql/README.md
config/prometheus/mysql/config.yaml
config/prometheus/redis/README.md
config/prometheus/redis/config.yaml

Added example configs for the prometheus exporter
* MySQL
* Redis
* MongoDB

feat: mysql, redis, mongodb prometheus exporter example configs

---

plugins/mysql_logs.yaml

- Added MySQL logging plugin. Ported from `stanza-plugins`
- Tested logs on mysql box.

feat(plugin): Added MySQL logging plugin

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum

Addresses the following dependabot prs:
- https://github.com/observIQ/observiq-otel-collector/pull/371

deps(dependabot): Dependabot Updates for week of 4/26/2022

---

config/google_cloud_exporter/journald_logs/README.md
docs/installation-mac.md
scripts/install/install_macos.sh

- Added a macOS installation script that wraps the brew commands and handles install, upgrade, and uninstall.
```sh
888                                        8888888 .d88888b.
888                                          888  d88P" "Y88b
888                                          888  888     888
.d88b.  88888b.  .d8888b   .d88b.  888d888 888  888  888  888     888
d88""88b 888 "88b 88K      d8P  Y8b 888P"   888  888  888  888     888
888  888 888  888 "Y8888b. 88888888 888     Y88  88P  888  888 Y8b 888
Y88..88P 888 d88P      X88 Y8b.     888      Y8bd8P   888  Y88b.Y8b88P
"Y88P"  88888P"   88888P'  "Y8888  888       Y88P  8888888 "Y888888"
Y8b
===================================================
| Checking Prerequisites
===================================================
Checking that …
```

feat(install script): macOS install script

---

plugins/nginx_logs.yaml

* Add a low flow mode for the nginx plugin
* Change request parsing for observiq format to parse into fieldnames from default format

feat(nginx): Add low-flow mode for the NGINX plugin

---

.goreleaser.yml

* Add the macOS install script as a release artifact

fix(install_script): Add macOS install script to release

---

config/google_cloud_exporter/mongodb_atlas/README.md
config/google_cloud_exporter/mongodb_atlas/config.yaml

Added example Google Cloud configuration for monitoring Mongodb Atlas.

feat: Mongodb Atlas Google Cloud example config

---

plugins/syslog_logs.yaml

* Add a syslog plugin
* Add a low-flow mode to the plugin
* Filters out debug logs
* Filters out factory_id, process_id, and priority

feat(syslog): Add a syslog plugin with a low-flow mode

---

README.md
exporter/googlecloudexporter/README.md

- Fixed spelling mistake
- Added macOS one liner to quickstart

fix(readme): Pre v0.6.0 Readme fixups

---

windows/test/install.rb

fixed plugins expected in windows cinc test

fix(release checks): Fixed expected plugins in cinc tests

---

opamp/config.go
opamp/config_test.go

Added parsing of OpAmp configuration yaml file. This is just parsing the file handed to the function and not determine if the file exists.

feat: Added OpAmp configuration parsing

---

config/google_cloud_exporter/iis/README.md
config/google_cloud_exporter/iis/config.yaml

Added example configuration using iis receiver and exporting to google cloud
* tested configuration on Windows Server 2019

feat: iis example config for google cloud exporter

---

cmd/collector/main.go

Adds a version flag to the collector. --version or shorthand -v can be used.
Will print out the version, the commit hash, and the timestamp
I did not add tests for this as it seems like it would be more pain than it is worth given the small size and it being in the main function. If someone disagrees let me know.

feat: Adds version flag to collector.

---

config/google_cloud_exporter/nginx/README.md
config/google_cloud_exporter/nginx/config.yaml

Added NGINX w/ Google Cloud Exporter example config.

feat: Google Cloud NGINX example config

---

README.md

Include disclaimer in README file that main branch is stable, but documentation may not be up to date
Include disclaimer in the main README

`fix`: Updated main README to include disclaimer

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
Makefile
windows/Makefile
windows/scripts/fetch-dependencies.sh
windows/wix.json

Adds a version file to be included in releases.

feat: Adds VERSION file

---

plugins/csv_logs.yaml

feat: Add CSV plugin

---

scripts/package/postinstall.sh

We provide stop, start, restart and show also provide `enable.

Provide enable command after install (Linux)

---

plugins/couchbase_logs.yaml

Add a logging plugin for Couchbase http_access, error, debug, babysitter, xdcr, http_access_internal, and info logs. (ported from stanza-plugins)
Tested against a running Couchbase instance to make sure access logs were parsing correctly.

feat(Couchbase): Add Couchbase logging plugin

---

config/google_cloud_exporter/README.md

The GCP exporter has new authentication options that should be included in our example configurations.

Update GCP exporter doc with latest authentication options

---

.github/workflows/manual_msi_build.yml

Add new GitHub action that can be manually triggered on any branch to build a msi
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

Adds manual msi build github action

---

.github/workflows/manual_msi_build.yml

Adds snapshot argument to goreleaser step of manual msi builder action

fix: Adds snapshot argument to goreleaser step of manual msi builder action

---

plugins/macos_logs.yaml

feat: Adds macOS plugin

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

Replaced fork of vCenter receiver for upstream version

deps: Swapped out fork of vCenter for OTel

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

Added Apache Flink Metrics Receiver

feat: Added Apache Flink Metrics Receiver

---

config/new_relic_otlp/solr/README.md
config/new_relic_otlp/solr/config.yaml
config/new_relic_otlp/zookeeper/README.md
config/new_relic_otlp/zookeeper/config.yaml

Added Apache Solr and Zookeeper example configs for New Relic.

feat: Solr and Zookeeper example configs for New Relic

---

config/prometheus/kafka/README.md
config/prometheus/kafka/config.yaml
config/prometheus/mongodb/config.yaml
config/prometheus/mysql/config.yaml
config/prometheus/redis/config.yaml

Added example config Kafka with Prometheus. Also added host detection to all prometheus configs.
Tested by scraping metrics from the Prometheus exporter
```
kafka_brokers{host_name="Josephs-MacBook-Pro.local",os_type="darwin"} 1
kafka_partition_current_offset{host_name="Josephs-MacBook-Pro.local",os_type="darwin",partition="0",topic="dev"} 69
kafka_partition_oldest_offset{host_name="Josephs-MacBook-Pro.local",os_type="darwin",partition="0",topic="dev"} 0
kafka_partition_replicas{host_name="Josephs-MacBook-Pro.local",os_type="darwin",partition="0",topic="dev"} 1
kafka_partition_replicas_in_sync{host_name="Josephs-MacBook-Pro.local",os_type="darwin",partition="0",topic="dev"} 1
kafka_topic_partitions{host_name="Josephs-MacBook-Pro.local",os_type="darwin",topic="dev"} 1
```

feat: Example config for Kafka + Prometheus

---

.github/workflows/release.yml

* Trigger installer testing in https://github.com/observIQ/otel-collector-installer-testing when a prerelease is made

feat: Trigger installer testing on prerelease

---

config/google_cloud_exporter/mongodb_atlas/README.md

Adds documentation to MongoDB Atlas readme for google exporter explaining the errors that are likely to be seen.

Adds caveat comment to MongoDB Atlas readme

---

plugins/solr_logs.yaml

* Ported Solr plugin from stanza
* Removed plugin ID
* sub filelog receiver for file input operator
* Add attributes to regex timestamp and severity

feat: Solr log plugin

---

plugins/wildfly_logs.yaml

feat: Wildfly log plugin

---

plugins/jboss_logs.yaml

* Port Jboss log parser plugin from stanza plugins

feat(Jboss): port Jboss plugin

---

.goreleaser.yml
docs/installation-linux.md
scripts/install/install_unix.sh

- Added version numbers to `deb` and `rpm` release artifacts
- Updated `install_unix.sh` script to handle these
- Updated linux documentation to mention version when running `dpkg` and `rpm` manually

feat: Versioned Linux Artifacs

---

plugins/apache_http_logs.yaml

Move instructions on changing Apache Http Log format to the description of the plugin

move instructions for observiq log format to description

---

plugins/cisco_catalyst_logs.yaml

Ported Stanza Cisco Catalyst plugin. Tested system
```yaml
receivers:
plugin:
path: './plugins/cisco_catalyst_logs.yaml'
parameters:
exporters:
logging:
service:
pipelines:
logs:
telemetry:
metrics:
level: none
```

feat: Cisco Catalyst plugin

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum
processor/resourceattributetransposerprocessor/go.mod
processor/resourceattributetransposerprocessor/go.sum
receiver/pluginreceiver/go.mod
receiver/pluginreceiver/go.sum

Contains the following dependabot prs:
- https://github.com/observIQ/observiq-otel-collector/pull/548
- https://github.com/observIQ/observiq-otel-collector/pull/547
- https://github.com/observIQ/observiq-otel-collector/pull/546
- https://github.com/observIQ/observiq-otel-collector/pull/545
- https://github.com/observIQ/observiq-otel-collector/pull/544
- https://github.com/observIQ/observiq-otel-collector/pull/543

deps: Dependabot 7/11/22

---

config/google_cloud_exporter/windows_events/README.md
config/google_cloud_exporter/windows_events/config.yaml

Google Cloud example w/ Windows Events.

feat(example config): Windows Events on Google Cloud

---

config/new_relic_otlp/mongodb/README.md
config/new_relic_otlp/mongodb/config.yaml

Added metrics and logs example config for Mongodb on New Relic.

feat(example config): Mongodb metrics and logs on New Relic

---

plugins/sql_server_logs.yaml

Added the MS SQL Server logging plugin
Sample Logs:

feat: Added MS SQL Server Logs plugin

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

added aerospikereceiver to collector

deps: added aerospikereceiver to collector

---

.github/dependabot.yml
exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum

Contains the following dependabot PRs:
- https://github.com/observIQ/observiq-otel-collector/pull/585

deps: Dependabot 07 25 2022

---

updater/cmd/updater/main.go

Was using the wrong constant for the package name in the updater. Tested this fix in a live update and worked.

fix: Fixed name of package updater looks at

---

updater/internal/action/service_action.go
updater/internal/service/service_windows.go

* Pass install dir into service struct on windows

fix: Pass install dir into service

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

Added SAP Hana metrics receiver.

feat(component): Add SAP Hana receiver

---

plugins/common_event_format_logs.yaml

Ported CEF plugin over from Stanza project.
example logs
```
Aug 02 15:25:11 localhost CEF:0|nxlog.org|nxlog|2.7.1243|Executable Code was Detected|Advanced exploit detected|9|src=192.168.255.110 spt=46117 dst=172.25.212.204 dpt=80
Aug 02 15:25:08 <local0.info> 10.217.31.247 CEF:0|Citrix|NetScaler|NS10.0|APPFW|APPFW_STARTURL|8|src=10.217.253.78 spt=53743 method=GET request=http://vpx247.example.net/FFC/login.html msg=Disallow Illegal URL. cn1=233 cn2=205 cs1=profile1 cs2=PPE0 cs3=AjSZM26h2M+xL809pON6C8joebUA000 cs4=ALERT cs5=2012 act=blocked
Aug 02 15:25:10 zurich CEF:0|security|threatmanager|1.0|100|worm successfully stopped|5|src=10.0.0.1 dst=2.1.2.2 spt=1232 
Aug 02 15:25:10 zurich CEF:0|security|threatmanager|1.0|100|worm successfully stopped|3|src=10.0.0.1 dst=2.1.2.2 spt=1232 
``` …

feat(plugin): common event format logs

---

opamp/observiq/observiq_client.go
opamp/observiq/observiq_client_test.go

Added more logging around updater process in collector.
Fixed version mismatch while installing not having a package status error message

Added better logging/messaging around collector package updating

---

.github/workflows/release.yml

- Add a repository dispatch trigger to release workflow of the collector repo
- Triggers workflow of amplify repo
- Passes in version info to auto update collector
- Can not be tested until merged

feat: Added a repository dispatch trigger

---

go.mod
updater/go.mod

Updated internal modules to next release number

Updated internal mod links for new version

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

feat: Added Splunk HEC Receiver

---

.github/workflows/gosec.yml
.github/workflows/multi_build.yml
.github/workflows/tests.yml
Makefile
cmd/collector/main.go
collector/collector.go
exporter/googlecloudexporter/factory.go
exporter/googlecloudexporter/go.mod
factories/factories.go
go.mod
internal/logging/config.go
internal/service/managed.go
internal/version/version.go
packagestate/go.mod
processor/resourceattributetransposerprocessor/config.go
processor/resourceattributetransposerprocessor/go.mod
receiver/pluginreceiver/go.mod
updater/cmd/updater/main.go
updater/go.mod
updater/internal/action/action.go
updater/internal/file/file.go
updater/internal/install/install.go
updater/internal/logging/logging_others.go
updater/internal/path/path.go
updater/internal/rollback/rollback.go
updater/internal/service/service.go
updater/internal/updater/updater.go
updater/internal/version/version.go

- Updated to go.mod files to use Go 1.18
- Updated CI to use Go 1.18
**NOTE**: Did not make a Go workspace as it doesn't seem like it's a good fit for the use case or a large benefit for this repo.

feat: Updated to Go 1.18

---

Makefile
plugins/kubelet_logs.yaml
plugins/syslog_logs.yaml

Fixed the make command for misspell to error on misspellings

Fixed misspell make command to return and error

---

opamp/observiq/observiq_client.go
opamp/observiq/observiq_client_test.go

Refactored a bunch of stuff in the observiq client regarding Update functionality. None of this is big architectural refactoring (not implementing some system where we can easily handle installation of multiple types of packages). Most of this is just to make it easier to read/understand. Fixes a few small issues along the way.
I still need to manually test this, but I don't expect any issues.

Refactored Package Installed related functions in observiq_client

---

updater/README.md

* Enhance the Updater readme with a high-level description of the update process
I tried to just hit the overall bullet points of how this process works. I tried not to get too tangled up in all the failure scenarios, all though I do try to mention some when I think they are pertinent.

feat(updater): Enhance README with description of update process 

---

cmd/collector/main_test.go
internal/logging/config_test.go

- Changed all instances of os.setenv to t.setenv

feat: Changed all instances of os.setenv to t.setenv

---

go.mod
updater/go.mod

Updated internal submodules for 1.7.0 release

Updated internal submodule versions for 1.7.0 release

---

plugins/file_logs.yaml

Exposed the `include_file_path` and `include_file_name` parameters of the filelogreceiver to the file logs plugin.
Example config:
```yaml
receivers:
plugin:
path: ./plugins/file_logs.yaml
parameters:
file_path: [./test.log]
parse_format: json
include_file_path: true
include_file_name: false
exporters:
logging:
service:
pipelines:
logs:
```
<details>
<summary>Output With Log File Path Set and Log File Name Unset </summary>
```
LogRecord #98
ObservedTimestamp: 2022-09-01 18:23:43.710957 +0000 UTC
Severity:
Body: {\"host\":\"241.220.115.27\", \"user-identifier\":\"-\", \"datetime\":\"01/Sep/2022:14:23:43 -0400\", \"method\": \"DELETE\", \"request\": \"/target/grow\", \"protocol\":\"HTTP/1.1\", …
```

feat(plugins): Expose `include_file_name` and `include_file_path` in `file_logs` plugin

---

plugins/kubelet_logs.yaml

Altered Kubelet plugin to parse to body rather than attributes
Example of payload sent to GCP:

feat(plugin): Kubelet logs plugin body parse

---

docs/plugins/oracledb_metrics.md

Added documentation for OracleDB Plugin.
We will have to add more extensive documentation to all other plugins and link them to the main readme at some point. This is the first as it is needed by the Field team for customer engagement.

OracleDB Plugin Doc

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

Adds the AWS Cloudwatch Receiver

feat: Adds the AWS Cloudwatch receiver

---

go.mod
updater/go.mod

Changes collector dependency version to 1.10.0

deps: Changes collector dependency version to 1.10.0

---

Makefile

Removed the `release` make target as it's confusing and unused.

Removed unused release make target

---

.github/workflows/check_plugin_docs.yml

Enables check plugin documentation action on PR

Enables check plugin docs action on PRs

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

deps: Adds SNMP Receiver

---

collector/collector.go

I booted up the collector in standalone mode, and got this error:
```
{"level":"error","ts":"2022-11-03T01:11:12.776-0400","caller":"service/collector.go:194","msg":"Asynchronous error received, terminating process","error":"listen tcp :8888: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.","stacktrace":"go.opentelemetry.io/collector/service.(*Collector).Run\n\tC:/Users/brandon/go/pkg/mod/go.opentelemetry.io/collector@v0.63.1/service/collector.go:194\ngithub.com/observiq/observiq-otel-collector/collector.(*collector).Run.func1\n\tD:/projects/observiq-otel-collector/collector/collector.go:108"}
{"level":"info","ts":"2022-11-03T01:11:12.776-0400","caller":"service/service.go:115","msg":"Starting shutdown..."} …
```

fix: Fix asynchronous error causing zombie collector

---

internal/report/snapshot_reporter.go

Fixed a possible race condition panic that could occur by concurrent accesses of the snapshot buffer maps during a reconfiguring.

fix: Snapshot Race Condition Panic on Config Reload

---

docs/exporters.md
factories/exporters.go
go.mod
go.sum

Added the [Dynatrace Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.63.0/exporter/dynatraceexporter)

deps: Added Dynatrace Exporter

---

cmd/plugindocgen/go.mod
go.mod
updater/go.mod

Prep for v1.11.1 release by updating submodule versions.

Updated submodule versions to 1.11.1

---

docs/installation-mac.md
scripts/install/install_macos.sh
service/com.observiq.collector.plist

Added a log file for stderr output to plist file on macOS. This is so if the collector panics it will be recorded somewhere.

Added error logs to macOS process and updated documentation

---

docs/plugins/mongodb_logs.md
plugins/mongodb_logs.yaml

Added a parse_to parameter to mongodb log plugin to allow choosing where to parse logs to body or attributes.
Not sure if MongoDB and MongoDB logs are required, so put them in.
Mongodb parse to body
```
LogRecord #0
ObservedTimestamp: 2022-11-14 21:33:47.142473 +0000 UTC
Timestamp: 2019-02-06 14:22:27.347 +0000 UTC
SeverityText: I
Body: Map({\"component\":\"CONTROL\",\"context\":\"initandlisten\",\"message\":\"db version v3.6.2\",\"severity\":\"I\",\"timestamp\":\"2019-02-06T09:22:27.347-0500\"})
Attributes:
-> log.file.name: Str(mongodb.log)
-> log_type: Str(mongodb)
Trace ID: 
Span ID: 
Flags: 0
```
mongodb parse to attributes
```
LogRecord #0
ObservedTimestamp: 2022-11-14 21:34:32.337217 +0000 UTC
Timestamp: 2019-02-06 14:22:27.347 +0000 UTC …
```

feat: Add parse_to parameter to MongoDB

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum

Includes the following dependabot PRs:
- https://github.com/observIQ/observiq-otel-collector/pull/763
- https://github.com/observIQ/observiq-otel-collector/pull/783

deps: Dependabot 11 16 22

---

.github/workflows/check-formatting.yml
.github/workflows/check-license.yml
.github/workflows/check_plugin_docs.yml
.github/workflows/gosec.yml
.github/workflows/lint.yml
.github/workflows/manual_msi_build.yml
.github/workflows/misspell.yml
.github/workflows/multi_build.yml
.github/workflows/release.yml
.github/workflows/tests.yml

Updated several actions to newer versions that are using Node 16.

Update GitHub Actions to latest versions

---

docs/plugins/hbase_logs.md
plugins/hbase_logs.yaml

Added the `timezone` parameter to the HBase Plugin

feat: Added timezone to HBase plugin

---

docs/plugins/zookeeper_logs.md
plugins/zookeeper_logs.yaml

Adds the `timezone` parameter to the Apache Zookeeper plugin

feat: Added timezone to Zookeeper plugin

---

docs/exporters.md
factories/exporters.go
go.mod
go.sum
license.yaml

Added the [Coralogix Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/coralogixexporter)

feat: Added Coralogix exporter

---

cmd/plugindocgen/go.mod
go.mod
updater/go.mod

Updated submodule references to 1.13.0

Updated submodules references to 1.13.0

---

.github/workflows/release.yml

Fixed typo for version on docker/login-action

Fixed incorrect version syntax on docker login action

---

processor/samplingprocessor/README.md

This is in effort trying to standardize how we do documentation for components. I tried to follow the guidelines as closely as possible, but let me know if there are any improvements or conciseness we can do since its a relatively simple processor.

Improve `samplingprocessor` Documentation

---

collector/collector.go

Adds collector panic stacktrace to logs

feat: Adds collector panic stacktrace to logs

---

Makefile
docs/releasing.md

Added a `make release` task that first tags the main module and pushes in order to kick off the release. Then tags all submodules and pushes those tags.

Added make release task

---

processor/resourceattributetransposerprocessor/README.md

- Rework README of resource attribute transposer processor to fit new standards
- Add "How it works" section
- Add min collector version
- Format supported pipelines like in other docs
- Show config options in table with value types
- Add full example instead of snippet

docs: Rework README of resource attribute transposer processor to fit new standards

---

docs/exporters.md
docs/extensions.md
docs/processors.md
docs/receivers.md

Small typo fixes and fixing links to the [otlpexporter](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.67.0/exporter/otlpexporter/README.md) and the [otlphttpexporter](https://github.com/open-telemetry/opentelemetry-collector/blob/v0.67.0/exporter/otlphttpexporter/README.md)

fix docs links && typos

---

docs/exporters.md

An update to the logging exporter doc link.

Updated link for logging exporter docs

---

.github/dependabot.yml
exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum

Address the following dependabot PRs:
- https://github.com/observIQ/observiq-otel-collector/pull/870

deps: Dependabot 1 6 2023

---

processor/throughputmeasurementprocessor/README.md

Updated documentation for throughput measurement processor to meet new documentation standards.

Updated documentation for throughputmeasurement processor

---

receiver/sapnetweaverreceiver/README.md

Update SAP Netweaver example configuration.
- Add a tls example configuration that uses port 401
- add googlecloud project name to prevent permission error w/ google

Update SAP Netweaver example configuration

---

cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
updater/go.mod

Updated submodule references to v1.17.0

Updated submodule version in go.mod to v1.17.0

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum
internal/expr/go.mod
internal/expr/go.sum
processor/logcountprocessor/go.mod
processor/logcountprocessor/go.sum
processor/metricextractprocessor/go.mod
processor/metricextractprocessor/go.sum

Addresses the following dependabot PRs:
- https://github.com/observIQ/observiq-otel-collector/pull/898
- https://github.com/observIQ/observiq-otel-collector/pull/900
- https://github.com/observIQ/observiq-otel-collector/pull/901

deps: Dependabot 2-9-23

---

cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
updater/go.mod

Updated submodule versions to 1.18.0 in preparation for release.

Updated submodule versions to v1.18.0

---

.github/CODEOWNERS

Changed code owner to observIQ/platform team

Changed codeowner team to platform team

---

cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
updater/go.mod

Updated submodule references to v1.19.0 in preparation for release

Updated submodule references to v1.19.0

---

.github/workflows/release.yml

Increased size of GitHub runner that does release.

Updated release process to use larger runner

---

Makefile

deps(tools): Alphabetize tools, upgrade to match bindplane-op

---

cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
updater/go.mod

Updated submodules to v1.20.0 for release prep

chore: Update submodules to v1.20.0 

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml
Makefile

Updated goreleaser to [v1.16.1](https://github.com/goreleaser/goreleaser/releases/tag/v1.16.1)

tools: Updated goreleaser to 1.16.1

---

cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
updater/go.mod

Update the submodules to v1.21.0 in preparation for release.

chore: Updated submodule version to 1.21.0

---

docs/extensions.md
factories/extensions.go
go.mod
go.sum

Added the [basicauthextension](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/basicauthextension/README.md)

feat: Added the basicauth extension

---

cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
updater/go.mod

Updated submodules to `v1.21.1` in prep for release

chore: Updated submodule versions to v1.21.1

---

cmd/plugindocgen/go.mod
docs/extensions.md
factories/extensions.go
go.mod
go.sum
plugins/w3c_logs.yaml
processor/logcountprocessor/go.mod
processor/maskprocessor/config.go
processor/maskprocessor/config_test.go
processor/maskprocessor/factory.go
processor/maskprocessor/factory_test.go
processor/maskprocessor/processor.go
processor/maskprocessor/processor_test.go
processor/metricextractprocessor/go.mod
updater/go.mod

Release prep for release/v1.21.1

Release Branch release/v1.21.1 into main

---

Makefile
cmd/plugindocgen/go.mod
go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
scripts/update-module-version.sh
updater/go.mod

* Updates submodule versions to v1.22.0 for release
* Add script and make command to help automate this

chore: Update submodule versions to v1.22.0

---

processor/datapointcountprocessor/processor.go

Because the datapointcount processor is for a metrics pipeline, it can ALSO be configured in the routed-to pipeline. This means that when routing, the datapointcount processor's ProcessMetric function could be called, causing the processor to deadlock.
Configuring like this is still not good, because it causes a loop, but it's limited by the configured interval, so it isn't an exponential loop, and re-configuring is possible with this fix (before, the component would not be able to shut down).

fix(datapointcountprocessor): Avoid deadlocking if re-entering the datapointcountprocessor

---

processor/maskprocessor/README.md
processor/maskprocessor/processor.go

Added ipv4 masking as a default for the mask processor

feat: Added ipv4 masking as a default option to the mask processor

---

cmd/plugindocgen/go.mod
go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/spancountprocessor/go.mod
updater/go.mod

* Bump module versions in prep for release v1.23.0

chore: Bump modules to v1.23.0

---

cmd/plugindocgen/go.mod
go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/spancountprocessor/go.mod
updater/go.mod

- Updated the submodule version to v1.24.0  in preparation for release.

chore: Updated submodule version to v1.24.0

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum

Addresses the following dependabot PRs:
- https://github.com/observIQ/observiq-otel-collector/pull/1044

deps(dependabot): Dependabot Updates for v1.24.0

---

Makefile
receiver/sapnetweaverreceiver/metadata.yaml

Updated the mdatagen tool to v0.76.3 and fixed any errors with that

deps: Updated mdatagen tool to v0.76.3 and fix discrepancies

---

docs/exporters.md
factories/exporters.go
go.mod
go.sum

- Add `awss3exporter` to list of exporters [README.md](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.76.3/exporter/awss3exporter/README.md)
- Add `awss3exporter` to docs

feat(exporters): Include awss3exporter from otel-contrib

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml

Updated all instances of the Goreleaser action to use our Goreleaser Pro license.

feat(release): Goreleaser Pro

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml
Makefile

deps: Match bindplane-op tool versions

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum

Addressed the following dependabot PRs:
- https://github.com/observIQ/observiq-otel-collector/pull/1125
Addressed the following dependabot security alerts:
- https://github.com/observIQ/observiq-otel-collector/security/dependabot/62
- https://github.com/observIQ/observiq-otel-collector/security/dependabot/61

deps: Addressed Dependabot 6-26-23

---

README.md
docs/connectors.md
factories/connectors.go
factories/factories.go
factories/factories_test.go
go.mod
go.sum
scripts/update-docs.sh

Added the following connectors to the collector:
- [forwardconnector](https://github.com/open-telemetry/opentelemetry-collector/tree/main/connector/forwardconnector)
- [countconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/countconnector)
- [servicegraphconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/servicegraphconnector)
- [spanmetricsconnector](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector)
Resolves #1137

feat: Added OTel Connectors

---

go.mod
go.sum

Updated filelog receiver with fix in open-telemetry/opentelemetry-collector-contrib#24070

fix: Updated filelog Receiver with fixes for filegrouping

---

collector/settings_test.go
go.mod
go.sum

- Update stanza dependency to actually pull in the fix to timestamp parsing in file log sort.

fix: Update stanza dependency

---

collector/settings_test.go
go.mod
go.sum

fix: Update stanza to pull in filelog bug fix

---

collector/settings_test.go
go.mod
go.sum

Release v1.29.1

---

receiver/pluginreceiver/factory.go
receiver/pluginreceiver/receiver.go
receiver/pluginreceiver/receiver_test.go
receiver/pluginreceiver/service.go

Wait for the collector's Run function to return before considering shutdown complete

Wait for collector to properly shut down in plugin receiver

---

cmd/plugindocgen/go.mod
collector/collector.go
factories/factories.go
go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/spancountprocessor/go.mod
updater/go.mod

Patch Release v1.35.1

---

processor/logdeduplicationprocessor/processor_test.go

Fixed a flaky test that would usually fail on Windows CI runs.

fix: Flaky Log DeDup Test

---

docs/exporters.md
factories/exporters.go
go.mod
go.sum

Added the [Sumo Logic Exporter](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/v0.86.0/exporter/sumologicexporter)

feat: Add Sumo Logic exporter

---

exporter/googlecloudexporter/go.mod
exporter/googlecloudexporter/go.sum
go.mod
go.sum
receiver/m365receiver/go.mod
receiver/m365receiver/go.sum

Contains the following dependabot changes:
* https://github.com/observIQ/bindplane-agent/pull/1290
* https://github.com/observIQ/bindplane-agent/pull/1292

deps: Dependabot 10-30-2023

---

docs/extensions.md
factories/extensions.go
go.mod
go.sum

Added [sigv4 authenticator extension](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.88.0/extension/sigv4authextension/README.md)

feat: Added the sigv4authextension

---

cmd/plugindocgen/go.mod
docs/extensions.md
factories/extensions.go
go.mod
go.sum
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/spancountprocessor/go.mod
updater/go.mod

Release v1.39.1

---

exporter/chronicleexporter/exporter.go

- Add check for empty file
- Use the right config field for creds.

fix: Chronicle creds

---

exporter/chronicleexporter/README.md

- Add additional documentation to chronicle about credentials

fix: Chronicle creds docs

---

exporter/chronicleexporter/README.md
exporter/chronicleexporter/config.go
exporter/chronicleexporter/config_test.go
exporter/chronicleexporter/exporter.go
exporter/chronicleexporter/exporter_test.go
exporter/chronicleexporter/factory.go
exporter/chronicleexporter/factory_test.go

- Remove regional endpoints and replace them with just an endpoint field. 
- link out to the endpoints in the creds section.

fix: Replace region with endpoint

---

docs/opamp.md
internal/processor/snapshotprocessor/README.md
updater/README.md

Updated documentation references to the OSS BPOP repo with ones to the product landing page.

chore: Updated references to BPOP OSS repo with ones to the product website

---

exporter/chronicleexporter/README.md

- There seemed to be confusion around what version of the ingestion API was supported, added a disclaimer to the doc to clarify.

chore: Add disclaimer to Chronicle exporter doc

---

exporter/chronicleexporter/README.md
exporter/chronicleexporter/config.go
exporter/chronicleexporter/config_test.go
exporter/chronicleexporter/exporter.go
exporter/chronicleexporter/factory.go
exporter/chronicleexporter/factory_test.go

- Add gzip compression support to chronicle

feat: Add gzip compression to Chronicle Exporter

---

go.mod

Forgot to run `make tidy` after updating submods

fix: Run make tidy

---

exporter/chronicleforwarderexporter/README.md

- Fix Chronicle forwarder's syslog example in the docs and explain `raw_log_field` more thoroughly.

fix: Chronicle Forwarder Syslog Example & Explain `raw_log_field` 

---

docs/extensions.md
factories/extensions.go
go.mod
go.sum

* Adds the oatuh2clientextension to the agent

feat: Add oauth2client extension

---

exporter/chronicleexporter/README.md

Chronicle Add Supported Log Types to Docs

chore: Chronicle Add Supported Log Types to Docs

---

internal/report/snapshot_reporter.go

* Adds the `SearchQuery` and `MinimumTimestamp` fields to the snapshot config for snapshot search

feat(snapshotsearch): Add search and minimum timestamp to snapshot report payload

---

go.mod
go.sum
internal/report/snapshot/filter.go
internal/report/snapshot/filter_logs.go
internal/report/snapshot/filter_logs_test.go
internal/report/snapshot/filter_test.go
internal/report/snapshot/snapshot_buffers.go
internal/report/snapshot/snapshot_buffers_test.go
internal/report/snapshot/testdata/logs/after/filters-get-timestamp.yaml
internal/report/snapshot/testdata/logs/after/filters-get.yaml
internal/report/snapshot/testdata/logs/after/matches-attribute-key.yaml
internal/report/snapshot/testdata/logs/after/matches-attribute-value.yaml
internal/report/snapshot/testdata/logs/after/matches-body.yaml
internal/report/snapshot/testdata/logs/after/matches-resource.yaml
internal/report/snapshot/testdata/logs/after/matches-string-body.yaml
internal/report/snapshot/testdata/logs/after/no-filters.yaml
internal/report/snapshot/testdata/logs/before/w3c-logs.yaml
internal/report/snapshot_reporter.go

* Add logic for filtering the logs payload before sending the report to bindplane.
* Add error check when prepping request payload
Tested (mostly) with unit tests. I plan on testing more extensively the e2e once we have all the pieces in place.
I have tested against current bindplane to ensure this change doesn't do anything unexpected with recent telemetry, everything on that front is working.

feat(snapshotsearch): Filter logs

---

internal/report/snapshot/filter_metrics.go
internal/report/snapshot/filter_metrics_test.go
internal/report/snapshot/snapshot_buffers.go
internal/report/snapshot/snapshot_buffers_test.go
internal/report/snapshot/testdata/metrics/after/filters-timestamp.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-key-exp-histogram.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-key-gauge.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-key-histogram.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-key-sum.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-key-summary.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-val-exp-histogram.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-val-gauge.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-val-histogram.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-val-sum.yaml
internal/report/snapshot/testdata/metrics/after/matches-attr-val-summary.yaml
internal/report/snapshot/testdata/metrics/after/matches-metric-name.yaml
internal/report/snapshot/testdata/metrics/after/matches-resource-attr-key.yaml
internal/report/snapshot/testdata/metrics/after/matches-resource-attr-val.yaml
internal/report/snapshot/testdata/metrics/before/exp-histogram.yaml
internal/report/snapshot/testdata/metrics/before/histogram.yaml
internal/report/snapshot/testdata/metrics/before/host-metrics.yaml
internal/report/snapshot/testdata/metrics/before/summary.yaml
internal/report/snapshot_reporter.go

* Adds the ability to filter metrics to snapshots

feat(snapshotsearch): Filter metrics

---

cmd/plugindocgen/go.mod
collector/featuregates.go
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/spancountprocessor/go.mod
updater/go.mod

Release v1.43.1

---

.github/workflows/checks.yml

Updates "pr_checks" workflow to run `make lint` in lint job

chore: Update lint job in "pr_checks" workflow

---

opamp/observiq/updater_manager_others_test.go

TestStartAndMonitorUpdater is starting to fail constantly (although no code this is testing has changed), trying to fix the flakes with this PR.

chore: Fix flaky test TestStartAndMonitorUpdater

---

exporter/chronicleexporter/README.md
exporter/chronicleexporter/config.go
exporter/chronicleexporter/exporter.go
exporter/chronicleexporter/marshal.go
exporter/chronicleexporter/marshal_test.go

- Added ingestion labels support
- Added Additional debug logging

feat(chronicle): Add ingestion labels support

---

.github/workflows/release.yml
.goreleaser.yml

Added signing to the MSI and artifact bundle during the release process

chore: Sign MSI and Artifact Bundle

---

.github/workflows/release.yml
.goreleaser.yml

fix: Fix signing of msi release artifact

---

.goreleaser.yml

Changed back logic to upload MSI

fix: Reverted MSI upload

---

.github/dependabot.yml

Update dependabot to post updates for tools

chore: Update dependabot with tools folder

---

manifests/README.md

Add a bit more detail for building with OCB using a custom manifest. Should address this ticket: https://linear.app/observiq/issue/BPOP-74/document-building-a-custom-distribution-of-bindplane-agent-20

chore: OCB doc update

---

scripts/install/install_macos.sh
service/com.observiq.collector.plist

Updates MacOS install script and service file to run with opamp supervisor
To test, run `make release-test` and then run `/scripts/install/install_macos.sh -f /path/to/darwin/tarball ...` with the rest of the arguments like endpoint and secret key (i just copied these from the cmd in the BP UI). 
You should see the agent is connected.
A couple notes:
- the agent log has a lot of errors about not being able to connect to the opamp server, but rolling out a config to the agent works fine and fixes it... not sure why this happens yet

feat: Updated MacOS install script

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml
.goreleaser.yml

Upgrading was simple, needed to remove `skip: false` from `changelog`.

chore(tooling): Upgrade to Goreleaser v2

---

SECURITY.md

Modeled after https://github.com/open-telemetry/opentelemetry-collector-contrib/security.
Intended to be generic, will be used on all of our public repositories.

chore(policy): Security Vulnerability reporting

---

.github/workflows/release.yml

Bumping this version of goreleaser got missed, quick update to get release running

fix: Bump goreleaser version for windows release action

---

factories/connectors.go
go.mod
go.sum

* Adds the upstream routing connector to the agent

feat: Add routing connector

---

exporter/chronicleexporter/exporter.go
exporter/chronicleexporter/exporter_test.go

We've been seeing some issues with customers getting an Invalid Argument response from secops, which ends up re-queuing and retrying a failing payload over and over again. Instead, we should mark the payload as a permanent error, since those payloads will always fail.

fix(secops): mark non-transient errors as permanent

---

.github/workflows/multi_build.yml
.github/workflows/release.yml
Makefile

Preparing for v2, update release workflow with necessary steps

fix: Polish release workflow

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml

Update go-msi action version to v2.3.0: https://github.com/observIQ/go-msi/releases/tag/v2.3.0

deps: Update go-msi

---

.goreleaser.yml
license.yaml

Commenting out docker related goreleaser steps to avoid versioning conflicts while in prerelease

chore: Remove docker related steps from goreleaser

---

receiver/telemetrygeneratorreceiver/logs_generator.go
receiver/telemetrygeneratorreceiver/logs_generator_test.go

I noticed we were setting timestamp but not observed timestamp.

[receiver/telemetrygeneratorreceiver] Set log record observed timestamp

---

factories/exporters.go
go.mod
go.sum

* Adds the debug exporter, which is the replacement for the logging exporter.
The logging exporter will be removed soon, so we'll have to use the debug exporter instead.

feat: add debug exporter

---

.goreleaser.yml

* Adds some temporary dockers/manifests to goreleaser file to test release docker images.

feat: Agent 2.0 prerelease container images

---

manifests/observIQ/manifest.yaml

Missed updating httpprovider version to the stable version during rebase

deps: Mark httpprovider stable version

---

manifests/minimal/manifest.yaml
manifests/observIQ/manifest.yaml

Update manifests:
- remove tencent exporter from bindplane manifest
- list out all providers in minimal manifest

fix: Update manifests to work at runtime

---

scripts/install/install_unix.sh

Add the status sub-commands to the install script command reference output

feat(installer): Update the install script to add the missing status arguments

---

README.md
docs/getting-started.md
docs/installation-linux.md
docs/installation-mac.md
docs/installation-windows.md
docs/supervisor.md

Updates repo documentation to be supervisor/v2 oriented.

chore: Update documentation

---

.github/CODEOWNERS

chore: Remove Brandon as codeowner

---

docs/processors.md
factories/processors.go
go.mod
go.sum

Adds the interval processor to the list of processors available in the BindPlane Agent.

feat: Add `intervalprocessor`

---

scripts/install/install_macos.sh
scripts/install/install_unix.sh
windows/install/generate-supervisor-yaml.bat

Configure default supervisor config with some logging options
- Info level logging
- Log to a file at `supervisor_storage/supervisor.log`

feat: Use configurable supervisor logging

---

exporter/chronicleexporter/marshal.go
exporter/chronicleexporter/marshal_test.go

- Added functionality in exporter/chronicle/marshal.go to https functions to get variables from attributes
- Add new functions that support HTTPs protocol and variables
- Add new tests
- Unit testing
- Testing in Bindplane
- Testing in Google SecOps

fix: secops processor works with https protocol

---

exporter/qradar/README.md

fix: QRadar README typo

---

receiver/splunksearchapireceiver/README.md
receiver/splunksearchapireceiver/receiver.go

Adds a readme to the Splunk Search API Receiver. Also adds some logging to show the end of receiver execution.

feat: SSAPI Readme

---

opamp/observiq/observiq_client.go
opamp/observiq/reload_funcs.go

Adds some debug logs to help diagnose agents failing to update their remote configs.

chore: Add debug logging

---

exporter/chronicleexporter/grpc_exporter_test.go
scripts/update-module-version.sh

- Fixes missed bindplane-agent go mod import that's causing tests to fail
- Updates update-modules script to look for bindplane-otel-collector

fix: Rebase cleanup

---

opamp/config.go
opamp/config_test.go
opamp/observiq/observiq_client.go
opamp/observiq/reload_funcs.go
opamp/observiq/reload_funcs_test.go

chore: Increase some logging levels to Info

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Need to do a patch release to fix SSAPI go module path. Bumps the version numbers for the modules.

chore: v1.67.1 patch release

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml
CONTRIBUTING.md
docs/development.md
manifests/README.md

Fix different references to `make build-binaries` and `make agent`

fix(v2): Update `build-binaries` references

---

receiver/splunksearchapireceiver/go.mod

Go mod path for this package was incorrectly defined.

fix: Update SSAPI go module path

---

factories/connectors.go
go.mod
go.sum

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/roundrobinconnector
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/failoverconnector

feat: Include roundrobinconnector and failoverconnector

---

docs/receivers.md
factories/receivers.go
go.mod
go.sum

Adds the netflow receiver for use with the collector
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/netflowreceiver

feat: Add netflow receiver

---

exporter/chronicleexporter/marshal.go
exporter/chronicleexporter/marshal_test.go

chore: update chronicle collectorIDs

---

.github/workflows/codeql.yml
cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
processor/topologyprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Updates the module versions to the new release version

chore: Update modules v1.71.0

---

scripts/install/install_macos.sh
scripts/install/install_unix.sh

Fixes an issue with the uninstall command output in the installation script.

fix: Uninstall command output

---

opamp/config_test.go

Tests will fail until https://github.com/observIQ/bindplane-otel-collector/pull/2154#pullrequestreview-2612327125 is merged.

chore(tests): Additional opamp/config tls tests

---

docker/Dockerfile.ubuntu

chore(docker): Remove no install recommends from Ubuntu build

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
processor/topologyprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

chore: Update modules to v1.71.2

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
processor/topologyprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

chore: Update modules to v1.71.3

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
processor/topologyprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

chore: Update modules to v1.71.4

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
processor/topologyprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Updating modules to collector version v1.72.0 now that collector v1.71.4 is released.

chore: Update modules to v1.72.0

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
processor/topologyprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Reverts observIQ/bindplane-otel-collector#2180

Revert "chore: Update modules to v1.72.0"

---

scripts/support/create-support-bundle.sh

Updated the support bundle to collect profiles in addition to the log files.

feat(support): Update support bundle script to include go profiling

---

exporter/chronicleexporter/go.mod
exporter/chronicleexporter/go.sum
go.mod
go.sum

Pull in fix for proxy support: https://github.com/grpc/grpc-go/releases/tag/v1.71.0

deps: Update grpc-go in chronicleexporter

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Bump module versions to the next release version

chore: Bump module versions v1.73.0

---

scripts/retrieve-available-components.sh

chore: Don't check out other branch after finishing available components script

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Update modules to v1.74.0 after the release.

chore: Update modules to v1.74.0

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Bump module versions to v1.74.0

chore: Bump module versions v1.74.0

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Update module version to v1.75.0 now that the release is done.

deps: Update module versions to v1.75.0

---

cmd/plugindocgen/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Updating modules to v1.75.0 now that the v1.74.1 release has completed.

deps: Update modules to v1.75.0

---

docs/development.md

Add a call out to verify the OTel release notes before updating OTel.

chore: Update development.md

---

scripts/retrieve-available-components.sh

To test, run script for v1.74.1, ensure generated entry looks like this:
```
s3event:
metadata:
- key: code.namespace
value: github.com/observiq/bindplane-otel-collector/receiver/awss3eventreceiver v1.74.1
```
not this:
```
awss3event:
metadata:
- key: code.namespace
value: github.com/observiq/bindplane-otel-collector/receiver/awss3eventreceiver v1.74.1
```

chore: Update available components generation script to account for s3event receiver

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
scripts/update-module-version.sh
updater/go.mod

Update module versions to the next collector release version

chore: Update module versions to v1.76.0

---

.github/workflows/manual_gcs_release_test.yml
.github/workflows/release.yml

While working in a different repo, I found it necessary to configure auth before configuring gcloud sdk.

fix(ci): GCS auth

---

receiver/awss3eventreceiver/internal/worker/worker_test.go
receiver/awss3eventreceiver/receiver_test.go

Just a few more nits noticed while working on #2352

chore: A couple more cleanup items for s3event receiver

---

exporter/googlecloudstorageexporter/go.mod
exporter/googlecloudstorageexporter/go.sum
extension/awss3eventextension/go.mod
extension/awss3eventextension/go.sum
internal/aws/go.mod
internal/aws/go.sum
internal/measurements/go.mod
internal/measurements/go.sum
internal/report/go.mod
internal/report/go.sum
internal/testutils/go.mod
internal/testutils/go.sum
processor/lookupprocessor/go.mod
processor/lookupprocessor/go.sum
processor/snapshotprocessor/go.mod
processor/snapshotprocessor/go.sum
processor/topologyprocessor/go.mod
processor/topologyprocessor/go.sum
processor/unrollprocessor/go.mod
processor/unrollprocessor/go.sum
receiver/awss3eventreceiver/go.mod
receiver/awss3eventreceiver/go.sum
receiver/oktareceiver/go.mod
receiver/oktareceiver/go.sum
receiver/windowseventtracereceiver/go.mod
receiver/windowseventtracereceiver/go.sum

This PR fixes the 13 moderate dependabot security alerts for the repo.

deps: Security alerts v1.76.0

---

.gitignore

Failing action: https://github.com/observIQ/bindplane-otel-collector/actions/runs/14620407601/job/41019895062
GoReleaser notes: https://goreleaser.com/errors/dirty/
Recommended fix: https://github.com/google-github-actions/auth/blob/main/docs/TROUBLESHOOTING.md#dirty-git-or-bundled-credentials
Testing probably involves running `make release-test`, but my computer can't handle that, every input takes about 10 seconds to complete if it's running.

chore: Add Google GitHub action credentials to gitignore

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Once the release action completes, this PR can be merged in to update the modules to v1.77.0.

deps: Update modules to v1.77.0

---

extension/awss3eventextension/README.md

chore: Add additional guidance to s3event extension readme

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Bump module versions back to v1.77.0 following patch release

chore: Bump module versions to v1.77.0

---

scripts/retrieve-available-components.sh

Type didn't match the path minus "extension".

chore: Update available components generation script for S3 event extension

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Changes module versions to v1.76.4 in prep for release

chore: Update module versions to v1.76.4

---

extension/bindplaneextension/README.md
extension/bindplaneextension/config.go
extension/bindplaneextension/extension.go

- Specify which distros the extension is used in
- Begin deprecation of the labels field since it was never actually used
- Document other config parameters

chore: Update bindplaneextension docs

---

.github/workflows/manual_gcs_release_test.yml
.github/workflows/release.yml

During the release, the latest install scripts will be copied to the GCS release bucket.
NOTE: This means any changes to the scripts will become live despite the release being in a "pre release" state. I spoke with @dpaasman00 about this. It is fine to start this way. The scripts are not changed often, and if they are changed, any relevant testing will be performed before the release.

chore(release): Publish latest install scripts to GCS

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml

Sign the BDOT MSI with our Extended Validation certificate via DigiCert.
https://github.com/observIQ/bindplane-otel-collector/actions/runs/15122366603
While I've confirmed that the signature in the screenshot above is not present on the MSI of the last release, I do still need to do some form of minor testing to ensure that above signature is what is required to make Windows trust our MSI out of the box.

feat: Sign BDOT MSI

---

.github/workflows/release.yml

Need to sign on the windows runner.

chore: Sign MSI on creation in release workflow

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Updates module versions post release

chore: Bump module versions to v1.78.0

---

manifests/observIQ/README.md
manifests/observIQ/manifest.yaml

Adds the github receiver into the observiq distribution

include github receiver into v2 collector (BPP-345)

---

docs/processors.md
factories/processors.go
go.mod
go.sum

Urgent GAP request to add the delta-to-cumulative processor to BDOT
[docs](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/v0.126.0/processor/deltatocumulativeprocessor/README.md)

feat: Add delta to cumulative processor (BPP-347)

---

.github/workflows/release-test.yml

Working run https://github.com/observIQ/bindplane-otel-collector/actions/runs/15469242220

fix(ci) Release test workflow

---

config/logging.yaml
exporter/chronicleexporter/config.go
exporter/chronicleexporter/factory.go
exporter/chronicleexporter/http_exporter.go

chore: Add logging for errored loads for Data Plane SecOps

---

docs/extensions.md
factories/extensions.go
go.mod
go.sum
scripts/retrieve-available-components.sh

Adds the JSON Log encoding extension to the BDOT collector.
- https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/extension/encoding/jsonlogencodingextension

deps: Add `jsonlogencodingextension`

---

scripts/package/postinstall.sh

Requires https://github.com/observIQ/bindplane-otel-collector/pull/2424
When BDOT_CONFIG_HOME is set in /etc/default/observiq-otel-collector or /etc/sysconfig/observiq-otel-collector, the install directory will be modified.
A follow up PR will make this change to the updater. Im waiting so I can base the change off of this PR https://github.com/observIQ/bindplane-otel-collector/pull/2436.

feat(linuxpackage): Configurable install directory

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Updating the modules to v1.80.0 after the v1.79.2 release.

chore: Update modules v1.80.0

---

plugins/apache_common_logs.yaml
plugins/cisco_asa_logs.yaml

- There was an indent issue in 2 plugins, causing this error: 
- Fixing the indent issue fixes the agent error

fix: fix plugins indent issue

---

exporter/webhookexporter/factory.go
exporter/webhookexporter/factory_test.go
exporter/webhookexporter/generated_component_test.go
factories/exporters.go

fixes webhook exporter generated tests that do not have a version to pass into NewFactory

chore: fix generation and test

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3eventreceiver/go.sum
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Update module versions to v1.80.1 in prep for patch release.

chore: Bump module versions to v1.80.1

---

CLAUDE.md
receiver/awss3eventreceiver/README.md
receiver/awss3eventreceiver/config.go
receiver/awss3eventreceiver/config_test.go
receiver/awss3eventreceiver/factory.go
receiver/awss3eventreceiver/internal/constants/constants.go
receiver/awss3eventreceiver/internal/worker/sns_parser.go
receiver/awss3eventreceiver/internal/worker/sns_parser_test.go
receiver/awss3eventreceiver/internal/worker/testdata/sns_notification.json
receiver/awss3eventreceiver/internal/worker/testdata/sns_notification_with_s3.json
receiver/awss3eventreceiver/internal/worker/worker.go
receiver/awss3eventreceiver/internal/worker/worker_test.go
receiver/awss3eventreceiver/receiver.go
receiver/awss3eventreceiver/testdata/test_config.yaml

Adds SNS support to the AWS S3 Event receiver

feat: bpop 3330 s3 sns sqs notification support

---

scripts/package/preinstall.sh

The branch `epic/linux-package-overhaul` will migrating the Linux user `observiq-otel-collector` to `bdot`. This works great when running as the default `root` user. When running as the `observiq-otel-collector` user, the upgrade fails with this error:
```
usermod: user observiq-otel-collector is currently used by process 5287
```
This PR updates the Linux package `preinstall` script to detect this scenario and stop the service before running usermod.
Release notes will go into detail here, to ensure users are aware that the package upgrade will stop and restart the service if they have configured their collector to run as the `observiq-otel-collector` user. Additionally, notes will be included to instruct users to update their systemd override to use `bdot` instead of …

fix(linuxpackage): Stop service before migrating username if running unprivileged

---

scripts/install/install_macos.sh

Based on the Linux change here https://github.com/observIQ/bindplane-otel-collector/pull/2536
Working great. Tested install locally and tested the generated uninstall command shown at the end of the install flow.

feat(install): Install macOS artifacts from bdot.bindplane.com

---

.github/workflows/stale.yml

productivity: add stale pr action

---

.github/workflows/stale.yml

Uses full action, instead of shared action, as a public repo can't access a private repo's workflows

chore: use full workflow, remove shared action

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Bump module versions for release

deps: Bump module versions to v1.83.0

---

scripts/install/install_macos.sh
scripts/install/install_unix.sh
scripts/support/create-support-bundle.sh

Make the P lowercase
This was done by hand, I have no clue what the original ascii font was and AI was really bad at this

fix: Bindplane banner in install scripts

---

.goreleaser.yml
scripts/install/install_macos.sh
scripts/install/install_unix.sh

fix(installscript): Add missing  prefix to curl url

---

scripts/install/install_macos.sh
scripts/install/install_unix.sh

Noticed this while testing that the link is 404ing just copying and pasting from the output of the install script was an incorrect URL:
```
===================================================
| Information
===================================================
Agent Home:         /opt/observiq-otel-collector
Agent Config:       /opt/observiq-otel-collector/config.yaml
Start Command:      sudo systemctl start observiq-otel-collector
Stop Command:       sudo systemctl stop observiq-otel-collector
Status Command:     sudo systemctl status observiq-otel-collector
Logs Command:       sudo tail -F /opt/observiq-otel-collector/log/collector.log
Uninstall Command:  sudo sh -c "$(curl -fsSlL https://bdot.bindplane.com/1.84.0/install_unix.sh)" install_unix.sh -r …
```

fix: add version to uninstall instructions link

---

.github/workflows/release.yml

chore(cicd): Change runner from 32x64 to 32x128 for release

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Update module versions for patch release

chore: Update modules v1.85.1

---

.github/workflows/release-test.yml
.github/workflows/release.yml
.goreleaser.yml

chore(release): Goreleaser docker retry

---

.github/workflows/manual_msi_build.yml
.github/workflows/release.yml
.goreleaser.yml

A couple goreleaser action versions were still using the old version - one of which caused the release to fail. All versions should be up to date now.

chore: Update all goreleaser action versions

---

cmd/plugindocgen/go.mod
exporter/azureloganalyticsexporter/go.mod
exporter/chronicleexporter/go.mod
exporter/chronicleforwarderexporter/go.mod
exporter/qradar/go.mod
extension/awss3eventextension/go.mod
extension/bindplaneextension/go.mod
go.mod
internal/rehydration/go.mod
processor/datapointcountprocessor/go.mod
processor/logcountprocessor/go.mod
processor/metricextractprocessor/go.mod
processor/samplingprocessor/go.mod
processor/snapshotprocessor/go.mod
processor/spancountprocessor/go.mod
processor/throughputmeasurementprocessor/go.mod
receiver/awss3eventreceiver/go.mod
receiver/awss3rehydrationreceiver/go.mod
receiver/azureblobrehydrationreceiver/go.mod
receiver/googlecloudstoragerehydrationreceiver/go.mod
receiver/splunksearchapireceiver/go.mod
updater/go.mod

Update module versions for patch v1.85.3 patch

chore: Update module versions v1.85.3
